### ISSUE TITLE
--no-cache argument does not work on windows10

### ISSUE THREAD

**Issue by ClementHector** [nerdvegas/rez#1002]
Hello,

I think a small bug exists in version 2.68.5 of rez,

![image](https://user-images.githubusercontent.com/7068597/103279504-3d91fb80-49ce-11eb-9101-1c17b7ae3e35.png)

It's the same through the configuration file.

Bye

**Comment by nerdvegas** [comment]
Hey,

This is working, it's just a little confusing. `--no-cache` disables _resolve_ caching. The `(cached)` you see above indicates that _package caching_ is active - it's pointing at a local disk cache of that package's payload. You can disable this with `--no-pkg-cache`

Hth
A
