### ISSUE TITLE
build environment is affected by "requires"

### ISSUE THREAD

**Issue by cuckon** [nerdvegas/rez#1003]
Hello there,

If I have a package.py like this:
```python
requires = [
    'python-3',
]

build_requires = ['python-2']
```
When build it I'd get a error:
```
18:01:44 INFO     Applying global preprocess function
18:01:44 INFO     Package attributes were changed in preprocessing:
Added attributes: ['build_command']
Resolving build environment: pype avalon_core maya_look_assigner pyblish_base pype_config ffmpeg python-3 publish_pipe python-2
The context failed to resolve:
The following package conflicts occurred: (python-3 <--!--> python-2)
The build environment could not be resolved:
The following package conflicts occurred: (python-3 <--!--> python-2)
```
Is it supposed to be so? From my understanding `requires` only take effect after rez-env, how come it being taking place when buiding the package? Is this intentional?

Thanks,
John.

**Comment by maxnbk** [comment]
requires -> runtime
build_requires -> at build time of dependent packages, and this package build time
private_build_requires -> only at build time of current package

**Comment by cuckon** [comment]
> requires -> runtime
> build_requires -> at build time of dependent packages, and this package build time
> private_build_requires -> only at build time of current package

That's what it is supposed to be. However `requires -> build time` in my case.

**Comment by cuckon** [comment]
It's a behaviour defined in rez itself. I don't think it make sense though.
I've created a relative [PR](https://github.com/nerdvegas/rez/pull/1004).

**Comment by nerdvegas** [comment]
Hey John,

Rez has always included both requires and
build_requires/private_build_requires in its build runtime. Changing that
would break backwards compatibility, so it's not an option. However, it
does make sense to add support for a build env that does not include the
runtime.

You can actually do this already, but with caveats:

```
@early()
def requires():
    if building:
        return ['python-3']
    else:
        return ['python-2']
```

There are limitations though:
* This only works for the package being built. Required packages will still
pull in their `requires as well as `build_requires`
* Variants are problematic

What I suggest we do is add a new package attribute that causes `requires`
to be ignored in the build env. Eg `build_ignore_requires = True`.

One limitation will remain however, and that's with variants.
Unfortunately at present, variants are just a list of requirements - it's
not possible to describe variant-specific build requirements. This is a
known limitation and needs to be fixed, but it needs to be done in its own
PR. Basically, we need to add support for dict-based variants, so you could
have this:

```
variants = [
    {
        "requires": ['python-2'],
        "build_requires": ['python-3]
    },
    ...
]
```

Thx
A

**Comment by cuckon** [comment]
Thanks @nerdvegas for your detailed explaination. It's a bit complicated considering backwards compacibility + required packages + variants.. For the time being, for my studio, I'm going to use the modified version of rez and keep it up with origin as we've just started and don't have much packages yet.

Cheers mate.

**Comment by dominiquekwiek** [comment]
Sorry to ping an old thread but looks like the `build_ignore_requires` attribute never got introduced.   We are facing the same problem as the OP.  Is there anyway to currently enable this behaviour?

**Comment by JeanChristopheMorinPerso** [comment]
Quoting Allan:
>You can actually do this already, but with caveats:
>
>```
>@early
>def requires():
>    if building:
>        return ['python-3']
>    else:
>        return ['python-2']
>```
>
>There are limitations though:
>* This only works for the package being built. Required packages will still
>pull in their `requires as well as `build_requires`
>* Variants are problematic

We'd be happy to accept a PR that adds a new `build_ignore_requires` attribute or maybe even a global config.

**Comment by dominiquekwiek** [comment]
> build_ignore_requires

We're hitting limitation 1).  We need a package in the `build_requires` and a different version in the `requires`.
