### ISSUE TITLE
bundled contexts ("bundles")

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#1009]
A mechanism for storing both a context, and the variants that context uses, into a single relocatable directory. This directory could then be copied to a server, or stored into an image, for standalone deployment. Note that packages need to be relocatable.

The process should be broken down into the following smaller operations, which can be useful in their own right:

1. Copy the variants in a context into a target pkg repo
2. "Retarget" a context to a nominated repo(s)
3. Allow relative-path pkg repo references in contexts
4. Explicitly disable memcaching in a context (and store this option as a context attribute). And/or, infer non-cachability when pkg repo path is relative.

In particular, separating out (1) and (2) will allow for scenarios where you may want multiple contexts to be retargeted onto the same pkg repo. This would allow for a new suite schema, where the variant payloads could all be stored into one repo within the suite directory, thus making the entire suite relocatable and standalone.

A bundled context would look like this:

```
/my_bundle
  /context.rxt  # retargeted to relative repo "./packages"
  /packages
    /python/2.7/...
    /foo/1.0.0/...
```

To create this bundled context in manual steps you would:
```
]$ rez-env foo bah -o tmp.rxt
]$ rez-context --show-uris --print-resolve | xargs -i rez-cp --variant-uri {} --dest-path ./my_bundle/packages
]$ rez-context tmp.rxt --retarget ./my_bundle/context.rxt ./my_bundle/packages 
]$ rm -f tmp.rxt
```

For convenience, a new rez-bundle tool is available, and does the equivalent to above:
```
]$ rez-env foo bah -o tmp.rxt
]$ rez-bundle tmp.rxt ./my_bundle
```

**Comment by mstreatfield** [comment]
> Note that packages need to be relocatable.
Presumably, this will respect the `relocatable` attribute in the package file? What is the behaviour if a package is not relocatable, error and exit?

**Comment by nerdvegas** [comment]
@mstreatfield you'll have control over this - default behaviour will be to fail, but you will also be able to:
* allow partial: Only add packages to the bundle that can be localised (so the context will not be entirely standalone)
* force everything regardless (YMMV)
