### ISSUE TITLE
problem with alias in powershell

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#1017]
From tests:

```
Line |
   4 |  function alias_test() { "echo test_echo" $args }
     |                                           ~~~~~
     | Unexpected token '$args' in expression or statement.
```

Seems related to: https://github.com/nerdvegas/rez/blob/master/src/rez/tests/test_shells.py#L384
I'm unsure as to why quotes are included in the alias command.

**Comment by instinct-vfx** [comment]
I can hopefully look into this. There is an issue with PowerShell that we discussed earlier somewhere in that the command vs. parameter escapes are different and hence plain concatenating them causes issues. It's too late atm for me to remember the specifics will try and come up with a more helpful reply tomorrow.

**Comment by nerdvegas** [comment]
Cheers! Yeah what I'm not clear on is why that alias command explicitly
includes the double quotes. Without them, the generated pwsh alias works
fine. So I don't know that there's anything wrong specifically with pwsh
shell impl..

**Comment by instinct-vfx** [comment]
I will try to take a look into it today. Seems @skral added this as part of other Windows fixes. Also keep in mind that different versions of PowerShell might have quite some difference.

**Comment by instinct-vfx** [comment]
How can i inspect or reproduce the error? I tried grabbing the lastest release and running the standard selftests. That yielded some weird results (the cmd tests being run in powershell trigger vscode to open the pyfiles mid-test run and i am also seeing some other oddities i wanna look into) but this particular one i do not see.

**Comment by nerdvegas** [comment]
It happened across all python versions in the macosx workflows, maybe
mac-specific? Note that I only saw it in the output though, for some reason
it didn't cause an error (which in itself may be another problem).

**Comment by instinct-vfx** [comment]
Got it now. And after cross checking it happens in all workflows on all platforms. Will try to look into this.

**Comment by instinct-vfx** [comment]
So i am pretty sure it is only a bug in the test definition itself. I tried building actual aliases locally and that seems to work just fine. Also removing the double quotes prevents the error locally for me.
