### ISSUE TITLE
Rez Can't See New Packages on Re-resolve

### ISSUE THREAD

**Issue by wjwilson** [nerdvegas/rez#1033]
Hi,
I'm having an issue where, once Rez has resolved a package in a Python session, it won't find updates to that package unless Python is restarted. The simplest example of this is in the rez-gui.

If I:
- Resolve a package in the gui
- Release a new version of that package
- Re-run the resolve.

it still finds the old version of the package and I have to restart the gui in order for it to see the new one. The same if I create a ResolvedContext in any python interpreter. I have turned off every form of caching I can find and the issue persists. From the documentation, I don't believe this is the expected behaviour.

I'm running:
- Windows 10
- Rez 2.72.3
- Python 3.7.8

I suspect I'm missing something obvious, but I can't see what it is.

**Comment by davidlatwe** [comment]
I think I know this one. You may have to call `FileSystemPackageRepository.clear_caches()` explicitly, if you need to release/install package while keeping another Rez session alive.

```python
from rez.package_repository import package_repository_manager
fs_repo = package_repository_manager.get_repository("<release_packages_path>")
fs_repo.clear_caches()
```

**Comment by wjwilson** [comment]
Hey David,

Thanks, that does work. I don't actually need to keep the initial Rez session alive, it's just that a particular Python process won't seem to let go of a package once it's resolved it.

Just as an example, to make sure this is the best solution--I'm working on our studio software launcher. It creates a `ResolvedContext`, say for the package `maya_env-1.0.0`, and uses that to launch Maya. If I release `maya_env-1.0.1`, close Maya, and relaunch it creating a new `ResolvedContext` it will still resolve to `maya_env-1.0.0`. In order for it to pick up the new package, I would have to restart the launcher as well as it seems to be the launcher's Python process that is caching the resolve. Does that sound right?

**Comment by davidlatwe** [comment]
> it's just that a particular Python process won't seem to let go of a package once it's resolved it.

The `ResolvedContext` is a context resolved from all the packages that it could get from the package repository instances, which are the instances of `FileSystemPackageRepository` for most cases. So the resolve isn't actually holding any package nor doing any kind of block, just that new package isn't able to be spotted by the repository instance due to it's internal caching.

> Does that sound right?

Yeah, and maybe you could call `clear_caches` for all package paths before your launcher resolve a context so you won't have to restart it.

**Comment by wjwilson** [comment]
Excellent. Thant's what I'll do then. Thanks.

**Comment by nerdvegas** [comment]
Hey, yes unfortunately this is an historical thing, cache state is global
(boo!). Ideally there would be some higher-level construct in rez that
would hold state (an App class for example). You'd then be able to clear
package caching within that context, or set that context to not cache in
that way (ie, expect that new packages may become visible during the
process lifetime). All stuff that's really obvious in hindsight :) (App
would also be the right place to override config settings).

Hth
A

**Comment by nerdvegas** [comment]
Closed in favor of https://github.com/nerdvegas/rez/issues/1043.
