### ISSUE TITLE
Aliases aren't accessible running python subprocess.run("alias", shell=True) in windows

### ISSUE THREAD

**Issue by Tilix4** [nerdvegas/rez#1078]
An alias set in `package.py` is accessible using python's `subprocess.run("alias", shell=True)` in linux but doesn't work for windows.

**Comment by instinct-vfx** [comment]
Can you share some more information about your setup? Particularly the version of Rez, the ShellPlugin you are using and how you actually run your command (e.g. `rez-env python mypackage -- python myapp` )

**Comment by instinct-vfx** [comment]
i think this is not a rez Issue but a CMD issue. IF you have not specifically set your shell to PowerShell then cmd is used. The problem is, that aliases do not exist natively in CMD, it is done through doskey, which is not a command but an executable. I guess calling the command from python bypasses doskey. I will give this a try though here and compare with powershell

**Comment by instinct-vfx** [comment]
I just tried this in CMD without rez and it still fails.

If you set an alias, e,g, `doskey test=calc.exe` you can run `test` fine and it launches the calculator.
If do the same like you did above it returns 1 and nothing happens. So this is nothing that Rez can fix for CMD i am afraid. In fact this also does not work in powershell either, it seems that subprocess simply bypasses both doskey macros in cmd and powershell functions in powershell.

Generally speaking subprocess does not execute a command in the shell you started python from, but instead creates a new process fork and a pipe to it if i am not mistaken. A simple workaround would be setting an env variable and use that to execute in your python code.

**Comment by Tilix4** [comment]
Ok thanks, I understand the issue and I'll end up using an env var I guess.

I was just confused it was working for Linux, but not for Windows.

If this is impossible to be fixed, I close the issue.
