### ISSUE TITLE
Disabling command aliases in rez env

### ISSUE THREAD

**Issue by johhnry** [nerdvegas/rez#1091]
Hi,

I have a Blender package configuration in my package directory and I would like to have a `blender` alias in zsh that would run the software in its environment like this :

```shell
alias blender="rez env blender -- blender"
```

However when I resolve an environment, the shell aliases are taken into account and therefore running `blender` never ends because it keeps calling itself.

Is it the right way to do this? If so, is it possible to disable shell aliases when inside a rez context?

Thanks

**Comment by davidlatwe** [comment]
As a workaround, maybe this
```python
def commands():
    alias("blender", "unalias blender; blender")
    ...
```
would work ?

**Comment by johhnry** [comment]
mmh this doesn't work :

```python
# packages/blender/2.93/package.py

name = 'blender'

version = '2.93'

description = 'Blender 2.93'

def commands():
    alias("blender", "unalias blender; blender")
    env.PATH.append("/home/josephhenry/Downloads/blender-2.93.0-linux-x64/blender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release")
```

```shell
$ rez-env blender

You are now in a rez-configured environment.

resolved by josephhenry@pop-os, on Sun Jun 06 19:33:23 2021, using Rez v2.69.6

requested packages:
blender           
~platform==linux  (implicit)
~arch==x86_64     (implicit)
~os==Pop-20.10    (implicit)

resolved packages:
blender-2.93  /home/josephhenry/packages/blender/2.93  (local)
$  blender alias blender
blender='rez env blender -- blender'
```

**Comment by bfloch** [comment]
I believe in bash rez alias becomes a function.
So you probably need to unset not unalias it, right?

**Comment by johhnry** [comment]
@bfloch Do you mean the `unset` bash function?

I tried:

```python
def commands():
    command("unset blender")
    env.PATH.append(".../blender/bin")
```

With 

```bash
alias blender="rez env blender-2.93 -- blender"
```

But it doesn't work either

**Comment by fnaum** [comment]
I do not have something to test here but what about using the "\" to temporarily disable the alias
something like 
`alias blender="rez env blender-2.93 -- \blender"` 
if that does not work you can have something along these lines
``` python
def commands():
    env.PATH.append(".../blender/bin")
    env.BLENDER_EXE(".../blender/bin/bledner")
 ```
then you can have something like

`alias blender='rez env blender-2.93 -- $BLENDER_EXE'`

**Comment by johhnry** [comment]
@fnaum 
Your example just escapes the `b` letter:

![Screenshot from 2021-11-30 21-41-18](https://user-images.githubusercontent.com/35373357/144124824-c08e3202-1759-4e26-9ec1-9f1a3627b10e.png)

> I do not have something to test here but what about using the "" to temporarily disable the alias

Did you meant that?

Also your second solution doesn't really correspond to what I am looking for since putting directly the path of the blender executable is the same as defining a custom shell alias (which I was doing before) and there's no point of using `rez` then.

But anyway I think I am going to close this issue since I can just launch the command with `rez env`!

Thanks ;)

**Comment by fnaum** [comment]
Hi @johhnry , I was referring to using the \ to skip any alias and default to the command (picked on the path)
A basic example would be something like
```bash
> ls
file1
file2
> alias ls=echo
> ls "now ls is echo"
"now ls is echo"
> \ls 
file1
file2
```
but maybe this is a behavior in `bash` and not in `zsh`

For the other suggestion, I just checked and I have some alias defined like this
```
alias bla='rez env package-version -c "\$TOOL_EXE"'
```
note that in this case the \ is just escaping the $ and you need double quotes so the env variable does not get expanded until it gets into the rez environment

If `TOOL_EXE` is the full path to an executable, this should work, as it will have priority over any alias defined
