### ISSUE TITLE
Using rez versioning regex in renovate

### ISSUE THREAD

**Issue by viceice** [nerdvegas/rez#1110]
Hi, I'm a maintainer of the [renovate bot](https://github.com/renovatebot/renovate) and we have a community contribution at renovatebot/renovate#10930 to integrate your `rez` versioning scheme.

For this we need some parts of your versioning regexes.  Are we allowed to do so?

**Comment by nerdvegas** [comment]
Hey,

I certainly don't mind personally, but I suppose it's a matter of determining what you're able to do given both our licenses (GNU GPL3 for me, GNU AGPL3 for you).

It looks like you're ok though: https://en.wikipedia.org/wiki/Affero_General_Public_License#Compatibility_with_the_GPL

If all you need to do is grab some regexes, I would just do that, and include a comment linking to the rez project.

Cheers
Allan

**Comment by viceice** [comment]
Thanks for info

**Comment by skral** [comment]
Hi @nerdvegas,

Long time no see. Hope you're well.

Opening this issue again. After some discussion on the PR using the regular expressions, the consensus is that copying the code with a simple comment won't be good enough to be license compatible, unfortunately. Ideally the original author of the regular expressions, you, can provide a license to use them. Creating a simple PR with the regular expressions and signing the CLA will do exactly that.

Any possibility you are willing to help us out here some more and commit that PR (non-functional) with just the regular expressions and sign the CLA for the [renovate bot](https://github.com/renovatebot/renovate) project? That way we can get renovate to understand rez licensing right away.

I am including steps to help make this as easy as possible:
1. Fork [renovate bot](https://github.com/renovatebot/renovate)
2. Create `lib/versioning/rez/index.ts`
3. Include the following text:
```
    version_range_regex = (
        # Match a version number (e.g. 1.0.0)
        r"   ^(?P<version>{version_group})$"
        "|"
        # Or match an exact version number (e.g. ==1.0.0)
        "    ^(?P<exact_version>"
        "        =="  # Required == operator
        "        (?P<exact_version_group>{version_group})?"
        "    )$"
        "|"
        # Or match an inclusive bound (e.g. 1.0.0..2.0.0)
        "    ^(?P<inclusive_bound>"
        "        (?P<inclusive_lower_version>{version_group})?"
        "        \.\."  # Required .. operator
        "        (?P<inclusive_upper_version>{version_group})?"
        "    )$"
        "|"
        # Or match a lower bound (e.g. 1.0.0+)
        "    ^(?P<lower_bound>"
        "        (?P<lower_bound_prefix>>|>=)?"  # Bound is exclusive?
        "        (?P<lower_version>{version_group})?"
        "        (?(lower_bound_prefix)|\+)"  # + only if bound is not exclusive
        "    )$"
        "|"
        # Or match an upper bound (e.g. <=1.0.0)
        "    ^(?P<upper_bound>"
        "        (?P<upper_bound_prefix><(?={version_group})|<=)?"  # Bound is exclusive?
        "        (?P<upper_version>{version_group})?"
        "    )$"
        "|"
        # Or match a range in ascending order (e.g. 1.0.0+<2.0.0)
        "    ^(?P<range_asc>"
        "        (?P<range_lower_asc>"
        "           (?P<range_lower_asc_prefix>>|>=)?"  # Lower bound is exclusive?
        "           (?P<range_lower_asc_version>{version_group})?"
        "           (?(range_lower_asc_prefix)|\+)?"  # + only if lower bound is not exclusive
        "       )(?P<range_upper_asc>"
        "           (?(range_lower_asc_version),?|)"  # , only if lower bound is found
        "           (?P<range_upper_asc_prefix><(?={version_group})|<=)"  # <= only if followed by a version group
        "           (?P<range_upper_asc_version>{version_group})?"
        "       )"
        "    )$"
        "|"
        # Or match a range in descending order (e.g. <=2.0.0,1.0.0+)
        "    ^(?P<range_desc>"
        "        (?P<range_upper_desc>"
        "           (?P<range_upper_desc_prefix><|<=)?"  # Upper bound is exclusive?
        "           (?P<range_upper_desc_version>{version_group})?"
        "           (?(range_upper_desc_prefix)|\+)?"  # + only if upper bound is not exclusive
        "       )(?P<range_lower_desc>"
        "           (?(range_upper_desc_version),|)"  # Comma is not optional because we don't want to recognize something like "<4>3"
        "           (?P<range_lower_desc_prefix><(?={version_group})|>=?)"  # >= or > only if followed by a version group
        "           (?P<range_lower_desc_version>{version_group})?"
        "       )"
        "    )$"
    ).format(version_group=version_group)
```
4. Create a PR
5. Sign CLA

This is purely your choice, of course. Let us know if you have any questions or concerns we can help with.

Cheers,
Sebastian

P.S.: [Here](https://github.com/renovatebot/renovate/pull/10930/files#r678945686) is the original thread about the license related concerns.

**Comment by nerdvegas** [comment]
Hey Sebastian!

No worries, I'll get this done for you in the next few days.

Cheers
A

**Comment by skral** [comment]
Hi Allan (@nerdvegas),

That's great. Thank you.

Cheers,
Sebastian

**Comment by nerdvegas** [comment]
Done, apologies for the delay.

Note that CLAassistant is complaining but I did the signing. I notice it's
saying "ajohns seems not to be a GitHub user", even though the PR is
clearly done by nerdvegas, not sure what's going on here.

Let me know if there's anything more you need.
A

**Comment by nerdvegas** [comment]
My username/email git conf was old, I didn't notice. This is fixed and I've
declined the previous PR and put in a new one:

https://github.com/renovatebot/renovate/pull/11634
