### ISSUE TITLE
Rez License Change: LGPLv3 to Apache2.0

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#1119]
We want to change rez license from LGPLv3 to Apache2.0. To do this requires permission from all code contributors.

## Why have you emailed me?

You are a contributor to the rez project and we require your permission to change its license.

## How do the licenses differ?

LGPLv3 is a copyleft licence, whereas Apache2.0 is a permissive license. A good short explanation of these licenses can be seen here: https://www.cnx-software.com/2011/10/10/open-source-licenses-overview-gpl-lgpl-apache-bsd/. In short, there are less limitations on how you can use rez if it is licensed with Apache2.0.

## Why Apache2.0?

Apache2.0 is the preferred license of the Academy Software Foundation (https://www.aswf.io/about/).

## Why do we want to do this?

LGPL creates a legal gray area for some studios, who may be hesitant to use the project for that reason. Under LGPL, a larger work using rez would need to provide the full rez sourcecode in its distribution, and would itself need to be LGPL-licensed, unless "dynamically" linked to rez (which in python could be interpreted as not being contained directly in the distribution).

## What do I need to do?

Either add a comment to this ticket, or reply to an email sent to you, using the following text:

```
I, <your full name here>, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.
```

Thank you kindly
A

**Comment by maxnbk** [comment]
I, Stephen Mackenzie, am a current or former contributor to the rez
project, and I give my permission to change its software license from
LGPLv3 to Apache2.0.

**Comment by davidlatwe** [comment]
I, Lai Ta-Wei, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by JeanChristopheMorinPerso** [comment]
I, Jean-Christophe Morin, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by instinct-vfx** [comment]
I, Thorsten Kaufmann, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by KelSolaar** [comment]
I, Thomas Mansencal, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by mchamberlain** [comment]
I, Morné Chamberlain, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by skral** [comment]
I, Sebastian Kral, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by zachlewis** [comment]
I, Zach Lewis, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by loonghao** [comment]
I, Long Hao, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by j0yu** [comment]
I, Joseph Yu, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by mstreatfield** [comment]
I, Mark Streatfield, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by renaudll** [comment]
I, Renaud Lessard Larouche, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by smaragden** [comment]
I, Fredrik Brännbacka, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by bfloch** [comment]
I, Blazej Floch, am a current or former contributor to the rez
project, and I give my permission to change its software license from
LGPLv3 to Apache2.0.

**Comment by bsergean** [comment]
I, Benjamin Sergeant, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by bareya** [comment]
I, Piotr Barejko, am a current or former contributor to the rez
project, and I give my permission to change its software license from
LGPLv3 to Apache2.0.

**Comment by dbr** [comment]
I, Ben Dickson, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by sparklabo** [comment]
I, Sehwi Park, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by nerdvegas** [comment]
Current stats:

* accepted: 20
* contacted and not heard from yet: 26
* contact details unknown: 7
* rejected: 0

**Comment by mottosso** [comment]
I, Marcus Ottoson, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0. 

Good move! ❤️

> which in python could be interpreted as not being contained directly in the distribution

Can you elaborate on this? I've seen similar notions in the Blender community. Does it mean that this comment..

```py
import rez
```

..is now dynamically linking Rez and is required to be LPGL'd as well? Or does it only apply if I put in a text file and upload it to GitHub?

**Comment by asztalosdani** [comment]
I, Daniel Asztalos, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by fxnut** [comment]
I, Andy Nicholas, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by sebastianelsner** [comment]
I, Sebastian Elsner, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by mychoko** [comment]
I, Mylene Pepe, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by adriankrupa** [comment]
I, Adrian Krupa, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by nerdvegas** [comment]
I don't believe so, I took it to mean that you're fine as long as the LGPL
code isn't actually embedded into your project - I would say that just
listing a requirement in your package, and importing said requirement, can
reasonably be considered "dynamic linking" and thus your own code does not
get pulled into the LGPL umbrella.

Here's a thread explaining from python POV (and which is my interpretation
also):
https://stackoverflow.com/questions/8580223/using-python-module-on-lgpl-license-in-commercial-product

Thx
A

**Comment by fnaum** [comment]
I, Federico Naum, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by gst** [comment]
I, Gregory Starck, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by pmolodo** [comment]
I, Paul Molodowitch am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by jasperges** [comment]
I, Jasper van Nieuwenhuizen, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by holofermes** [comment]
I, Fabio Piparo, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by cwmartin** [comment]
I, Christopher Martin, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by chadrik** [comment]
I, Chad Dombrova, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by yawpitch** [comment]
I have no interest in hindering this conversion, thus:

I, Michael Morehouse, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

However, that said:

> LGPL creates a legal gray area for some studios, who may be hesitant to use the project for that reason. Under LGPL, a larger work using rez would need to provide the full rez sourcecode in its distribution, and would itself need to be LGPL-licensed, unless "dynamically" linked to rez (which in python could be interpreted as not being contained directly in the distribution).

If we take that interpretation as gospel then Rez must remain under LGPL, since it vendors a copy of an LGPLv2.1 licensed library. 

I don’t subscribe to that interpretation; the vendored AMPQ library is not modified, it’s license accompany’s it, and a Rez user is not hindered from using a modified version of AMPQ, so IMHO (though with the usual IANAL caveat) all of the rights the LGPL exists to protect have been maintained. The vast majority of Rez is clearly not “based” on AMPQ, so at worst only the “minimal corresponding source” would need to be made available to downstream users of code incorporating Rez.

So no argument against the change, I’m just not certain a particularly copyleft-averse lawyer-type would be completely mollified with that vendored code in place.

**Comment by nerdvegas** [comment]
We've recently gotten rid of py-amqp specifically for this reason, see
https://github.com/nerdvegas/rez/releases/tag/2.96.0

And thanks for the email! You just saved me a bunch of work.
A

**Comment by yawpitch** [comment]
> We've recently gotten rid of py-amqp specifically for this reason, see https://github.com/nerdvegas/rez/releases/tag/2.96.0

I saw the move to Pika, but vendor/amqp still seems to be there.

**Comment by nerdvegas** [comment]
Ah so it is. I recall now I was planning on leaving removal of anything
until a last step before the actual licence change, in case we needed to
revert for whatever reason. So yes this will definitely be gone when the
licence change happens.

thx
A

**Comment by willjp** [comment]
I, Will Pittman, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by manuelkoester** [comment]
I, Manuel Köster, am a current or former contributor to the rez project, and I give my permission to change its software license from LGPLv3 to Apache2.0.

**Comment by pombredanne** [comment]
The setup.py still references the LGPL here https://github.com/nerdvegas/rez/blob/d4f29f882aec0c358451faa1f92c456ed7836fa3/setup.py#L77 and here https://github.com/nerdvegas/rez/blob/d4f29f882aec0c358451faa1f92c456ed7836fa3/setup.py#L104
