### ISSUE TITLE
Could not create named generator NMake

### ISSUE THREAD

**Issue by joeyskeys** [nerdvegas/rez#1122]
Hi guys,
I was trying to build libraries that need to invoke cmake, but rez keeps reporting the error message below:
`CMake Error: Could not create named generator NMake`
I've tried the method mentioned by willjp in #348, but didn't work out.
Any ideas?

**Comment by bareya** [comment]
@joeyskeys Have you installed vsudio properly with C++? That error appears most likely because cmake does not find nmake.

**Comment by joeyskeys** [comment]
I forgot to source VS develop environment bat, my bad.
The build tools are not in the PATH by default. This issue could be closed now.
