### ISSUE TITLE
Force rez to resolve ignored versions

### ISSUE THREAD

**Issue by EmileLabrosse1** [nerdvegas/rez#1125]
Hello !

I've been looking into the ignore package feature recently, and I was wondering if there is any way to force rez to resolve an ignored version. 
The reason I'm asking is because we would like to use ignored packages as staged releases at our studio.
We would ignore a package's version, then release it. And once it's been tested, we would un-ignore it so it's available to production.
We could also use it as a quick & easy rollback, rather than doing an entire new release, or moving a package between a staging and a production repo. 
The problem is, we cannot resolve an ignored version afaik.
I've looked into other ways of staging releases. Like having a staging repository, or releasing with a "-beta" token and filtering it out. But this would be the simplest solution for us.

Do you think that's something that would be possible in the future ? I would be happy to submit a PR.

Cheers,
Emile Labrosse
Pipeline Developer 
elabrosse@onanimationstudios.com

**Comment by instinct-vfx** [comment]
What do you mean specifically with "the ignore package feature"?

**Comment by EmileLabrosse1** [comment]
@instinct-vfx Sorry I wasn't very clear. Versions are ignored if there is a .ignore<version> file in the package's root: https://github.com/nerdvegas/rez/blob/master/src/rezplugins/package_repository/filesystem.py#L1029 
The rez-pkg-ignore command line can be used to create the .ignore file.

**Comment by davidlatwe** [comment]
Why not just stage the package to a place that is not in production's `rezconfig.package_paths` ?

**Comment by davidlatwe** [comment]
Ah sorry, you were looking for alternatives, I missed that. But seems like the package filter is already serving the purpose ?

How do you imaging that ignore/un-ignore switch work ?

**Comment by instinct-vfx** [comment]
Thanks for following up. The reason there is no override is that .ignore was specifically introduced to mark temporarily defunct packages. For example during packages being copied. Overriding this would not only pull in staging packages but also all these potential defunct packages and that seems like a bad thing to troubleshoot.

A way that seems close to what you are doing that would be supported out of the box is using package filters and rez-mv. rez-mv is like rez-cp just to move packages. So you could for example release as package-1.0.0.staging and then use rez-mv to rename it and drop the staging part.

**Comment by nerdvegas** [comment]
As others have covered already, you should not do this - ignored is ignored for a reason! You have other options:

* Use package filters. At Method we use filters to ignore `*.dev` versions by default, but we turn that filter off for testing purposes. Once tested, the non-dev equivalent package is released, and the dev version gets archived later (we could do a rez-rm instead these days but it didn't exist when we wrote this, and we also need our existing infra which syncs releases across all our sites).
* Install to some staging packages path. When you want to promote to production, either rez-mv or re-release the pkg into your official packages path. Staging runtimes would have this path visible, prod would not

Hth
A

**Comment by EmileLabrosse1** [comment]
Thanks guys for the explanations, I think I will go with package filters as you suggested.
Cheers !
