### ISSUE TITLE
rez pip installed prettytable-2.2.0 will not import

### ISSUE THREAD

**Issue by jlgerber** [nerdvegas/rez#1127]
prettytable relies on importlib from python 3.8+'s stdlib or a backport (importlib_metadata ) for earlier python versions to read version info from metadata in the dist-info or egg-info directory. 

As the metadata doesnt exist as part of the package, prettytable will not import. 

Shouldnt rez pip be generating said metadata?

**Comment by bpabel** [comment]
It does generate it, it just installs it into the wrong directory, one level above where it's supposed to be. There is an existing issue for this I believe, about a year old. I think there was recently a PR made to address it.

**Comment by bpabel** [comment]
#892 and #1123

**Comment by jlgerber** [comment]
well obviously i was far to lazy before writing the issue. Thanks for pointing out all of the prior work / related issues

**Comment by nerdvegas** [comment]
I've just commented on #1123 <https://github.com/nerdvegas/rez/pull/1123>,
I'd rather this be default behaviour unless there's a specific reason for
it not to be.
A

**Comment by nerdvegas** [comment]
Should be fixed in https://github.com/nerdvegas/rez/releases/tag/2.95.0
