### ISSUE TITLE
-- (double-dash) removes double quotes on Windows

### ISSUE THREAD

**Issue by epkaz93** [nerdvegas/rez#1133]
**Rez Version:** 2.95.0
**Platform:** Windows 10
**Working Rez version:** 2.69.6

Running rez commands with `--` causes double quotes to be removed from arguments after `--`.

Example:
 ```shell
rez-env python -- python -c "print('hello world')"
  File "<string>", line 1
    print('hello
               ^
SyntaxError: EOL while scanning string literal
```

Escaping the double quotes appears to work:
```shell
rez-env python -- python -c \"print('hello world')\"
hello world
```

**Comment by nerdvegas** [comment]
I'm thinking this may be a regression introduced in https://github.com/nerdvegas/rez/releases/tag/2.94.0. Is there any chance you could test with https://github.com/nerdvegas/rez/releases/tag/2.93.3 and see if that works?

**Comment by epkaz93** [comment]
> I'm thinking this may be a regression introduced in https://github.com/nerdvegas/rez/releases/tag/2.94.0. Is there any chance you could test with https://github.com/nerdvegas/rez/releases/tag/2.93.3 and see if that works?

Yeah it works correctly in 2.93.3
