### ISSUE TITLE
Ability to configure path separator in package commands per variable

### ISSUE THREAD

**Issue by JoshkVFX** [nerdvegas/rez#1142]
Hi all,

I've got a package that I'm currently building (shotgun event daemon and consumers) that expects one variable to be comma separated. I'd like to somehow mark that one variable as comma separated while all others would retain the default pathsep

Just wanted to see if anyone had any solution to this already, if not I'll start working on a PR myself

Thanks,
Josh

**Comment by nerdvegas** [comment]
Does this suit?

https://github.com/nerdvegas/rez/wiki/Configuring-Rez#env_var_separators
