### ISSUE TITLE
commands() does not get executed when running rez-build on Windows

### ISSUE THREAD

**Issue by Jawabiscuit** [nerdvegas/rez#1197]
Given this simple package.py
[package.zip](https://github.com/nerdvegas/rez/files/8027452/package.zip)

It appears that when running `rez build` in a pwsh terminal, that the print inside commands() never gets executed. Furthermore, the print inside `if building` doesn't get called either.

I was originally trying to set an environment variable when `building` is True but realized commands isn't getting called to begin with.

Here's some more information and output:

```
rez build

================================================================================
Building rez_build_bug-0.1.0...
================================================================================
Resolving build environment: 'python-2+<3'
resolved by Jonas@vrexton2, on Tue Feb 08 15:59:18 2022, using Rez v2.103.4

requested packages:
python-2+<3
~platform==windows       (implicit)
~arch==AMD64             (implicit)
~os==windows-10.0.19041  (implicit)

resolved packages:
arch-AMD64             c:\users\jonas\packages\arch\AMD64
                    (local)
os-windows-10.0.19041  c:\users\jonas\packages\os\windows-10.0.19041
                    (local)
platform-windows       c:\users\jonas\packages\platform\windows
                    (local)
python-2.7.18          c:\users\jonas\packages\python\2.7.18\platform-windows\arch-AMD64\os-windows-10.0.19041  (local)

Invoking custom build system...
Running build command: python D:\git\rez-build-bug/package.py

================================================================================
Build Summary
================================================================================

All 1 build(s) were successful.
```

Quoting Jason Scott on the rez-talk Slack:

> I had a related question (at least, I think it's related) about that:  https://rez-talk.slack.com/archives/CHELFCTFB/p1640821230183300

> I want to run a command during build that comes from another package (in private_build_requires).  I tried: pre_build_commands, but as far as I can tell, because it's pre, the required packages haven't run their commands block yet, so the commands aren't exposed yet commands using the building object (example from docs in https://github.com/nerdvegas/rez/wiki/Package-Commands#building), but it looks like commands aren't running during building?  I can't seem to get that doc example to work . . .

**Comment by nerdvegas** [comment]
A package's commands() is never run when that package is getting built,
that isn't what it's for. Perhaps you want to use
https://github.com/nerdvegas/rez/wiki/Package-Commands#pre-build-commands?

The commands func is used to configure the runtime containing that package.
If you're building a package then its build runtime doesn't contain itself
(it isn't built yet!).

Hth
A

ps - this comes up now and again, it may be worth updating the wiki on
commands() to make this clear.

**Comment by Jawabiscuit** [comment]
Ok, yeah, the wiki definitely needs an update then. I was essentially going off that while I was creating, coincidentally, a boost package of my own for Windows.

https://github.com/nerdvegas/rez/wiki/Building-Packages#package-communication 

Beginning with:
> For example, our boost package's commands might look like so:

**Comment by nerdvegas** [comment]
That example is correct though. In this case boost is in the build runtime
that is being used to build maya_utils. Boost's commands() will be run, but
maya_utils' will not.

I've made a note to update these docs to make this clearer, as well as
https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#commands

thx
A

**Comment by Jawabiscuit** [comment]
Ah, I guess I skimmed over that part, but I do understand what you're saying as I have read about the "build runtime" concept before. Thanks!

**Comment by nerdvegas** [comment]
Closing, see https://github.com/nerdvegas/rez/issues/1198
