### ISSUE TITLE
Add config for whether suites stay in $PATH within rez

### ISSUE THREAD

**Issue by blake-sweeney** [nerdvegas/rez#127]
Currently, if you run a command from a suite then rez will keep that one, source suite in the $PATH while removing the rest.

After speaking with Allan, it would be great to allow these three options as rez configs --
1. Never include suites from the $PATH within the rez-env
2. Current behavior, include the suite that the command is from within the $PATH
3. Keep all suites in the $PATH, regardless of where the command came from

There are many cases where only one application is overridden in a suite and still wants to be able to call other commands from inherited suites.

**Comment by nerdvegas** [comment]
Done.
