### ISSUE TITLE
Problems with memcached resolves not seeing newly installed package versions.

### ISSUE THREAD

**Issue by herronelou** [nerdvegas/rez#1276]
Upon installing a new package version, a new resolve will not find that package, and keep resolving to the state before the release.

**Environment**
* OS: Windows 10
* Rez version 2.104.9
* Rez python version 3.7.9

**To Reproduce**
With a default rezconfig:
- create package foo, and install (not release, though I haven't tested) version 0.0.1
- Launch a python shell with rez in the env, import ResolvedContext
- `rc = ResolvedContext(['foo'])`
- Notice that it properly resolved to foo-0.0.1
- without closing the python process, install foo-0.0.2
- `rc = ResolvedContext(['foo'])`
- Notice that it still resolved to foo-0.0.1

**Expected behavior**
Should resolve to 0.0.2

**Actual behavior**
Resolved to 0.01

**Digging a bit deeper**
Eventually, the ResolvedContext object calls resolver.Resolver.solve()
In turn, this calls Resolver._get_cached_solve(), which has some logic to check if things have changed since caching.
However, line 214 of resolver.py, self.memcached_servers is [], so the function bails early and doesn't check any of the update logic and says it's going to resolve "not from cache".

Quite a few things happen, which eventually leads to the following "traceback" (most recent on top as per python order):
(function/method, python_file : line_number)
```
- wrapper, lru_cache.py:71
- iter_packages, packages.py:570 <<< This iter is what returns the old list of versions
- wrapper, memcached.py:265
- iter_packages, packages.py:562  
- __init__, solver.py:474
- get_variant_slice, solver.py:474
- _get_variant_slice, solver.py:2358
- __init__, solver.py:976
- __init__, solver.py:1243
- __init__, solver.py:1995
- _solve, resolver.py:407
- solve, resolver.py:123
- wrapper, memcached.py:271
```

I'm not too sure yet how to get it to resolve properly, but this has been causing me some issues.

**Comment by herronelou** [comment]
I have tried `ResolvedContext(['foo'], cache=False)` as well as setting a memcache_uri, and neither solved the problem.

It seems like it's not liking having the python process running and having changes done at the same time, but I have a UI launcher that lets me get into different rez envs, and artists are expected to keep this open, having to close and re-open every time a package gets released will not work.

I suspected it might be the lru_cache causing this, so I tried to clear it with `package_repository.package_reposiory_manager.pool.cached_get_resource.cache_clear()` but that also did not solve it.

**Comment by herronelou** [comment]
And as often, turns out I complicated my own life, and` package_repository.package_reposiory_manager.clear_caches()` did the trick.
I'll close this, as it's probably not an actual bug. A bit more info about the caching mechanism in the docs would be welcome though.

**Comment by JeanChristopheMorinPerso** [comment]
That cache is supposed to be an implementation detail I think, which unfortunately leaks a little bit too much. At least that's what I remember.

**Comment by nerdvegas** [comment]
Hi Erwan,

You are correct, this isn't actually a bug, it is annoying though.

Rez caches package info globally within the current py proc. You need to
call clear_caches() to clear that global state, as you've discovered.

A decent improvement to rez would be to add a first class "app" object that
acts as a place to store state like this, as well as config settings. Right
now both package cache state and config settings are effectively global
data. It's one of those things that's obviously an issue in retrospect! I
doubt adding this App context would be trivial though.

Hth
A

**Comment by herronelou** [comment]
Thanks Jean-Christophe and Allan for the clarification.

For now clearing the cache does the trick, and as my launcher matures it might implement stuff like timestamp locking which will reduce the need to constantly clear the cache (only clear cache when timestamp changes, or something custom is being resolved).
It's still early in my Rez journey but I do find that I have to dig into the code more often than not to understand things that the documentation doesn't talk about or glances over.

**Comment by nerdvegas** [comment]
The docs need attention yes, but this is an OS project with limited
resources so it's often a choice between fixing bugs, adding features or
upgrading docs, and docs often draw the short straw!

In the interests of tracking where we should be concentrating on improving
docs, I've started this discussion:
https://github.com/nerdvegas/rez/discussions/1277

Please add notes there going over the issues you've hit up on!

Thx
A

**Comment by herronelou** [comment]
Will do, thanks!
