### ISSUE TITLE
convert_old_environment_variable_references causes problems

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#143]
This function was introduced fairly recently, but it has the effect of expanding environment variable references when before they were not. This is causing some of our packages to fail (for a stupid reason, but failing still).

Given that unexpanded variables end up expanded by the target interpreter anyway, why was this added? I think I need to remove it but I'd rather know why it's there in the first place.

Cheers
A

**Comment by nerdvegas** [comment]
Bam! Now I remember why I did the whole literal/expandable strign support in the first place. It was because of this issue.

I've implemented a fix in branch 'issue_143'. Env-var references such as "$THIS" now get converted to "${THIS}", but are unaffected if within a literal() construct.

**Comment by mstreatfield** [comment]
I picked this branch up after your comment in pull request #134.  The formatter unit test is broken and I am not so clear from all the other changes what the expected behaviour is meant to be to know if it's a bug or not:

    $ ./rez selftest --formatter
    =====================================================================
    FAIL: test_formatter_rex (rez.tests.test_formatter.TestFormatter)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/rez/issue_143/lib/python2.6/site-packages/rez-2.0.BETA.30-py2.6.egg/rez/tests/test_formatter.py", line 20, in test_formatter_rex
        self.assert_formatter_equal('Hello, ${{world}}!', 'Hello, ${Earth}!', world="Earth")
      File "/tmp/rez/issue_143/lib/python2.6/site-packages/rez-2.0.BETA.30-py2.6.egg/rez/tests/test_formatter.py", line 13, in assert_formatter_equal
        self.assertEqual(self.formatter.format(format, *args, **kwargs), expected)
    AssertionError: 'Hello, ${world}!' != 'Hello, ${Earth}!'
    
    ----------------------------------------------------------------------
    Ran 2 tests in 0.020s
    
    FAILED (failures=1)

**Comment by nerdvegas** [comment]
Hey Mark,

Yeah I just looked at this. I don't know why the UT expects that result - I would expect '${{world}}' to format to '${world}' regardless, since '{{..}}' is supposed to be treated as a literal '{..}'.

I've changed the UT to expect this instead and I've added another test case, and everything is passing.

Thx
A

**Comment by nerdvegas** [comment]
Closing this for now, I think this has all been addressed.
