### ISSUE TITLE
Add system.home to rex

### ISSUE THREAD

**Issue by rminsk** [nerdvegas/rez#153]
$HOME comes up many times when defining preference paths and such.  It would be nice to have rex expand the users home directory with something like '{system.home}'

**Comment by chadrik** [comment]
since it's an environment variable it should be easily accessible as `env.HOME`.  is there a reason that is not sufficient?

**Comment by rminsk** [comment]
Under windows it will be HOMEDRIVE/HOMEPATH.  With system.home we can treat the users home directory uniformly across platforms.  Should system.home be getpwent and SHGetFolderPath or the environment?

**Comment by mstreatfield** [comment]
I had need of this yesterday too as I have Windows and OSX support working now.  I went with `os.path.expanduser('~')` as it is much cleaner I think.

I'm happy to add it and make a pull request, I should be able to do it on Monday.

**Comment by rminsk** [comment]
Implemented in pull request commit dce3a1d46eec21e7652a45b76434c22386443dc5

**Comment by nerdvegas** [comment]
fix has been added to resources2 branch.
