### ISSUE TITLE
PYTHONPATH not set for simple package

### ISSUE THREAD

**Issue by sebastianelsner** [nerdvegas/rez#184]
I have the following package:

```
name = 'sqlalchemy'

version = '1.0.0'


def commands():
    env.PYTHONPATH.append('{this.root}/python')

timestamp = 1429880382
```

in this hierarchy

```
/home/sebels/packages/
├── arch
│   └── x86_64
│       └── package.py
├── hello_world
│   └── 1.0
│       ├── bin
│       │   └── hello_world
│       └── package.py
├── os
│   └── CentOS-6.6
│       └── package.py
├── platform
│   └── linux
│       └── package.py
├── python
│   └── 2.6.6
│       ├── package.py
│       └── platform-linux
│           └── arch-x86_64
│               └── os-CentOS-6.6
│                   └── bin
│                       └── python -> /raid/standards/base-setups/rez/bin/python
└── sqlalchemy
    └── 1.0.0
        ├── package.py
        └── python
            └── sqlalchemy
```

rez-env finds the package sqlalchemy, but the PYTHONPATH is not set, when doing 
```
echo $PYTHONPATH
```
in the resulting shell.

replacing
```
env.PYTHONPATH.append('{this.root}/python')
```
with 
```
 env.PATH.append('{this.root}/python')
```
works. the root path is added to $PATH.

Any hint on why this happends or how I could debug?

**Comment by nerdvegas** [comment]
Hi Sebastian,

I cannot see how that could be happening. Run 'rez-context -i' in the resolved shell too see exactly what commands are being sourced, I suspect something in your bashrc etc is overwriting the env var.

**Comment by sebastianelsner** [comment]
That might be the case. Will check on Monday! Thank you!

**Comment by sebastianelsner** [comment]
Indeed one of the script in profile.d did not include $PYTHONPATH
