### ISSUE TITLE
Detatched Node In Conflict Graph

### ISSUE THREAD

**Issue by mstreatfield** [nerdvegas/rez#201]
We have found a case where the conflict graph drawn by rez results in detached nodes.  The behaviour is the same regardless of the `prune_failed_graph` option.

I have a small collection of packages that demonstrate this problem however I am unable to upload them to GitHub due to firewall issues.  I have created them as a [private gist](https://gist.github.com/mstreatfield/f5c63ca43f82545da358). 

If I run:

```
rez env spam foo --no-implicit -v -v -v -v -o /tmp/fail_without_eggs.rxt
rez context --graph /tmp/fail_without_eggs.rxt
```

The graph is drawn correctly with the conflict nodes correctly attached.  If I run:

```
rez env spam foo eggs --no-implicit -v -v -v -v -o /tmp/fail_with_eggs.rxt
rez context --graph /tmp/fail_with_eggs.rxt
```

The graph is drawn incorrectly.  There is a `py-2.7` node which is marked as a conflict but not attached to the parent node that is requesting it (which, in this case, should be `bar`, _I think_).  With `prune_failed_graph` set to `false` an additional branch is drawn which is also not attached to the conflict nodes (even though it contains a `py` node).  

I'll email you the conflict graphs separately, perhaps you can attach them to the issue on my behalf - it makes much more sense when you see them.

**Comment by nerdvegas** [comment]
Thanks Mark,

Not sure when I'll get the chance to look at this (and - damn - I really thought I'd fixed this) but thanks for the repro info - I will definitely get to this at some point.

**Comment by nerdvegas** [comment]
graph algo changed significantly since this old ticket, probably not repro'able
