### ISSUE TITLE
support json-encoded rxt files

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#214]
Yaml is slow, taking ~ 0.25s to dump to string for a large resolve. Json does it in ~ 0.01s.

Make encoding a configurable option, and detect format on read.

**Comment by mstreatfield** [comment]
I am curious to see what counts as a 'large resolve' - how many packages?  We have some environments where the time to dump the context is closer to 1 second already.

**Comment by nerdvegas** [comment]
Off the top of my head maybe 80 packages? I guess if you're hitting 100+
that could go up a fair bit, simply because the graph would get bigger in a
non-linear way (exponential? Not sure).

I don't know how much a custom dot write function might fix things, but I
think it's worth a shot - 1/2 second seems an awful long time just to dump
a graph to text, and it should be easy enough to replace -  we don't need a
general case, just something that dumps the types of graphs we generate.

I've spotted a few other potential optimizations, I'll try them out in an
optimizations branch soon.

A

**Comment by nerdvegas** [comment]
Just realized I mixed up two related issues... It's yaml dump and
conversion of pygraph to dot string that are causing the rxt write times,
just to clarify.

**Comment by mstreatfield** [comment]
Ok... most of our production environments run to around 300 packages... the solve times are equally as long.

**Comment by nerdvegas** [comment]
Holy shit.

Ok, I'm sure there are further optimizations possible, it just depends how much effort we're willing to put in. I can think of a few options, on phone ATM but will expand later, maybe this warrants a general thread.

**Comment by mstreatfield** [comment]
Yeah, we try not to do things by half if we can possibly avoid it!

We would obviously be interested in any optimisations that are available and achievable.  We are working towards deploying the resources2 branch into production (pending some failing OSX tests I need to look into).

I am interested in the mongo branch to see if that helps resource time, but am beginning to think a pass on resolve time might be required.  Aside from the number of packages (and versions) we have, I think a problem might be that we have some broad version ranges/poorly defined dependencies.  As a result I think the solver is carrying around some large version ranges (lots of small python objects) resulting in lots of comparisons on each phase.  I also think we have some non-mutually-exclusive variant-funkiness which we've touched on before.

But yes, happy to spin this out into another thread.

**Comment by nerdvegas** [comment]
I've added support for storing contexts as json, much faster than yaml. However I've left the default config setting to yaml for the moment (see 'rxt_as_yaml' setting). Studios will want to make sure all their users are using this newer rez version before turning json writes on.
