### ISSUE TITLE
write custom pygraph dot write function

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#215]
pygraph's own function is slow, taking ~0.4s(!) on large resolves.

This combined with yaml dump is contributing to about 1/2 second of the time it takes to rez-env, which is significant when we get a memcache hit on a big resolve, often this is ~1/3rd the total time spent.

**Comment by nerdvegas** [comment]
This has been done. Have also switched to an internal 'compact' dot format, which is a lot smaller than native dot.

**Comment by mstreatfield** [comment]
Fede and I discovered a problem with this yesterday - he is working on a bug report for you.

**Comment by nerdvegas** [comment]
you meant a PR right? :D
