### ISSUE TITLE
_rez-complete throws an exception if paths in packages_path don't exist

### ISSUE THREAD

**Issue by reedwade** [nerdvegas/rez#225]
rez/packages_.py:iter_package_families() presumes the paths given to it actually exist

I'm unsure if the best fix is to check it there or if it would be better to have the check further down, like in the filesystem plugin.

In the meantime, I have made a small patch to rez/packages_.py that just checks the directories exist or not.

**Comment by nerdvegas** [comment]
Indeed it does. Thanks Reed, will address this soon.
A

**Comment by nerdvegas** [comment]
Hi Reed,

Fix has been implemented in branch issue_225 and merged into resources2, let me know if you have any issues.
Thx
A
