### ISSUE TITLE
Mac Setup - platform package not found

### ISSUE THREAD

**Issue by ylathouris** [nerdvegas/rez#230]
Hi,

I am trying to setup rez on my mac laptop. I have installed it as per the documentation on Github. I have also built rez as a rez package using `rez-bind rez`. When I try to create an environment I get this:

```
rez-env rez

rez: PackageFamilyNotFoundError: package family not found: platform (searched: /Users/yanilathouris/packages; /software/packages)
```

Have I missed some platform specific setup? I don't have a platform package in any of my search paths. Is this something I am suppose to create or should rez do that for me? Sorry if this is really basic.

Cheers

**Comment by nerdvegas** [comment]
Hey Yani,

Yeah there are some packages that Rez expects to be there but are not
created by default. They're easy to create though.

Actually now it's even easier. I'm just now working on a new branch -
'repository' - that provides a bunch of installer packages - so far I have
gcc, python, tbb, ilmbase, openexr, boost and hdf5, as well as platform,
arch and os. If you get that branch, all you need to do is cd into the
'repository' directory and into the package you want to install, then
running 'rez-build' will locally install that package for you. For 3rd
party stuff (such as boost etc) it expects the source archive to be on
disk. See the repository/README file for more instructions.

The platform, arch and os packages that are already there may not be
exactly what you want (for instance, only an 'Ubuntu-12.04' OS package is
available). What you should do is just copy the whole repository directory
to another location, make your own repository out of it, make whatever
changes you like (or add new packages, such as a different OS), and
rez-build from there. Soon you'll be able to rez-release too, I just need
to merge a recent PR first, but in the meantime local package installs
should see you through.

I'd like to have all the software listed in the current 2015 VFX Reference
Platform available in time for Siggraph this year, but we'll see (trying to
get everything building correctly for the more involved packages -
gcc/boost/qt and so on - is a fair bit of work).

All that aside - Rez packages are just a case of having the right
directories and files in the right place, and a package.py with a
'commands' section that does the right thing. You can always throw one
together manually and it generally isn't very difficult to get it working.
Once you have some installed and working you'll see what the structure
should be.

Hth, hit me up if you have any more issues.

Thx
A

**Comment by nerdvegas** [comment]
Yani, the 'repository' directory has now been merged into the main resources2 branch. If the platform package that you need isn't there (osx) please just add it and send a PR.

I'll close this issue for now..

**Comment by ylathouris** [comment]
No worries,

Thanks Allan!
