### ISSUE TITLE
Unicode characters in package.py with git commit messages.

### ISSUE THREAD

**Issue by smaragden** [nerdvegas/rez#239]
With a name like Brännbacka.
The package.py file fails on release after the commit messages are written to the file.
And the file does not contain encoding string.

My temporary fix was to add before line:
https://github.com/nerdvegas/rez/blob/resources2/src/rez/package_serialise.py#L137

```
print >> buf, "# -*- coding: utf-8 -*-"
```

**Comment by nerdvegas** [comment]
Hey Fredrik,

Thanks for the info. This has come up before but evidently isn't fixed,
I'll look into this when I get a chance. In the meantime you might have to
lose your umlaut :)

A

**Comment by nerdvegas** [comment]
Should be fixed in resources2 now. Note that in order to release a package.py containing unicode in the first place, it needs to have the coding hint present.
