### ISSUE TITLE
config_version missing on the package_base_schema

### ISSUE THREAD

**Issue by fnaum** [nerdvegas/rez#245]
Hi Allan,

While doing some automation code that reads/modifies/writes packages in batches I noticed that at writing time it removes the fields that are not in the schema i.e `config_version`. 

I found that back in ~Dec 2014 you started deprecating this field.  We haven't taken any advantage of this field yet but seemed that it would become useful in the feature. So, I just wanted to know the reason behind its deprecation and if there is a mechanism that replaces it now.

Cheers
Fede

As a side question,  let me know if you are interested in an optional feature that allows reading the packages (yaml and py) in order (data becomes and `orderedDict`), so later you can dump them in the same order ( or pass any arbitrary key order). For us, this becomes useful when we modify package using an automation tool and we want to minimize the diff for the code reviews.

**Comment by nerdvegas** [comment]
Hey Fede, below.

On Mon, Aug 31, 2015 at 2:09 AM, Federico Naum <notifications@github.com>
wrote:

> Hi Allan,
>
> While doing some automation code that reads/modifies/writes packages in
> batches I noticed that at writing time it removes the fields that are not
> in the schema i.e config_version.
>
> I found that back in ~Dec 2014 you started deprecating this field. We
> haven't taken any advantage of this field yet but seemed that it would
> become useful in the feature. So, I just wanted to know the reason behind
> its deprecation and if there is a mechanism that replaces it now.
>

It wasn't used anywhere yet so I removed it. The original intention was for
this attribute to detect when an incompatible package.py change is
introduced in rez. But I'm not sure that will ever happen tbh - breaking
backwards compatibility would be a drastic thing to do. But even if this
ever does happen, and config_version is reintroduced, simply lack of it
being in the package.py can just imply that its value is zero.


> Cheers
> Fede
>
> As a side question, let me know if you are interested in an optional
> feature that allows reading the packages (yaml and py) in order (data
> becomes and orderedDict), so later you can dump them in the same order (
> or pass any arbitrary key order). For us, this becomes useful when we
> modify package using an automation tool and we want to minimize the diff
> for the code reviews.
>

I am in fact very interested, if you could contribute this when possible
that would be great.

Cheers
A

**Comment by fnaum** [comment]
Hi Allan,

I think you are right, we can always treat the lack of if as version 0.

I'll create a PR during the week.

Cheers
Fede
