### ISSUE TITLE
rez-yaml2py does not retain 'plugin_for' key

### ISSUE THREAD

**Issue by damntourists** [nerdvegas/rez#267]
When converting a package.yaml to python, it appears that rez-yaml2py is not retaining the 'plugin_for' key.

**Comment by maxnbk** [comment]
@nerdvegas I don't believe this is still a bug. Something else must have fixed it in the interim, but here is a simple reproduction case of it working:
```
$ cat package.yaml

name: 'test'

version: '1.2.3'

plugin_for:
  - maya
  - nuke

has_plugins: True
```
```
$ rez-yaml2py package.yaml
# -*- coding: utf-8 -*-

name = 'test'

version = '1.2.3'

has_plugins = True

plugin_for = [
    'maya',
    'nuke'
]
```
