### ISSUE TITLE
pip --target option causing problems on CentOS 

### ISSUE THREAD

**Issue by cwmartin** [nerdvegas/rez#274]
Currently running into an issue on CentOS ( and seemingly other RHEL based distros ) using the --target option with pip 7.1.2 where the /tmp directory pip is looking for doesn't exist. Seems that instead of the lib/python directory pip is expecting, the directory that gets created is actually lib64/python. 

Below is the error that is thrown:
```
Exception:
Traceback (most recent call last):
  File "/home/christopher/packages/pip/7.1.2/platform-linux/arch-x86_64/python-2.7/python/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/christopher/packages/pip/7.1.2/platform-linux/arch-x86_64/python-2.7/python/pip/commands/install.py", line 351, in run
    for item in os.listdir(lib_dir):
OSError: [Errno 2] No such file or directory: '/tmp/tmpdWyLx6/lib/python'
```

I'd run into this previously and the workaround was to use the --install-* distuils options instead of --target.

I've made the following changes locally to the pip call in RezPipInstall.cmake and it's working correctly...

```
COMMAND pip install --no-deps --install-option=--install-scripts=${destbinpath} --install-option=--install-lib=${destpath}
```

It would likely make sense to use the --install-data and --install-headers as well to ensure that the lack of --target option is compensated for.

I can submit a pull request with the changes but I wanted to run this one by first incase I'm missing something.

Cheers,
Chris.

**Comment by nerdvegas** [comment]
Hey Christopher,

Happy to take the PR and test on non-RHEL destro, if it works then I'd say
we take the change. Probably better to individually control the bin, lib,
include etc paths separately anyway.

Thanks,
A

**Comment by cwmartin** [comment]
Great. I'll send a PR soon.

**Comment by mvtk** [comment]
Just a quick heads up, using --install-options removes support for wheel packages. This may or may not be relevant for rez. I am fighting this in a different project currently and thought it would be worth mentioning.

**Comment by nerdvegas** [comment]
Ack. Python packaging is the worst.

Thanks for the head's up mvtk. I think we're already in trouble there
though - even in the current implementation I'm using --intsall-options as
well as --target, iirc I had to in order to control the install path for
binaries.

Thx
A

**Comment by instinct-vfx** [comment]
Hrmpf. Signed in with the wrong account  above heh. The reasons this happens is that --install-options are targeted at the build process which is not used in wheels as they are supposed to be binary relase packages.

I am not sure how much sense this makes...just that it causes a lot of headache for me heh

Thorsten

**Comment by cwmartin** [comment]
So would the preference be to find a way to allow for whl packages, or to stick with the from-source method that currently exists?

Cheers,
Chris.

**Comment by nerdvegas** [comment]
Actually it looks like we may be forced to deal with wheels.

I'm working on a rez-pip-install tool atm, to install a python module and
dependencies with a single commandline tool. But it looks as though pip
downloads the dependencies as wheels.

I wonder, and I haven't tried this yet - I wonder if installing into a
virtualenv would help? That might allow us to isolate the lib, binaries etc
easily and move them into a rez package. I don't know yet if I might run
into any pathing problems though, ie absolute paths baked into binaries and
so on.

A




On Wed, Dec 2, 2015 at 7:08 PM, Christopher Martin <notifications@github.com

**Comment by cwmartin** [comment]
I was using the --no-binary option to force pip to download the tar.gz source rather than the whl files. Might work for what you're doing...

```pip install --download=<dest_path> --no-binary=:all: <package>```

Pip does have the disclaimer in their docs..."Note that some packages are tricky to compile and may fail to install when this option is used on them"

**Comment by nerdvegas** [comment]
Nice one Christopher, I'll try that out.

I think no binary is more appropriate in our case, although we can look
into adding binary support later on. The user might want to build the
source using a specific compiler, or compiler flags and so on. In any case
I'm fine with building from source being the initial implementation.
However I do wonder if using a virtualenv might still simplify things for
both cases. I'll do some investigation.

Thx
A


On Tue, Dec 8, 2015 at 7:43 AM, Christopher Martin <notifications@github.com
