### ISSUE TITLE
inaccessible packages path in context breaks rezolve when lack of package should be what breaks a rezolve

### ISSUE THREAD

**Issue by maxnbk** [nerdvegas/rez#281]
It appears that paths added to the REZ_PACKAGES_PATH var must be available from the point of view of all resolving users, even if no resolved packages in the request are being served from that location;

The presence of an inaccessible path in an environment variable is what breaks rez, not the lack of access to a package, when the condition that should break rez, is the inability to locate a desired package on the contexts present search paths.

**Comment by nerdvegas** [comment]
(false alarm)
