### ISSUE TITLE
Memcache issue when TimestampRule and  RangeRule are in use

### ISSUE THREAD

**Issue by fnaum** [nerdvegas/rez#301]
Hi,

I have a question regarding the memcache algorithm when using a filter with a `TimestampRule` and a `RangeRule`.

Context: We modelled a production environment, by locking the resolve in time for all packages but  we use the inclusion filter (RangeRule) to consider all available version for particular packages. In rez speak 
```
> rez-env [Packages List] --time T --include 'range(foo)' 'range(bar)'
```

So basically, it uses only packages released *before T* but for package` foo` and `bar` all version released *after T* are also considered.

This works perfectly without having memcache active.

This is the currente algorithm in `resolver.py` ` _get_cached_solve()`

        If there IS a resolve timestamp (let us call this T):
            - fetch a non-timestamped memcache entry;
            - if entry then:
              - if no packages have changed, then:
                - if no packages in the entry have been released since:
                  - if no packages in the entry were released after T, then
                    - use the entry and return;
                - else:
                  - delete the entry;
              - else:
                - delete the entry;
            - fetch a timestamped (T) memcache entry;            
            - if no entry, then fail;
            - if packages have changed, then:
              - delete the entry;
            (*)
              - fail;
            - else:
              - use the entry.

For this particular case, at first glance, It seems we would need to add another check for *released packages after T* for the packages in the `RangeRule` at (*), and invalidate/renew the cache if any.  Am I correct?

As I said this is a particular case, I'm not sure how to implement this as a general case yet, without extracting/analysing  the rules from the filters. Thoughts?

Is there any other way I can achive the production lock version but for package `foo` and `bar`?

Cheers,
Fede

**Comment by fnaum** [comment]
Hi Allan,

Thanks for the clarification. What I'm using is the global `--time` timestamp. I initially mentioned `TimestampRule`, because at some point in the [`Resolver`](https://github.com/nerdvegas/rez/blob/master/src/rez/resolver.py#L67) code it combines this global timestamp with the package filter into a single filter, and it converts the `--time` flag into a `TimestampRule.after`. 

The problem with the caching  that I'm seeing is probably due to the combination `--time` and `RangeRule` that I'm using. 

I tried  the `--time` plus a `PassTruRule` for the package that I want to consider and it picked the last version for that package. But I think as soon as release a new version of that package I won't get the latest next time, because I'll get the timestamped resolve from the cache, right?

Is there a way to model the scenario that I depicted before where I want rez to consider all packages up to time `T`, but for a particular package, it considers all versions including the ones that are released after the `T` point?. (And that works with memcache ON).?

Thanks,
F

**Comment by nerdvegas** [comment]
Hey Fede,

I'm not clear on exactly the error you're getting. Are you saying that the
latest version of the passthru package is getting selected, even though
that release is after the --time that you've specified? And is this
happening with cache on, or off, or both?

You can consider all packages up to T, but all versions for a specific
package, yes - just do what you're doing but don't use --time. This should
work regardless of whether caching is on or not. The --time option always
means, exclude *all* packages after T - it takes precedence over all other
filters. You can't do what you're asking for on the command line, but you
can configure it with a rezconfig. You would do:

    package_filter:
      excludes:
      - after(187655573)
      includes:
      - mypackage

See the comments on package_filters in rezconfig.py for examples of how it
works.

Thx
A

**Comment by fnaum** [comment]
Hi Allan,

I got you. I'll try the filter with the rules as you mentioned and report back.

PS: 
It is still possible to get packages released after `T` when you use the `--time` flag. I'm guessing now that this is not the expected behaviour. 
ie.
```
rez env foo --time 1456261219 --include 'range(foo)' --exclude 'range(foo<X)'
```

where X is any version  gives you the latest `foo` package that is released after `1456261219`.

**Comment by fnaum** [comment]
I will test a bit more but 
```
rez env foo --exclude 'after(1456261219)' --include 'range(foo)'
```
Seems to work fine. 

Thank you so much!

F

**Comment by nerdvegas** [comment]
Hey Fede,

that is definitely not expected behaviour. Would you mind adding an issue?

Cheers,
A

**Comment by nerdvegas** [comment]
Ah yes, that combo of --exclude and --include will work just fine. I didn't
think of doing it that way.

A

**Comment by nerdvegas** [comment]
Ah yes and I think I know what this might be. Should be a pretty easy fix.

A

**Comment by fnaum** [comment]
Hi Allan, 

I submitted a new issue https://github.com/nerdvegas/rez/issues/303
You can close this one now.

Thanks,
Fede
