### ISSUE TITLE
rez variant environment var during build

### ISSUE THREAD

**Issue by maxnbk** [nerdvegas/rez#304]
Multi-issue Issue, but all in the same ballpark so keeping collected in one item.

First, introduce REZ_BUILD_VARIANT env var during rez-build process which is the value of the REZ_VARIANT_INDEX -ed variant string (so for variant ['platform-linux','arch-x86_64','os-Ubuntu16'], give back "platform-linux,arch-x86_64,os-Ubuntu16".

Second, Additional REZ_VARIANT_PATH which is just the same thing, with slashes instead, to be modified in next item.

Third, add ability to specify custom rez-variant paths as dictionary key in variant list. This would override #2 item variant path var appropriately, while leaving build variant var as the key.

**Comment by nerdvegas** [comment]
REZ_BUILD_VARIANT_REQUIRES was added in https://github.com/nerdvegas/rez/releases/tag/2.25.0

Will add REZ_BUILD_VARIANT_SUBPATH in upcoming release.

Dict-based variants are a heavy enough feature that they deserve a separate ticket. Note however that a coming feature (hashed variants) will alleviate the need for this to a fair degree.

Will close this ticket with next release as it addresses these points.
