### ISSUE TITLE
Missing tools

### ISSUE THREAD

**Issue by suryakiran** [nerdvegas/rez#307]
Hi, I checked out the master branch of rez and the installation went fine. But I do not see any of the tools mentioned [here](http://nerdvegas.github.io/rez/#more-tools) installed.

Am I missing something or the tools have been replaced by some other commands ?

**Comment by nerdvegas** [comment]
Hi,

That documentation is very old (rez-1) and those tools no longer exist. As
long as you have the tools such as rez-env, rez-context, rez-build and
various other rez-xxx available, you're good to go.

hth
Allan

**Comment by suryakiran** [comment]
Hi, 

Thanks for the reply. I guessed so. I've some scripts written (with rez-1.7.0) which are using rez-which. what is the equivalent for that ?

**Comment by nerdvegas** [comment]
I'd say rez-search will be what you want, it does quite a lot more than
rez-which did.

Thx
A

**Comment by suryakiran** [comment]
Thanks for the help. I'm closing this now.

Surya
