### ISSUE TITLE
Allow overriding configuration options like package_filter via REZ_XXX environment variables

### ISSUE THREAD

**Issue by instinct-vfx** [nerdvegas/rez#320]
Currently only POD configuration options can be overridden using environment variables (like REZ_OPTION). Support for all options should be provided.

Probably using JSON notion in the environment variables. Opinions?

**Comment by mottosso** [comment]
(Sneakily) Added to this commit: https://github.com/nerdvegas/rez/commit/6d75e61ba505fcfe945975eccf893ed3d94cfbd7 (September 2018) and documented here: https://github.com/nerdvegas/rez/wiki/Environment-Variables#runtime-environment-variables
