### ISSUE TITLE
rez-gui will not open contexts if a rez-release is in process

### ISSUE THREAD

**Issue by darthgabz** [nerdvegas/rez#323]
This error is thrown when a rez-release for a package is in process and I try to open a context that has that package in its resolve. Once the release has completed the context opens as expected.

```
rez: PackageDefinitionFileMissing: Missing package definition file: FileSystemPackageResource({'version': '2.14.0', 'repository_type': 'filesystem', 'location': '/tools/share/', 'name': 'pkg'})
```

**Comment by nerdvegas** [comment]
https://github.com/nerdvegas/rez/releases/tag/2.2.0
