### ISSUE TITLE
How to print env as "rez-config package --print-env" in prior versions

### ISSUE THREAD

**Issue by hongloull** [nerdvegas/rez#324]
This is not a issue, but I can not find a way to do this in current version. In version 1.7, we can use "rez-config package --print-env", but "--print-env" has been removed in current version, is there a way to do the same thing?

**Comment by nerdvegas** [comment]
Heya, I can't remember exactly what this printed, but Rez-context should give same info and more.

A

**Comment by hongloull** [comment]
Hi nerdvegas, thanks a lot and with your help, I got it(rez-context -i).
