### ISSUE TITLE
add configurability of package orderers

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#329]
Package orderers as found in package_order.py aren't yet configurable via rezconfig.py. Should support something like:

package_orderers:
- type: soft_timestamp
  package_families: ["maya*"]
  timestamp: 3456789
  rank: 0

**Comment by JeanChristopheMorinPerso** [comment]
@renaudll @JeanChristopheMorinRodeoFX  (Sorry to poke your personal account, but I don't have your RodeoFX account). I was going into the old issues and found this one. When we upstream our changes for this, can you link to this issue please? So basically, RodeoFX just did this feature. We just need to upstream our changes.

**Comment by renaudll** [comment]
Sure thing!
