### ISSUE TITLE
Configurable name for 'package' file.

### ISSUE THREAD

**Issue by martinpengellyphillips** [nerdvegas/rez#331]
Some of our developers are evaluating Rez currently and we now have a name clash with an incumbent system that already uses a `package.py`.

To avoid having to maintain separate branches for the Rez trial, is it possible to configure Rez to look for an alternately named file (e.g. `rez_package.py`)?

If not possible currently, can I suggest adding support for this.

**Comment by instinct-vfx** [comment]
Hey Martin,

It would be great to see you guys join Rez! It is currently not possible afaik. You should be able to hack that in https://github.com/nerdvegas/rez/blob/eebd0936d8a6ac0f77d7cbaed17ae9065574d4f9/src/rezplugins/package_repository/filesystem.py . You want to change occurrences of get_file(self.path, "package") I THINK.

**Comment by nerdvegas** [comment]
Heya Martin,

It isn't possible currently, but I think it'd be a worthy addition and
doesn't strike me as difficult to add.

Thx
A

**Comment by martinpengellyphillips** [comment]
Thanks guys.

**Comment by holofermes** [comment]
Hey guys,

Considering that "package" is the only name allowed, this change should be so that it would extend the names that a package could be called rather than replace it altogether.

With this in mind we'd have a new option called "additional_package_name" as a StrList, and the logic would be to look for the default name "package" first, then use the additional_package_name in case of failure.

Does this sound too complicated?

**Comment by nerdvegas** [comment]
I think that's fine, although I'd go for "package_filenames" and have it
defaulted to ["package"].

Also note that this should actually be a config setting on the 'filesystem'
package_repository plugin. Strictly speaking none of the rest of the rez
code should know that packages are loaded from package.py files. You'd add
this to src/rezplugins/package_repository/rezconfig (note that this config
file is still in old yaml format! Have to get around to updating it - but
it works).

Hth
A

**Comment by martinpengellyphillips** [comment]
Agree with @nerdvegas here - the goal is that we can configure Rez to *not* pick up and interpret a `package.py` that is used for other purposes when an alternately named package file for Rez exists.

**Comment by holofermes** [comment]
Here is a starting [PR](https://github.com/nerdvegas/rez/pull/332).

rez-selftest --packages work. I had to make sure multi-packages can still define their own package name, as well as making sure that when installing a new variant over an existing package, the destination name is being used.

**Comment by nerdvegas** [comment]
Nice one Fabio, I'll get this merged soon.

A

**Comment by nerdvegas** [comment]
This has been merged, closing.
