### ISSUE TITLE
missing setup.py

### ISSUE THREAD

**Issue by larsbijl** [nerdvegas/rez#334]
can't seem to find the `setup.py` which is required in the `install.py`

```
running in /python setup.py install
/software/rez/rez-install/CentOS/6/2.0.0/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory
```

**Comment by instinct-vfx** [comment]
setup.py was dropped in the "cleanup" commit ( ff70672c0faba3ee64cbeb6613a7f2c9f572b71c ). As it's in the commit message it seems to be on purpose. 
Re-adding the file works fine here to deploy and the installed version also seems to work for now.

**Comment by larsbijl** [comment]
thanks that worked.
@nerdvegas what is supposed to replace the setup.py?

**Comment by nerdvegas** [comment]
Whoops, that's a fail on my behalf. I haven't touched the installation in a
long time and I thought setup.py was a hangover from long ago.

I can't easily fix this from work. If one of you could submit a PR I can
merge it online and get it fixed ASAP. Otherwise I'll fix it tonight.

Thx
A

**Comment by nerdvegas** [comment]
Scratch that. Just fixed it.

A
