### ISSUE TITLE
env.PATH manipulations break alias command on Windows

### ISSUE THREAD

**Issue by yawpitch** [nerdvegas/rez#343]
On Windows if a package.py (or **any** previously loaded package.py) does an _env.PATH.prepend_ or _env.PATH.append_ **BEFORE** a call to the _alias_ function, the _alias_ function will fail with the following error printed to the launching terminal:

> 'doskey' is not recognized as an internal or external command

This is because by default (ie without setting rez to pass through the PATH var from the parent), the PATH variable is being cleared at the moment of the first call to _env.PATH.prepend_ / _env.PATH.append_, which then makes it impossible for the shell that's running the resolved context file to find the _doskey.exe_ command. The resolved_context.py file then runs _executor.append_system_paths()_ which by default re-establishes the basic part of the PATH required by Windows to once again find the _doskey.exe_ file, but at that point it's already too late for the _alias_ to have worked.

End result: the alias fails to be created with an unexpected error message, but the executable the error message describes is once more available to the user by the time the shell has resolved.  This was not easy to track down.

This all goes back to what can only be described as a **"**Feature**"** of Windows; CMD.exe as a shell has built-in commands (set, call, etc), and doskey is in theory one of those commands, but unlike most of the others it's a distinct .exe, so you can get yourself into a situation where a shell cannot find one of the built-in commands that is a from-the-manufacturer part of that shell.  Go figure.

Working on a potential fix where we lazy-load the actual path to the doskey executable and use that instead.

**Comment by nerdvegas** [comment]
Hey Michael,

Just bear in mind that this is a general issue that needs fixing across the
board. What we need is smarter management of PATH during command execution.

An idea I have in mind is to:

1) Store pre-rez-env value of PATH;
2) on env.PATH.append(x), actually do:
    export __PATH=$__PATH:x
    export PATH=$__PATH:$__PRE_REZ_PATH

This should be further generalised so it's one of several different modes,
and can be applied to all env-vars, or a particular set.

A



On Thu, Aug 25, 2016 at 3:17 PM, Michael Morehouse <notifications@github.com

**Comment by michaelmovies** [comment]
Fixed in #341.

**Comment by michaelmovies** [comment]
Agreed, but a much larger issue (especially given the PATH char length limitations on Winblows) than what's ultimately causing this.

I think the patch I just pushed is a reasonable solution: doskey will effectively be in the C:\Windows\system32 directory for all version of Windows that should be found in the wild, and probably will be forever.

M
