### ISSUE TITLE
local_packages_path should be a list

### ISSUE THREAD

**Issue by ttanimura** [nerdvegas/rez#368]
It would be nice if `local_packages_path` was a list, exactly like `packages_path`, and if `rez-env --no-local` would ignore all paths in `local_packages_path`. 

At Imageworks we have a setup where facility wide things are installed on a special show called `spi`, which has the advantage of keeping the same directory structure for both facility and show specific things:

- `/shots/spi/home/packages`
- `/shots/$SHOW/home/packages`

This structure is also reflected in users' development areas:

- `/shots/spi/home/dev/$USER/packages`
- `/shots/$SHOW/home/dev/$USER/packages`

Which gives rise to the need for multiple local package paths. 

Ideally we would have `local_package_paths` be a list and then configure packages_path like this:
`packages_path = local_packages_path + [whatever other paths you want]`

Has there been any discussion on making the setting a list?

**Comment by ttanimura** [comment]
Or, I guess since local_packages_path is also used by rez-build to determine where to put packages, maybe a better thing would be a setting that lets you control what paths are excluded when you use the --nolocal option in rez-env

**Comment by nerdvegas** [comment]
Yeah I think something along those lines sounds good - perhaps simply
'extra_local_packages_path'. If present, these paths would be appended
after local_packages_path, and before packages_path. If --no-local is used,
they are skipped.

Further to this, I've thought before that it'd be useful to also have
config driven paths. For example, let's assume we have the following
configuration somewhere in rezconfig.py:

custom_package_paths:
  testing:
    paths: ['/svr/packages/testing']
    priority: 25

This would register a 'testing' package path, which you could include
using: "rez-env --include-paths testing". The 'priority' value would
determine where the paths are injected in the path list (smaller = earlier)
- perhaps local_packages_path has priority 10, extra_local_packages_path
20, packages_path 30 and so on. We could also have an
'include_custom_package_paths' if you want to include some of these by
default, and a matching --exclude-paths to remove them.

Thus, for your example, perhaps you would have:

custom_package_paths:
  spi:
    paths:
    - /shots/spi/home/packages
  - /shots/spi/home/dev/$USER/packages
    priority: 25

include_custom_package_paths:
- spi

Then to run the equivalent of no-local, you would instead go:

]$ rez-env --exclude-paths spi pkg1 pkg2... pkgN

As an added nicety, the output of rez-context could show the custom path
label to the right, similar to how "(local)" is already printed.

Thoughts?
A

**Comment by ttanimura** [comment]
I like the idea of named groups of paths. It would give us the flexibility to include/exclude things in a more intuitive way. Local paths could just be a group called `local`.

The priority thing sounds good, but I would also be happy with the config being explicit about how it wants things ordered: `packages_path = local + show_specific + facility_wide`

If there was such as thing as a `extra_local_packages_path`, you may even want a different set of priorities in that list vs `packages_path`... although I could be overthinking it.

**Comment by nerdvegas** [comment]
Yeah that might be a better approach to controlling the path order.
Something like:

packages_path_order:
- local_packages_path
- spi
- packages_path

Where (local_)packages_path represent the existing searchpaths. If any
entry in this list doesn't match a named path group, it's just ignored.

**Comment by nerdvegas** [comment]
Closing as duplicate.

This is addressed in: https://github.com/nerdvegas/rez/pull/428, although I need to make some changes.
https://github.com/nerdvegas/rez/issues/426
