### ISSUE TITLE
Using rez env interactively in windows

### ISSUE THREAD

**Issue by bpabel** [nerdvegas/rez#375]
What is the preferred way of creating interactive rez environments?

I have several rez packages built and `rez env` is resolving them, but it doesn't seem to be applying them to the current shell (windows cmd).  

For example, I'm using `rez env` to build a context with the `requests` python library

```
rez env requests
```

Rez appears to find and resolve the package, but it's not updating the `PYTHONPATH` in my shell.  

If I run the following command, it will launch a child shell and the packages are correctly applied.  Is this how it is supposed to work -- that you have to launch a child process to apply the package environment?

```
rez env requests -c CMD
```

**Comment by nerdvegas** [comment]
Hey,

rez-env requests is supposed to put you into an interactive subshell,
configured for that environment. When you're in the new shell, the prompt
is updated so that something like ']$' becomes '>]$' (note prepended
chevron).

There must be some problem in your scenario - some issue with the shell
startup. I'm not familiar with how this should work on Windows so I'm
hoping others will chime in.

Thx
A

**Comment by instinct-vfx** [comment]
Can you share some more information like the code of the package.py file to investigate?

Cheers,
Thorsten

**Comment by assumptionsoup** [comment]
I took another stab at getting rez to work on windows today.  I have this same issue with the hello_world example.  In windows cmd.exe and in git-bash `rez-env` does not put the environment in a sub-shell, and therefore it does not affect $PATH.

**Comment by elrond79** [comment]
Out of curiosity, what happens if you do "rez-env PACKAGES -- cmd.exe"?

**Comment by bpabel** [comment]
@elrond79 Yes, that will drop you into a shell, but that is different from the behavior in other shells.  In other shells, not specifying a command will give you an interactive shell.  The current behavior (without the PR I submitted) when using rez-env in a windows CMD shell is to spawn a shell with the correct rez enviroment, but then immediately exit.

**Comment by instinct-vfx** [comment]
There are different PRs doing similar things or tackling it slightly different. We definitely need to clean up the windows side of rez and rework the cmd plugin a bit.

**Comment by bpabel** [comment]
Fixed with #377
