### ISSUE TITLE
Question about use with Deadline render manager

### ISSUE THREAD

**Issue by bpabel** [nerdvegas/rez#381]
Are any studios currently using rez with Deadline?  I'd be interested in hearing your process for getting the Deadline Render plugins to execute in rez environments.

**Comment by bpabel** [comment]
FYI, for now I'm just passing the user environment to Deadline via the custom environment key value options.  So the rez environment isn't being resolved on the farm machines.  It looks like the newer versions of Deadline have some features that make executing rez on the render slaves before the actual slave command a little easier.

**Comment by ClementHector** [comment]
Hello, did you find a way to resolve rez environment in deadline?

**Comment by bpabel** [comment]
I used the Deadline [GlobalJobPreLoad.py](https://docs.thinkboxsoftware.com/products/deadline/10.0/1_User%20Manual/manual/application-plugins.html#application-plugins-globaljobpreload-script-ref-label) script to modify the command line for the job.

I updated the submitters to pass along the `rez_used_request` environment variable.  Then the plugin uses that to prefix the job launch command with a "rez-env" command to launch it in a rez environment.

Looks something like this:

```python

def __main__(deadlinePlugin):
    job = deadlinePlugin.GetJob()
    rez_args = job.GetJobExtraInfoKeyValue("rez_used_request")

    def callback(exe, args, pwd):
        new_args = "{} -- {} {}".format(rez_args, exe, args)
        return ("rez-env", new_args, pwd)

    deadlinePlugin.ModifyCommandLineCallback += callback
```
Depending on how your exe paths and environment are setup, you may need to do some escaping or quoting for the exe to get the command to run correctly. May also need to do some checking so that it doesn't try to modify a job command that wasn't submitted with a rez environment.

**Comment by ClementHector** [comment]
Thank you very much, that's pretty much the idea I had. But I didn't know there was a callback command. It helped me alot, it works perfectly now.

**Comment by tweak-wtf** [comment]
Cheerio. I'm also trying to achieve the same thing but I can't get the workers to launch the rez exe... do you know which environment variable to set in order to tell workers to look for executables in a custom directory? I have installed rez on a network share that I would like to use

**Comment by bpabel** [comment]
@tweak-wtf For render nodes, I've generally installed rez locally on the machines and added the rez bin/Scripts directory to the `PATH` variable so that the deadline nodes can launch it.  If you really want to use it from a network share, you can still do that, just need to update `PATH`
