### ISSUE TITLE
Exclude changelog from released package files

### ISSUE THREAD

**Issue by bpabel** [nerdvegas/rez#382]
I think this should at least be an option.  Several of our repos go back years and there's just no reason to have several thousand lines of commit messages in the package files.

Maybe with the recent change to make it easier to include release tag messages, the changelog should only contain release tag messages, and not every commit message.

**Comment by elrond79** [comment]
We found this annoying as well, so I added a configuration option to set a maximum number of commits to include.  The pull request is here:

https://github.com/nerdvegas/rez/pull/357

**Comment by bpabel** [comment]
Great, thanks.  I didn't even see the max_package_changelog_chars config option.  I do prefer truncating by number of commit messages rather than number of characters.
