### ISSUE TITLE
Solver Boundary Assertions

### ISSUE THREAD

**Issue by AAorris** [nerdvegas/rez#383]
When solving for a request that involves API breaking changes, I feel like rez encounters a **grey area issue**.

I would define the gray area issue like this:

> A lack of explicit boundaries impacts the user's ability to verify that a given resolve does not contain a naively bounded request for a child, given the child has released an API breaking change in a version (package-BOUNDARY+).

The solution I've considered is that the resolve provides a **warning** if a boundary is not clearly respected. I would imagine that a boundary would be a configuration setting in either a context, the rez settings, or in a package repository.

The boundaries could be defined as assertions that have two forms:

1) All requests have a high bound of (BOUNDARY)
2) All requests have a low bound of (BOUNDARY)

The assertions should raise a warning, and if there was an appropriate place for the configuration settings, there should be the ability to turn that into an error or exception that fails a resolve.

I'm not sure if there is already something that can make these assertions, or if all the faculties for a solution like this are in place.

@nerdvegas, I would be curious about your thoughts:

- If you feel like it would be feasible to implement
  - If so, an estimate of what needs to be done (where) to implement it

**Comment by nerdvegas** [comment]
So, do you mean that a package should be able to define the constraints
under which it should be required by other packages?

For example, if I have package 'foo', and I know that major version changes
== API breakage, are you suggesting we could do something like so:

# package.py
name = "foo"
requirement_rank = 1

So here, 'requirement_rank' indicates that other packages should have
requirements on foo bounded at least to the major version (rank==1).
Failure to do so will result in either a warning or error, depending on
configuration.

I think this would be a useful feature. It'd be an update to the solver - a
day or two of work I think.

Thx
A

**Comment by AAorris** [comment]
I think that would be the case. Would `rank==2` then do the same for anything not bounded to the minor version?

Perhaps I can take a look at a pull request then.

**Comment by nerdvegas** [comment]
Yes, rank==2 would mean requirements have to be down to the minor version.

There would also be a legitimate case for rank==0. I think you should be
able to set a global default requirement_rank (which would probably be 1),
but for the odd cases where you have a package that should allow unbounded
requests, you could override requirement_rank=0 specifically for that
package.

Cheers
A

**Comment by AAorris** [comment]
I've started by adding a package_filter rule that filters based on package requires.

- does not match if the requirement family is not in requires
- matches if the ranges intersect (requested x filter.required)

This allows for naive requests to be filtered with following forms of rules:

```
include:
  - requires('package-2')
```
```
exclude:
  - requires('package>reasonable_bound',warning)
```

This matches my (explicit backwards/forwards-assurance) use case:

#### An unexpected breakage has cropped up and we need to ensure that requests for it are unbaised
Given Unexpected breakage in `bombastic-0.11`

- pkg-0.4.0 already requires `bombastic-0.8+<1` (Upper bound is inappropriate)
- Release pkg-0.4.1 (updated for bombastic-0.8+<0.11)
- Release pkg-0.5.0 (updated for bombastic-0.11+<1)

```
rez-resolve bombastic pkg --exclude 'requires(bombastic>0.10,warning)'
23:01:08 WARNING filter(requires(bombastic>0.10)) pkg-0.4.0: 'bombastic-0.8+<1' overlaps bombastic>0.10
> pkg-0.4.1

rez-resolve bombastic pkg --exclude 'requires(bombastic<0.11)'
> pkg-0.5.0
```

With only `0.4.0`, both resolves would fail with a `MissingPackageError` after reducing all package versions with naive requires for `pkg-0.x+<1`.

Singular resolves and PackageFilter().iter_packages() could be used for investigations in this regard.

I don't think you could accomplish this backwards-assurance with package_rank since that would be version-specific and allow for step-down resolves for that package family if not set up before the breakage.

Will continue investigating the solver route.

**Comment by nerdvegas** [comment]
Hey Aaron,

Ah ok, I see your intention now. My suggestion of requirement_rank solves a
slightly different problem - it is a way for a package to advertise to
other packages where API breakage occurs (typically major version), and so
can produce errors if other packages use a requirement that is a superset
of that rank.

You are solving a different problem - the ability to add extra constraints
to a resolve, after a known bad release (ie one that breaks API when it
shouldn't have) occurs.

I think the package filter approach works. I certainly see the value in
doing this (as per your eg):

rez-resolve bombastic pkg --exclude 'requires(bombastic<0.11)'
> pkg-0.5.0

However, regarding the earlier example:


rez-resolve bombastic pkg --exclude
'requires(bombastic>0.10,warning)'23:01:08 WARNING
filter(requires(bombastic>0.10)) pkg-0.4.0: 'bombastic-0.8+<1'
overlaps bombastic>0.10
> pkg-0.4.1

I'm not sure we'd ever need to do this (although granted this is no
extra implementation, it's just what you can do with the
existing filters). Why wouldn't you just rez-env "pkg ~bombastic<0.11"
in this case? Why would we release a pkg-0.4.1, and
use a package filter, when we can just constrain bombastic with an
extra, normal requirement - and when we know that pkg-0.4.0
works fine with bombastic<0.11?

Cheers

A

**Comment by AAorris** [comment]
> why not just rez-env "pkg ~bombastic<0.11"

I think you're right. The only behavior a requires would provide here is additionally filtering a package that does not explicitly bound its request.
