### ISSUE TITLE
Are there any examples of how rez-suite should be used?

### ISSUE THREAD

**Issue by bpabel** [nerdvegas/rez#385]
How is this feature meant to be used?  Are there any examples of how to use it and what it does?

**Comment by nerdvegas** [comment]
Hi Brendan,

Suites in general you mean? I haven't written the docs for those yet, but
they're really easy to use.

Basically a suite is a directory on disk that contains any number of
contexts (rxt files), and a single bin subdir. In the bin dir there are
wrapper scripts for every tool from every context. From the user's POV all
they need to do is add the bin path to PATH, then they have a load of tools
that automatically run in their correct environments - the user doesn't
even need to be aware that this is happening.

Here's an example:

    rez-env maya maya_utils -o maya.rxt
    rez-env nuke nuke_utils -o nuke.rxt
    rez-suite --create mysuite
    rez-suite -a maya.rxt - c maya mysuite
    rez-suite -a nuke.rxt - c nuke mysuite

Now you have a path ./mysuite/bin containing tools 'maya' and 'nuke', and
running each one will boot the app into its correct, preresolved
environment.

Hth
A

**Comment by bpabel** [comment]
Thanks.  I don't get the maya and nuke entries in ./mysuite/bin.  Do my maya and nuke packages need to do anything special for that to work?

**Comment by nerdvegas** [comment]
Ah yes, they need to be listed in the 'tools' attribute:

# maya package.py
tools = ["maya"]

Normally this attribute has no effect (because once you're in a context you
just see whatever's on PATH); but the suites use this info to know what
wrapper scripts to create.

Hth
A

**Comment by bpabel** [comment]
Ah, I'm getting the files now.  I think I had saved the context incorrectly.  Unfortunately, I don't think windows respects the shebang to call the rez forward script.

**Comment by nerdvegas** [comment]
Ah, yeah come to think of it I don't know if anyone's attempted using
suites on Windows before.

To get it working would be a case of generating whatever analogous windows
equivalent to those shebanged wrapper scripts.

A
