### ISSUE TITLE
"alias" unexpected behaviour.

### ISSUE THREAD

**Issue by KelSolaar** [nerdvegas/rez#389]
Hi,

I was under the *naive* assumption that the `alias` definition would allow me to call the application directly on `rez-env` invokation:

```shell
>>>>>>>> C:\Users\thomas>rez-env nuke-9.0v8 -- nuke
'nuke' is not recognized as an internal or external command,
operable program or batch file.
```

if I launch a shell and then invoke `nuke` it is fine though:

```shell
>>>>>>> C:\Users\thomas>rez-env nuke-9.0v8 -- cmd
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

>>>>>>>> C:\Users\thomas>nuke
Nuke 9.0v8, 64 bit, built Oct 26 2015.
Copyright (c) 2015 The Foundry Visionmongers Ltd.  All Rights Reserved.
Disk cache C:/Users/thomas/AppData/Local/Temp/nuke\ViewerCache/??: 10065MB (99% of 10240MB) used in 1042 files.
```

This is my `package.py` file by the way:

```python
# -*- coding: utf-8 -*-

name = 'nuke'
version = '9.0v8'
authors = ['The Foundry Visionmongers Ltd.']
description = 'Powerful compositing, editorial and review.'
tools = ['nuke', 'nukex']  # Testing stuff here.
uuid = 'third-party.the-foundry-visionmongers.nuke'


def commands():
    import os
    import platform

    application_name = '{0} {1}-{2}'.format(
        'The Foundry Visionmongers Ltd.', this.name.title(), this.version)
    error_message = '"{0}" is not available on your platform!'.format(
        application_name)

    if platform.system() == 'Darwin':
        raise SystemError(error_message)
    elif platform.system() in ('Windows', 'Microsoft'):
        root_directory = 'C:\\Program Files\\{0}{1}'.format(
        this.name.title(), this.version)
    else:
        raise SystemError(error_message)

    assert os.path.exists(root_directory), (
        '"{0}" is not installed at a standard location on your system!'.format(
        application_name))

    # Setting aliases after *PATH* manipulation will break the aliases command:
    # https://github.com/nerdvegas/rez/issues/343
    alias('nuke', "Nuke9.0")
    alias('nukex', "Nuke9.0 --nukex")

    env.PATH.append(root_directory)
```

Cheers,

Thomas

**Comment by nerdvegas** [comment]
Thanks Thomas - I would expect this to work, will need to investigate.

Also, unrelated, but we're looking into a new feature that will fix issue
#343, which I see you have noted in your package.py.

Thx
A


On Thu, Feb 23, 2017 at 10:00 AM, Thomas Mansencal <notifications@github.com

**Comment by KelSolaar** [comment]
@nerdvegas: Right, glad to see that my assumptions were correct! Looking forward to the fix.

**Comment by instinct-vfx** [comment]
This seems to be a different issue but i just wanted to raise awareness, that alias breaks if called after any path manipulation including other packages. So if you have a set of packages and others are resolved before nuke and touch PATH, then PATH is emptied and standard commands do not work till after the resolve when the original PATH is re-appended.

Also, keep in mind, that "original" is not the PATH in the shell you start rez-env from, but taken from the registry on windows (which i would like to see changed).

**Comment by nerdvegas** [comment]
Hey Thorsten,

Thanks, yeah this is a separate issue and one that I'm aware of. I think
this is being worked on atm, will be checking in in the coming weeks.

Thx
A



On Fri, Feb 24, 2017 at 7:52 AM, Thorsten Kaufmann <notifications@github.com
