### ISSUE TITLE
Accessing package authors in release emails

### ISSUE THREAD

**Issue by ttanimura** [nerdvegas/rez#391]
Is there a way to append the list of package authors to the `release_hook.emailer.recipients` setting? We have a rez-release group that messages go to, but it would also be nice to avoid having everyone monitor that list, and only get notified when a package they are involved with is released. I'm looking for something like:
```

"release_hook" : {
        "emailer" : {
          "recipients" : ["{system.user}@imageworks.com", ...] + {package.authors},
        }
}
```

**Comment by nerdvegas** [comment]
So, one way you could do that now is to use a couple of new features I just
added - namely, package preprocessing and package attributes as functions:

https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#package-preprocessing
https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#package-attributes-as-functions

So you could register a global preprocess function that defines the
requirements list however you want it to be. This function has access to
the package's attributes, so you can take the authors list into account.

Having said that, it would also make sense to add an option to the new
recipients configured support to include the package authors by default.

A

**Comment by ttanimura** [comment]
Oh cool, forgot about your new pre/post-processing functions. I'll get an update installed so I can take them for a spin. Thinking about it a little further, a function would work better for us, as some people have written packages like:

`authors = ["Taisuke Tanimura (ttanimura@imageworks.com)", ...]`

So we would need some parsing of the list anyway. Thanks!

**Comment by ttanimura** [comment]
So I love the new pre/post processing functions. Having the flexibility to customise packages like this is super cool! 

I want to centralise the notion of "active" variant sets, and it seems like pre-processing is the perfect solution. For example, we want to centrally manage what versions of Maya we build for. If we define the Maya variants in each package, we would need to edit a bunch of packages each time a Maya version is deprecated or added. 

I was thinking about having users add a special attribute to packages that we would use to dynamically configure the variants. Does this sound like a sound approach, or is there something already in place that solves this problem?

**Comment by nerdvegas** [comment]
You could do it that way but I'm not sure about doing too much magic in
preprocessing. At the end of the day it's up to you though.

What might be better is to use the new
'package_definition_build_python_paths' setting, to share code at build
time. Then in your package with maya variants, you'd do something like:

    # package.py
    name = 'maya_utils'

    @early()
    def variants():
        from sony_rez.utils import get_maya_variants
        return get_maya_variants()

This feels a bit more explicit, you can tell what's going on in the
package.py. But yes it'd involve updating all affected packages.

Hth
A
