### ISSUE TITLE
rez-env : REZ_CONFIG_FILE + default_shell not taken into account..

### ISSUE THREAD

**Issue by gst** [nerdvegas/rez#395]
Hi,

seems the REZ_CONFIG_FILE for the default_shell variable isn't always respected.

For instance with the rez-env cli, it isn't respected.

`$ REZ_CONFIG_FILE=path_to_my_rez_config.py rez-env foo`

I could debug this quite deeply in the code, while I can understand the root problem, I'm not sure what's the best solution :

within rez-env `command` function (rez/cli/env.py::L119) : 

the opts obtained from the actual command line arguments is passed. This one has shell value which actually in my case is defaulted to `'tcsh'` (my default system shell is that).

But in that `command` function the rez config instance is also imported `from rez.config import config`.
In that config instance the default_shell value is well set to the one I've set in my own config file exported above (`default_shell = '/bin/bash'` ; basically).

But at the end of the function the `execute_shell()` method called on the context is passing the opts.shell, which is not what I want ..

the parser used higher level should default the shell value to the one obtained from configuration file.
And effectively : in `setup_parser` : config from rez.config is imported but was not used..

Given it's simple I'm gonna propose a small PR to fix this specific issue.

But I'm guessing the same should be done possibly for other rez-xxx commands.. at least it is fixing our situation temporarily.

**Comment by nerdvegas** [comment]
Hey thanks for the head's up Gregory, will take your fix soon.

A

**Comment by gst** [comment]
if it looks like a good fix to you (given I don't know all the code base), great :)

**Comment by brentVilla** [comment]
GST beat me to the punch with this ticket.  I actually have some code snippets that explains what gst is proposing (I think).  In rez.shells, add the follow function.

```
def get_default_shell():
    shell = config.default_shell
    if shell:
        return shell
    return system.shell
```
Then, in rez.cli.env, instead of defaulting to system.shell for the --shell argument, call and use the result of get_default_shell().
