### ISSUE TITLE
Windows installation failing with setuptools and pip not found

### ISSUE THREAD

**Issue by fxnut** [nerdvegas/rez#401]
Hi Allan,
I'd be amazed if I'm not overlooking something really simple here; in fact I'm fairly certain that it's not even anything to do with Rez itself.

Here's the error I'm getting trying to install it on Windows 7 Pro with Python 2.7.5:

```
C:\Program Files\rez-master>python .\install.py c:\rez
installing rez to c:\rez...
Traceback (most recent call last):
  File ".\install.py", line 133, in <module>
    create_environment(dest_dir)
  File "C:\Program Files\rez-master\src\build_utils\virtualenv\virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "C:\Program Files\rez-master\src\build_utils\virtualenv\virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "C:\Program Files\rez-master\src\build_utils\virtualenv\virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command c:\rez\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 2
```

As you can see, the error is occuring at the "create_environment" call in install.py. What I think is happening is that when subprocess is called from virtualenv.py, it's unable to find setuptools or pip when using the executable that it's copied into the new rez directory. I noticed that in the target installation directory; c:\rez\Lib\site-packages is empty when this errors out, which would probably explain why it isn't working, right?

I've not configured the machine I'm on so I don't know the full history. I also don't want to start re-installing stuff all over the place as I'm freelancing at the moment, and I just want to be able to demo Rez to the guys here, as I think it would be helpful for them. (First thing I'd probably do would be to update Python!).

Anyway, if you, or anyone else, happen to know what might be causing this and how to fix, then let me know. Otherwise, I'll keep digging around to see what I can find, and report back here if I resolve the issue.

Many thanks,
Andy

**Comment by fxnut** [comment]
Incidentally, in case it helps, this is what subprocess is being passed when the command is being launched:

```
cmd = ['c:\\rez\\Scripts\\python.exe', '-c', 'import sys, pip; sys.exit(pip.main(["install", "--ignore-installed"] + sys.argv[1:]))', 'setuptools', 'pip']

pythonpath = r"C:\Program Files\rez-master\src\build_utils\virtualenv\virtualenv_support\setuptools-3.6-py2.py3-none-any.whl;C:\Program Files\rez-master\src\build_utils\virtualenv\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl"

findlinks = r". C:\Program Files\rez-master\src\build_utils\virtualenv C:\Program Files\rez-master\src\build_utils\virtualenv\virtualenv_support C:\Program Files\rez-master\src\build_utils\virtualenv\virtualenv_support"
```

**Comment by fxnut** [comment]
Hmmm, well I thought that the problem was that it couldn't find setuptools and pip, but I noticed that it's passing the correct python path (see previous post). So I tried launching c:\rez\Scripts\python.exe, and then updated sys.path with the python path above, and it imports setuptools and pip without any issues.

I'll keep digging...

**Comment by fxnut** [comment]
Fixed. Don't put the downloaded rez-master underneath a directory with spaces in the name on Windows. Pip can't handle it.

**Comment by nerdvegas** [comment]
Bam! Nice detective work. Maybe we should add a check for this in the
installer..

A

**Comment by fxnut** [comment]
Heh, thanks Allan. I'll look at doing a fix when I get a sec.
