### ISSUE TITLE
rez-bind is ignoring REZ_PACKAGES_PATH?

### ISSUE THREAD

**Issue by sebastianelsner** [nerdvegas/rez#404]
I am following the "getting started" guide and working with a fresh install of rez 2.10 release on CentOS 6.6 with the REZ_PACKAGES_PATH set in my bashrc. rez-bind is ignoring it and will bind to  ~/packages. rez-env on the other hand does recognize the env var (same shell) and thus ends up with a "PackageFamilyNotFound" error. Am I missing something in the path resolution order. I tried rez a year or so ago and I remember this worked without problems.

**Comment by instinct-vfx** [comment]
rez-bind is mostly meant to get you up and running and does not necessarily behave like the rest of rez. From the help of rez-bind:

"install path, defaults to local package path"

So it is by design, though it may be debatable if the design should be changed.

To install to REZ_PACKAGES_PATH you have to use -i PATH (or -i $REZ_PACKAGES_PATH for that matter)

**Comment by nerdvegas** [comment]
Yeah rez-bind just creates the packages in ~/packages. I guess you've set
REZ_PACKAGES_PATH to not include ~/packages then?

With recent additions to rez, I'm hoping to actually deprecate the rez-bind
stuff. Package.py files are more programmatic now, and I'm able to instead
write normal packages that can detect existing system software and
integrate them with rez instead, see
https://github.com/nerdvegas/rez-recipes/tree/master/python/_detect.

But please be aware that even with this new approach, packages like this
are usually just to get you up and running - if you were to use say,
apt-get to change the python installation you have for eg, that would put
your rez package created from the example link out of sync (the rez package
python-2.7.4 might now refer to system python-2.7.12, and may be broken).

There may be legitimate cases for long term use of 'detected' packages
though - for example, perhaps you don't want to build gcc from source, and
instead you're happy to use the gcc on your system and you aren't going to
change it.. in which case using a rez gcc package which is based off
detecting the system gcc installation would be acceptable. It's up to you.

Hth
A





On Fri, Mar 24, 2017 at 8:12 AM, Thorsten Kaufmann <notifications@github.com

**Comment by sebastianelsner** [comment]
Thank you for the explanation!
