### ISSUE TITLE
Infinite solve if variants can not be solved

### ISSUE THREAD

**Issue by bfloch** [nerdvegas/rez#422]
Tested with rez 2.13.0. Attached minimal setup with README.
This seems to be the minimal setup:

**Package 1 "python_provider":**

variants = [
  ['maya', '!houdini', '!nuke']
]

**Package 2 "pyqt":**

varriants = [
  ['houdini-15'],
  ['nuke-8'],
]

**Package 3 "maya":**

Regular.

Solve:
rez-env python_provider pyqt maya -vv

Give us a python_provider (maya, but not houdini and not nuke), maya and pyqt
(which does not have a variant that would not break the python_provider variant requirement).

Instead of failing the solver solves forever.

[rez_solver_bug.zip](https://github.com/nerdvegas/rez/files/994202/rez_solver_bug.zip)

**Comment by nerdvegas** [comment]
Fantastic, thanks Blazej
A

**Comment by bfloch** [comment]
Briefly looking into it.

The problem seems to be in the split. At least both failed conditions are being catched (!nuke & !houdini).

First it does split (reason: first variant) [pyqt==4.11.4.tbe1[0,1]] into [pyqt==4.11.4.tbe1[0]]* and pyqt[==4.11.4.tbe1(2:3)]

It fails solving [pyqt==4.11.4.tbe1[0]]

Then it pops pyqt[==4.11.4.tbe1(2:3)] and splits it again into
[pyqt==4.11.4.tbe1[1]]* and [pyqt==4.11.4.tbe1[0,1]]

Then it splits [pyqt==4.11.4.tbe1[0,1]] into [pyqt==4.11.4.tbe1[0]]* and pyqt[==4.11.4.tbe1(2:3)]

And so on ... I do not really know about the syntax. What does package[==version(2:3)] mean compared to [package==vesion[0,1]]? Why wouldn't it split [0,1] into [0] and [1]?

**Comment by bfloch** [comment]
This might be the solve. I am not making this a pull request before you have your eyes on it.
Basically in the case of two entries we only need to split into [0] and [1]. We do not need to add the rest of the variants.

rez/solver.py at line 833
~~~python
            if result:
                entry, next_entry = result
                entries = self.entries[:i_entry] + [entry]
                if len(self.entries) > 2:
                    next_entries = [next_entry] + self.entries[i_entry:]
                else:
                    next_entries = [next_entry]
            else:
                entries = self.entries[:i_entry + 1]
                next_entries = self.entries[i_entry + 1:]
~~~

**Comment by bfloch** [comment]
I looked around further. I wonder if my fix is not a bug itself in case the n_variants is not 1 for len(2) entries. Probably this is not generic enough. Will rethink it on Monday, I should write a few unit tests to make sure I am not introducing any side effects.
Feel free to propose a better fix, I still have to get to know the surrounding code.

**Comment by bfloch** [comment]
The pull request should be the proper fix to my best knowledge.
Allan, please take a good look if I figured the intention of the code correctly. If you can think of cases where this might break (expected or existing) behavior let me know.

**Comment by bfloch** [comment]
There is another pull request for the same bug:
#448

**Comment by nerdvegas** [comment]
I believe this has been fixed.
