### ISSUE TITLE
"package_definition_build_python_paths" defined paths are not available from top level in "package.py"

### ISSUE THREAD

**Issue by KelSolaar** [nerdvegas/rez#433]
As described in https://github.com/nerdvegas/rez/issues/426#issuecomment-305348630, adding a path to `package_definition_build_python_paths` in the config file does not expose it to `package.py` top level, i.e. it is not added to `sys.path` and you cannot import any module under the added path.

**Comment by nerdvegas** [comment]
https://github.com/nerdvegas/rez/releases/tag/2.25.0
