### ISSUE TITLE
Per Variant Release

### ISSUE THREAD

**Issue by mstreatfield** [nerdvegas/rez#44]
Currently `rez release` releases all variants in a single pass, which is generally a good thing.

However, we are finding that in some cases we have to go back and release an additional variant to an existing package (for example, an additional boost variant).  We are unable to do this with the current implementation of rez-release.

One solution would be to increment the sub-patch version number (so `1.0.0` would become `1.0.0.1`) however this means releasing all variants again.  For some tools this takes many hours.  However for external packages (which we are currently releasing using the `ExternalProjects` macro in CMake we want the version number to match the external number.

Another solution would be to add a `-v` argument to `rez release` which behaves in a similar way to `rez build`.  This creates problems with tagging and if misused could result in a package being partially released.  That said this might become more necessary if we consider distributing variant builds across a CI system such as Jenkins.

Has anyone else encountered this problem?  Does anyone have any suggestions?

**Comment by nerdvegas** [comment]
Closing - resources2 branch allows for installing variants into existing packages.

**Comment by n0phx** [comment]
> Closing - resources2 branch allows for installing variants into existing packages.

how is this achieved though? I am trying to figure out how to integrate rez release into a Jenkins pipeline, where I'd like to trigger a rez release for each build configuration separately, thus my variants list would list only a single variant I guess for each build configuration, and trigger rez release
