### ISSUE TITLE
${EnvironmentVariable} expansion in windows does not work

### ISSUE THREAD

**Issue by bfloch** [nerdvegas/rez#443]
To quote the wiki:

> Environment variable expansion is also supported when passed to rex functions. The syntaxes $FOO and ${FOO} are supported, regardless of the syntax supported by the target shell.

However in my testing the environment variables do not get expanded on windows in CMD.

Only the "Python" interpreter does `expand_env_vars = True`, while in bash the system takes over and does the expanion.

Since on windows ${} is not supported I suggest that `expand_env_vars` should be set `True` in the CMD shell.

Is there a risk doing this?

**Comment by skral** [comment]
@bfloch Can you provide reproducible steps to what you tried, please? I am trying to understand where you're running into this issue.

**Comment by bfloch** [comment]
I will have to try again and see if this still applies. 
But I do not have access to that environment till April.

**Comment by bfloch** [comment]
Closing in favor of the new issue.
