### ISSUE TITLE
zsh plugin for rez

### ISSUE THREAD

**Issue by suryakiran** [nerdvegas/rez#451]
I'm using Rez version 2.13.1 on Ubuntu 16.10. The zsh plugin for rez is non-existent. Any plans on introducing it in future releases ? If not, I'd like to know what is the way to write a new shell plugin.

Thanks,
Surya

**Comment by instinct-vfx** [comment]
I don't know if anyone has a zsh plugin or wants to work on one. But to create a new shell plugin you'd probably start by inheriting the UnixShell class ( found in https://github.com/nerdvegas/rez/blob/master/src/rez/shells.py) and implement all the methods.

You can look at the other shells to get a better idea of what each of the methods do.

Cheers,
Thorsten
