### ISSUE TITLE
Remove sh dependency

### ISSUE THREAD

**Issue by instinct-vfx** [nerdvegas/rez#459]
As discussed on the mailing list already we want to remove the .sh dependency. It is not supported on Windows and just a fancy wrapper to replace subprocess and the likes essentially and it seems the only place it is still used is the git vcs plugin anyways.
And even in the git vcsplugin it is only used in a single classmethod.

**Comment by instinct-vfx** [comment]
So i started working on that but i am unsure how to continue. So as outlined there is only the class method that is using it.

First of all, the classmethod is defunct anyways because it uses retain_cwd which is never imported in the module.

In addition this classmethod is only used in a single method in the project. Namely "diff_packages" in rez.utils.diff_packages.

I don't really understand how this should be used and it does not work at all for me at all anyways.

Can anyone shed some light if this actually works for anyone and if it is actually used?

**Comment by nerdvegas** [comment]
It mustn't be used - as you point out retain_cwd isn't imported so this
would fail anyway.

Rez-diff is just a convenience tool to diff the contents of two packages.
Don't know if anyone is using it (probably not becaues they'd've hit that
bug).

I think it'd be acceptable to leave the export function as-is right now, we
can deal with it later.

A

**Comment by instinct-vfx** [comment]
I changed the plugin as discussed, see PR.

**Comment by nerdvegas** [comment]
Addressed by https://github.com/nerdvegas/rez/pull/377
