### ISSUE TITLE
Rez's unique selling proposition

### ISSUE THREAD

**Issue by Schizo** [nerdvegas/rez#465]
I was eager to see in the readme how Rez is different than other package managers that lead to the motivation to write this package. Can someone point out kindly what the biggest flaws of the other products are?

**Comment by instinct-vfx** [comment]
I think the introduction of the docs outlines the difference quite well: https://github.com/nerdvegas/rez/wiki

"
Rez is a cross-platform package manager with a difference. Using Rez you can create standalone environments configured for a given set of packages. However, unlike many other package managers, packages are not installed into these standalone environments. Instead, all package versions are installed into a central repository, and standalone environments reference these existing packages. This means that configured environments are lightweight, and very fast to create, often taking just a few seconds to configure despite containing hundreds of packages
"

**Comment by Schizo** [comment]
I read the whole readme, but when it's said **"Unlike many other package managers"**, there are at least 100 on pypi only. So which ones are you referring to?

**Comment by instinct-vfx** [comment]
I am not sure what you are expecting to be honest? (Personally i am not referring to any specific package manager, i just quoted a (what i thought) relevant part of the docs.

**Comment by KelSolaar** [comment]
Rez is VFX oriented, I have tried quite a few, e.g. cpenv, ecosystem, etc... and Rez is what came closest of what you find in big VFX studios.

**Comment by nerdvegas** [comment]
That's a good summary imo.

A
