### ISSUE TITLE
rez-build doesn't write private_build_requires to installed package

### ISSUE THREAD

**Issue by brentVilla** [nerdvegas/rez#477]
_rez-depends_ now has the ability to query dependencies in _private_build_requires_.  However, _rez-build_ does not write that section to the output package's package.py file.  Please include _private_build_requires_ in the output package.py file.

**Comment by bfloch** [comment]
For reference it was introduced here: #444
Should be an easy fix.

**Comment by nerdvegas** [comment]
https://github.com/nerdvegas/rez/releases/tag/2.24.0
