### ISSUE TITLE
Support for keyword arguments in `rez-python`

### ISSUE THREAD

**Issue by swallitsch** [nerdvegas/rez#492]
Looking at how rez-python is implemented, this looks like a difficult request, but I'll ask it anyway.

Right now `rez-python` only supports positional arguments- no flags or kwargs.

So, `rez-python ./scriptname /path/to/file/1 /path/to/file2` works, but `rez-python ./scriptname -i --sequence baz --shot 100` will not, because rez tries to eat the flags and kwargs, then errors out when it doesn't understand them.

I feel like it'd be a neat addition, because it would allow people to place `#!/usr/bin/env rez-python` as a script shebang line, and have it behave exactly as if you called the script with `rez-env rez -c "{sys.argv}"`, which is how I initially expected rez-python to behave.

**Comment by bpabel** [comment]
I think it would be possible to update the command to handle that without breaking backwards compatibility.  Right now, it's ignoring arguments from the other argument groups (seperated by `--`-), but really, those should just be passed to `python` unprocessed.

    rez-python [REZ ARGS] -- /path/to/script.py arg1 arg2 --keywords -f --debug

**Comment by nerdvegas** [comment]
Yeah this has been on my backlog for some time.. I don't see a problem
passing the non-rez args directly to rez-python.

**Comment by swallitsch** [comment]
I was actually hoping for `rez-python` to not even take default rez arguments- for it to pass given arguments and flags straight to the script it's calling- that way I can place it in shebang lines.

I can write my own script for that though. My use cases might not match up with the normal use case for rez-python.

**Comment by nerdvegas** [comment]
Addressed by https://github.com/nerdvegas/rez/pull/523
