### ISSUE TITLE
rez-release does not copy @include() scripts to packages dir

### ISSUE THREAD

**Issue by willjp** [nerdvegas/rez#510]
Hey Guys

When I rez-release a package that uses the `@include` decorator, the included
script does not get copied to the release packages directory.

<br>
<br>

I have noticed that when I use `rez-build -i` a subdirectory `.rez/include` is 
created with the created package, and that script is read when `rez-env` is run.

This directory does not get created in released packages. When I try to run a
rez-env from a released package, even if the included script is on the 
`package_definition_python_path` , the rez-env fails because it cannot find the
included script.

I am not certain if this is an issue with rez-release, or an issue with my workflow
( and I apologize if this is the latter ). Either way, I was wondering if anyone
had any tips for working with `@include` in conjunction with `rez-release` . Thank you 
so much again,

Will

**Comment by willjp** [comment]
I've been able to fix this, by modifying my rez-install's code. This is my understanding:

``` python
# ============
# rez-build -i
# ============

rezplugins.build_process.local.LocalBuildProcess().build()
    # calls    `self.visit_variants( self._build_ariant, ...)` to perform build
    # if install   `self._install_include_modules(install_path)`

# ===========
# rez-release
# ===========

rezplugins.build_process.local.LocalBuildProcess().release()
    # calls   `self.visit_variants( self._release_variant )`  for each variant
        # calls   `self._build_system.build()` to build each variant
        # nothing calls `self._install_include_modules(install_path)`
```

Adding `self._install_include_modules(install_path)` to `rezplugins.build_process.local.LocalBuildProcess()._release_variant()` under it's `if install:` fixes this issue for me.

I can make a pull request if that is helpful.

- Will

**Comment by nerdvegas** [comment]
Hi Will,

Yes thank you! It's entirely possible this never got tested on a release,
and was just tested on `build -i`, since so much of the code is common.

Thanks,
A

**Comment by willjp** [comment]
No problem! Thanks for writing all of this, and thanks for sharing :)

**Comment by nerdvegas** [comment]
https://github.com/nerdvegas/rez/releases/tag/2.24.0
