### ISSUE TITLE
windows: rez-env --stdin

### ISSUE THREAD

**Issue by willjp** [nerdvegas/rez#512]
Hey guys,

I just noticed that `rez-env --stdin` does not work on windows, since `sys.stdin` can't be used within `select.select` on windows. This looks not fun to fix: https://stackoverflow.com/questions/12499523/using-sys-stdin-in-select-select-on-windows

```
echo "python" | rez-env "python" --stdin

select.error (10038, 'An operation was attempted on something that is not a socket')
```

**Comment by nerdvegas** [comment]
We could probably just drop the `select.select` on windows and just read
from stdin normally. The select just tells us if there's anything buffered
in stdin, so worst case without this is just that you get a prompt for
input if there wasn't anything in stdin.

Hth
A

**Comment by willjp** [comment]
That's awesome, thank you! goodbye ackward cmd.exe escape strings!!

**Comment by nerdvegas** [comment]
https://github.com/nerdvegas/rez/releases/tag/2.22.1
