### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by adriankrupa** [nerdvegas/rez#515]
Hey @nerdvegas,

What's the status of this project? There was no commit or accepted PR for over 5 months. I can see that you actively reply on some issues and google group. Do you have any big picture for the future?

Thanks,
Adrian

**Comment by nerdvegas** [comment]
I've been busy on something else but should have a few months' development
time coming up, in the next month or two.

Thx
A

**Comment by purestvfx** [comment]
cool,

I did notice the absence of code changes/merges.  was a little worried it was getting abandoned.

What can be done to help?
