### ISSUE TITLE
provide ability to track package usage

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#528]
AMQP hook, trigger whenever context is created / used

**Comment by instinct-vfx** [comment]
Are there also plans for a bigger initiative to add AMQP events for more events? In an ideal world AMQP events would be fired for pretty much any notable event.

**Comment by instinct-vfx** [comment]
With this released i gave it a quick go and it looks to be working nicely for now. I would really love to see this to be extended a) to be a generalized mechanism that allows to fire events for all kinds of events from the core and b) potentially be developed towards being plugin based with amqp being the default (for now i don't have an actual requirement, but i may have in the future).

**Comment by nerdvegas** [comment]
I had the same thoughts. To that end, note that there's a new utils/amqp.py
file, which both the new context tracking, and the existing release hook
plugin, both use. Adding new events will be easy if there are requests for
them.

Re plugin-based event mechanism (ie add HTTP endpoint rather than amqp, for
eg) makes sense also, but I didn't want to build this out ahead of time. I
suspect that extending support to both AMQP and HTTP will probably suffice.
With this in mind though perhaps there should have been a
`context_tracking_connection` setting instead, where `mode` field would
select amqp/http/other.

Cheers
A



On Wed, Oct 10, 2018 at 1:52 AM, Thorsten Kaufmann <notifications@github.com

**Comment by nerdvegas** [comment]
Fixed by https://github.com/nerdvegas/rez/pull/531
