### ISSUE TITLE
rez-env with PYTHONHOME set.

### ISSUE THREAD

**Issue by ISkipy** [nerdvegas/rez#585]
Hey guys,

I just came across a "bug?" i never experienced before:
It seems that a package can't set a PYTHONPATH if PYTHONHOME is set.
error message: `ImportError: No module named site`

How to reproduce it on Centos 7.5:
`export PYTHONHOME="/usr/lib64"`
`rez-env myPackage -- python`
Where you package have to set PYTHONPATH
i.e: `env.PYTHONPATH.append("{root}/rez_myTool")`

Same commands without setting PYTHONHOME work.
Same commands with a package who is not setting PYTHONPATH work.

Cheers,
Clement

**Comment by bpabel** [comment]
The problem is probably that `PYTHONHOME` doesn't contain a `site.py` file, which python expects to be in the `PYTHONHOME` directory, as it is automatically imported on python startup.

I would expect you to get the exact same error if you just ran python without the rez command

```
$ export PYTHONHOME="/usr/lib64"
$ python
```

**Comment by ISkipy** [comment]
That is true.
So it is not an issue related to rez then, sorry for that.

`export PYTHONHOME="/usr"` fixes the issue.
Even though `site.py` is inside `/usr/lib64/python2.7`
Probably some dependencies..

Thanks for the help!
