### ISSUE TITLE
rez pip --install Qt.py doesn't convert dot to underscore

### ISSUE THREAD

**Issue by mottosso** [nerdvegas/rez#611]
Resulting pip install contains a dot, which makes it inaccessible to Rez.

- Dashes become underscore, but dots do not
- Confirmed on Linux and Windows

```bash
$ cd ~/packages
$ rez pip --install pyblish-base
$ rez pip --install Qt.py
...
$ ls
pyblish_base Qt.py
```

**Comment by instinct-vfx** [comment]
Gotta check tomorrow, but that works fine for me. What is the issue?

**Comment by mottosso** [comment]
Sorry! You're right, I didn't test this thoroughly enough.

This works fine.

```bash
$ rez env Qt.py>=1.0
```
