### ISSUE TITLE
Dedicated environ variable for package.py

### ISSUE THREAD

**Issue by mottosso** [nerdvegas/rez#613]
### Goal

Enhance readability of package.py

### Motivation

The declarative nature of `package.py` works really well I think, akin to any configuration file format out there.

```python
name = "foo"
version = "1.1"
requires = ["a", "b", "c"]
```

Environments however are currently specified in the `commands()` function, which stands out.

```python
name = "foo"
version = "1.1"
requires = ["a", "b", "c"]

def commands():
  env["PYTHONPATH"].append("{root}/python")
  env["MAYA_VIEWPORT_1"] = "${GLOBAL_MAYA_VIEWPORT_1}"
```

### Proposal

Specify the environment declaratively too.

```python
name = "foo"
version = "1.1"
requires = ["a", "b", "c"]
environ = {
  "PYTHONPATH": ["{root}/python"],
  "MAYA_VIEWPORT_1": "${GLOBAL_MAYA_VIEWPORT_1}",
}
```

Whereby members of `environ` implicitly expands variables, as I think anyone would expect, taking into account both path-like and plain variables.

Would also propose using a different name from `env` to avoid confusion; they aren't actually the same, as you've got a `os.environ`, `env` and now `this.environ` which contain three separate environments altogether. Wasn't sure about whether we should choose `environ` or `environment`, the latter fitting better with surrounding non-shortened versions, but former more akin to `os.environ` and perhaps more familiar. I found the symmetry between `os.environ` and `this.environ` quite appealing, one addressing the OS and the other the current package.

Here's how it could work under-the-hood.

```python
def commands():
    for key, value in this.environ.items():
        if isinstance(value, (tuple, list)):
            [env[key].append(expandvars(v)) for v in value]
        else:
            env[key] = expandvars(value)
```

I've been doing this on all of my packages so far, and haven't found any technical, visual or practical issue with it, and figured it may as well be part of Rez.

For advanced use, e.g. explicitly prepending or appending a PATH-like variable, one could combine the two methods.

Thoughts?

**Comment by JeanChristopheMorinRodeoFX** [comment]
Hey @mottosso, I'm not sure to understand what it would bring from what we already have. Could you elaborate more on what this would try to solve or answer?

Thanks!

**Comment by mottosso** [comment]
Hey @JeanChristopheMorinPerso, the change is purely cosmetic.

The motivation is that many of my packages do nothing but edit the environment in the `commands()` function, resulting in what you see at the left below. I don't know about you, but to me, having environment variables declarative - like `name` and `requires` - is expected and reads better. Leaving `commands()` to what *happens* during a resolve/build, and everything else to what *is*.

<table>
<tr>
<th>Before</th><th>After</th>
</tr>
<td>

```python
name = "maya_base"
version = "1.0.8"
requires = [
    "core_pipeline-2",
]

build_command = "python -m rezutils {root}"
private_build_requires = ["rezutils-1"]

environ = {

    # General environment applicable to
    # every version of Maya.
    "MAYA_DISABLE_CIP": "1",
    "MAYA_DISABLE_CER": "1",
    "MAYA_DISABLE_CLIC_IPM": "1",

    "MAYA_ENABLE_LEGACY_VIEWPORT": "1",
    "MAYA_VP2_DEVICE_OVERRIDE": "VirtualDeviceDx11",

    "MAYA_DISABLE_CLIC_IPM": "1",
    "MAYA_FORCE_PANEL_FOCUS": "0",
    "MAYA_DEBUG_SIGTERM_AS_SIGINT": "1",
    "MAYA_COLOR_MANAGEMENT_POLICY_LOCK": "1",
    "MAYA_RENDER_SETUP_INCLUDE_ALL_LIGHTS": "0",

    # General scripts and shelves
    "MAYA_COLOR_MANAGEMENT_POLICY_FILE": [
        "{root}/maya/color_management"
        "/default_synColorConfig.xml"
    ],

    "PYTHONPATH": [
        "{root}/maya/scripts",
        "{root}/maya/shelves",
    ],

    "MAYA_PLUG_IN_PATH": [
        "{root}/maya/plugins"
    ],

    "MAYA_SCRIPT_PATH": [
        "{root}/maya/scripts",
    ],

    "MAYA_SHELF_PATH": "{root}/maya/shelves",

    "XBMLANGPATH": [
        "{root}/maya/shelves/icons"
    ],
}


def commands():
    global env
    global this
    global system
    global expandvars

    environ = this.environ

    for key, value in environ.items():
        if isinstance(value, (tuple, list)):
            [env[key].append(expandvars(v)) for v in value]
        else:
            env[key] = expandvars(value)
```
</td>
<td valign="top">

```python
name = "maya_base"
version = "1.0.8"
requires = [
    "core_pipeline-2",
]

build_command = "python -m rezutils {root}"
private_build_requires = ["rezutils-1"]

environ = {

    # General environment applicable to
    # every version of Maya.
    "MAYA_DISABLE_CIP": "1",
    "MAYA_DISABLE_CER": "1",
    "MAYA_DISABLE_CLIC_IPM": "1",

    "MAYA_ENABLE_LEGACY_VIEWPORT": "1",
    "MAYA_VP2_DEVICE_OVERRIDE": "VirtualDeviceDx11",

    "MAYA_DISABLE_CLIC_IPM": "1",
    "MAYA_FORCE_PANEL_FOCUS": "0",
    "MAYA_DEBUG_SIGTERM_AS_SIGINT": "1",
    "MAYA_COLOR_MANAGEMENT_POLICY_LOCK": "1",
    "MAYA_RENDER_SETUP_INCLUDE_ALL_LIGHTS": "0",

    # General scripts and shelves
    "MAYA_COLOR_MANAGEMENT_POLICY_FILE": [
        "{root}/maya/color_management"
        "/default_synColorConfig.xml"
    ],

    "PYTHONPATH": [
        "{root}/maya/scripts",
        "{root}/maya/shelves",
    ],

    "MAYA_PLUG_IN_PATH": [
        "{root}/maya/plugins"
    ],

    "MAYA_SCRIPT_PATH": [
        "{root}/maya/scripts",
    ],

    "MAYA_SHELF_PATH": "{root}/maya/shelves",

    "XBMLANGPATH": [
        "{root}/maya/shelves/icons"
    ],
}
```
</td>
</tr>
</table>

On seeing this for the first time, you'll know that because it doesn't have `commands()` block no logic is involved in the package, no aliases and no Python imports etc.

It should be noted however that it may cause backwards incompatibility for anyone using their own variable called `environ` at the moment.

**Comment by instinct-vfx** [comment]
I am also not really sure about the benefit tbh. Why are you putting it into an attribute to iterate over in the first place? What is the benefit over just setting the variables in commands()? 

One issue i would see with some of our packages is that we set environment variables at different times. So for example our max plugin packages announce their plugin paths to the max package through an environment variable. They do so in their pre_commands and the max package picks them up in its commands section.

Also a lot of our variables aren't purely declarative but contain logic to be created. So that would create a weird mix of parts of the env being in commands and parts being in an attribute.

**Comment by JeanChristopheMorinRodeoFX** [comment]
Thanks for the details @mottosso. I'm personally not sure it's the way to go. The main purpose of the `commands` is to set up the environment. All other attributes will never affect your environment and are only there to describe your package. See https://github.com/nerdvegas/rez/wiki/Package-Commands#overview. Having an attribute to do what the `commands` function is mainly made for would defeat the purpose of the `commands` function IMO.

But maybe others will disagree with me.

> Whereby members of environ implicitly expands variables, as I think anyone would expect, taking into account both path-like and plain variables.

If you use the `env.append` (or prepend) the variable expansion will be done automatically. Don't need to use `expandvars` in your specific case that you showed us. The same applies for `alias` and other functions/variables accessible from the `pre_commands`, `post_commands` and `commands` function (actually any rez function available in the commands functions. See https://github.com/nerdvegas/rez/wiki/Package-Commands#explicit-string-expansion.

PS: I agree with what @instinct-vfx said too.

**Comment by mottosso** [comment]
Ah, I'm surprised.

Let's turn things around for a second; why do you think they should be declared in `commands()`? I would expect to see actions being performed in a function, and for data to be declared in variables. Like `name` and `version`. Why not put `name` and `version` in `commands()` as well?

**Comment by mottosso** [comment]
> Why are you putting it into an attribute to iterate over in the first place?

Haha, yes perhaps not the most obvious example, I was in a rush.

I've updated the example to better illustrate where splitting up data from logic can help with comprehension; especially for someone reading this for the first time.

**Comment by instinct-vfx** [comment]
To me there is a very clear distinction between name/version etc. and commands - and splitting env variables that way goes against the split in my head (which does not mean i am necessarily right heh).

Attributes like name, version, authors etc. are properties of the **_package_** itself, whereas everything in pre_commands, commands and post_commands are commands that need to be executed to create the **_environment_** for the package. I always looked at everything in commands as - well - commands that need to be executed. Hence i also tend to use the env.VAR.set() or env.VAR.append() notation.

**Comment by mottosso** [comment]
One more usecase for this.

```python
from rez.resolved_context import ResolvedContext
context = ResolvedContext(["myPackage"])
context.get_environ()
```

This currently calls on the `commands()` function, which I wouldn't expect.

Especially if the `commands()` function does more than just set environment variables, like print a welcome message, establish aliases etc. Instead, I would expect the "raw" or unprocessed environment variables, and for the "final" environment to come from e.g. `context.compute_environ()`

**Comment by mottosso** [comment]
Having used this for the past few weeks, I just had a challenging debugging session that one could say was due to this way of authoring environment variables.

Can you spot it?

**a/package.py**

```python
name = "a"
version = "1.0.0"
environ = {"PYTHONPATH": ["{root}/python"]}
```

**b/package.py**

```python
name = "b"
version = "1.0.0"
environ = {"PYTHONPATH": ["{root}/python"]}
```

**c/package.py**

```python
name = "c"
version = "1.0.0"
environ = {"PYTHONPATH": "{root}/python"}
```

That's exactly it. It's a hard one to spot, especially when:

1. You've got a lot more packages
2. They aren't laid out in a single block of text like this

If you haven't spotted it yet, the issue is that whilst a and b appends to the PYTHONPATH, c overwrites it.

Without this feature, it would have looked like:

```python
name = "a"
version = "1.0.0"

def commands():
  env.PYTHONPATH.append("{root}/python")
```

```python
name = "c"
version = "1.0.0"

def commands():
  env.PYTHONPATH = "{root}/python"
```

Which although doesn't eliminate the possibility, doesn't lend itself to missing out on just two characters.

Has anyone struggled with this before? I wonder if it would be a good idea to warn or prevent writing to a variable that's had `.append` or `.prepend` used with it before, or likewise prevent a variable from being used with `.prepend` if it had previously been assigned with `=`?

**Comment by maxnbk** [comment]
> Let's turn things around for a second; why do you think they should be declared in `commands()`? I would expect to see actions being performed in a function, and for data to be declared in variables. Like `name` and `version`. Why not put `name` and `version` in `commands()` as well?                           

Because for environment setups, order matters intimately.
                                                                                                                         
If I'm specifying multiple ops to a single environment variable (and I do so plenty), it's not clear how a dict-based setup would execute them, because order is not going to be deterministic. Unless you want to set it up as a list of small dicts, wherein the list is managing the order, but that's getting into it's own layer of confusing.

I can see no situation where the declarative approach helps you get something done that the function-style helped you get done, and no situation where the function-style does something more confusingly if you are only going to list things out as if you were doing so declaratively, while also providing a superset of the same functionality.

But if you must do so that way, nothing stops you from simply declaratively handling those variables inside a commands section and then iterating over it yourself in whatever manner you find appropriate, I'd think, and then it's whatever you want to make of it.

**Comment by nerdvegas** [comment]
On Thu, May 23, 2019 at 8:44 PM Marcus Ottosson <notifications@github.com>
wrote:

> One more usecase for this.
>
> from rez.resolved_context import ResolvedContext
> context = ResolvedContext(["myPackage"])
> context.get_environ()
>
> This currently calls on the commands() function, which I wouldn't expect.
>

Why wouldn't you expect that? The docs explain in detail what happens when
a context is used. The commands are _always_ used to configure the target
environment.


> Especially if the commands() function does more than just set environment
> variables, like print a welcome message, establish aliases etc. Instead, I
> would expect the "raw" or unprocessed environment variables, and for the
> "final" environment to come from e.g. context.compute_environ()
>
The get_environ docstring actually doesn't make this clear enough, but any
actions in the command that don't affect the environ, are skipped (eg
welcome messages). See
https://github.com/nerdvegas/rez/blob/master/src/rez/rex.py#L550

I agree with others that this feature doesn't bring anything to the table
that you can't already do. Furthermore it introduces ambiguity - it isn't
obvious what order the env vars will be set in. In fact it takes control
away - at the moment (for eg) a package can set an env-var earlier than
other packages, by doing so in its pre_commands instead. This has real
world consequences and is actively used. The examples given also don't
appear to define whether a path-like env-var is appended to, or prepended
to.

Right now everything outside of the commands are declarative (they define
the properties of the package), and everything in commands is always used
to configure the target environment, and I don't see good reason to change
that.

If convenience for this case is what is desired, then what would be
acceptable is some new `env` method, like so:

# in package.py
vars = {
  "FOO": "bah",
  "THINGS": ["a", "b"]
}

def commands():
    env.apply_map(this.vars, path_mode="append")


A

**Comment by nerdvegas** [comment]
We used to have a feature in rez-1 where, if two packages set the same
env-var, a warning was produced. This was lost in rez-2 however.

What would be useful is a generalisation of this. It would be good to be
able to track what has happened to any given env-var, and then to be able
to configure warnings/errors etc if desired.

Fog eg (and this is completely off the top of my head):

> ]$ rez-context --inspect-var PYTHONPATH
1. foo-1.2.3 appended PYTHONPATH
2. bah-3.4 appended PYTHONPATH
3. eek-1 set PYTHONPATH. Note that this has overwritten [1, 2]

Then in rezconfig you might:

env_var_inspect_mode:
  - var: PYTHONPATH
    on_overwrite: error

Globbing would be supported also, and order of rules would matter (stop on
first):

env_var_inspect_mode:
  - var: PYTHONPATH
    on_overwrite: error
  - var: *
    on_overwrite: warning

A

**Comment by mottosso** [comment]
Hi guys, thanks for chiming in.

> Why wouldn't you expect that?

In my case, `commands()` does more than just setting environment variables, like printing to the terminal, setting aliases and sometimes writing executables (for e.g. when `cmd` is unable to provide aliases via `--`).
