### ISSUE TITLE
Shell history not working in cmd.exe or PowerShell

### ISSUE THREAD

**Issue by mottosso** [nerdvegas/rez#616]
Confirmed by @instinct-vfx on [Slack](https://rez-talk.slack.com/archives/CHELFCTFB/p1556261890473900) and this old [Google Groups thread](https://groups.google.com/forum/#!searchin/rez-config/history%7Csort:date/rez-config/erxLThK7Yrk/amhtxvCVAAAJ), using cmd.exe or PowerShell with Rez doesn't let you step through history via the traditional up-arrow key.

**To reproduce**

```bash
$ rez env
> $ echo Hello World!
> $ # hit up-arrow
> $ # no response.. :(
```

It does however (for some reason) work when using Rez with ConEmu, Cmder and Alacritty (and probably others too); each of which call on the same `rez_shell.bat` file. Odd!

**Comment by nerdvegas** [comment]
Closed by https://github.com/nerdvegas/rez/releases/tag/2.35.0
