### ISSUE TITLE
welcome() banner

### ISSUE THREAD

**Issue by mottosso** [nerdvegas/rez#620]
Feature proposal.

### Goal

Enable a developer to communicate with the end-user, and facilitate a Getting Started-style tutorial.

### Motivation

To a new user, or anyone being a consumer rather than a producer of Rez packages, entering into an environment can get a little overwhelming.

```bash
$ rez env alita maya
resolved by me@none.ya.beeswax, on Sat Apr 27 09:46:16 2019, using Rez v2.29.1

requested packages:
alita
maya
~platform==windows       (implicit)
~arch==AMD64             (implicit)
~os==windows-10.0.17763  (implicit)

resolved packages:
alita-0.3.17        C:\Users\me\.rez\packages\alita\0.3.17  (local)
base-1.2.1          C:\Users\me\.rez\packages\base\1.2.1    (local)
ftrack-1.0.0        C:\Users\me\.rez\packages\ftrack\1.0.0  (local)
gitlab-1.2.0        C:\Users\me\packages\gitlab\1.2.0
maya-2018.0.1       C:\Users\me\packages\maya\2018.0.1
maya_base-1.0.8     C:\Users\me\packages\maya_base\1.0.8
mgear-2.4.1         C:\Users\me\.rez\packages\mgear\2.4.1   (local)
pyblish_base-1.7.2  C:\Users\me\packages\pyblish_base\1.7.2\
pyblish_lite-0.8.4  C:\Users\me\packages\pyblish_lite\0.8.4\
python-2.7          C:\Users\me\packages\python\2.7
> (rez) $
```

### Proposal

Provide a custom message to the end-user via `welcome()`

**package.py**

```python
name = "intro"
version = "1.0.0"
build_command = False

_message = """\
--------------------------

Welcome to {env.PROJECT_NAME}, type `help` for more information.

-------------------------
"""

_help = """\
-----------------------------------------------------
A longer message, perhaps with details about
what's available to the user.

Commands:
  help: Print this message
  exit: Leave this environment

-----------------------------------------------------
"""

def commands():
  alias("help", "echo {this._help}")
  alias("hello", "echo world!")
  welcome(this._message)
```

How would it work?

1. During resolve, if no `welcome()` is found, print standard welcome screen.
2. Else, print only the contents of the last encountered `welcome()`

That way, one can override the welcome and could potentially build upon (inherit) it like so.

```python
welcome(this.welcome + "\nOh, and don't forget to say `hello`!")
```

Resulting in..

```bash
$ rez env alita maya
--------------------------

Welcome to Alita, type `help` for more information.

-------------------------
> $ help
-----------------------------------------------------
A longer message, perhaps with details about
what's available to the user.

Commands:
  help: Print this message
  exit: Leave this environment

-----------------------------------------------------
> $ hello
World!
> $ exit
$
```

This would then also help when constructing a tutorial for the new user, as one could replace unnecessary information with a helpful message about what to do once having entered an environment.

**Comment by bpabel** [comment]
I like this idea.

This feels more like it should be a config setting (packages can make config overrides within a resolve).  That way you can set a global welcome message too.

**Comment by mottosso** [comment]
> This feels more like it should be a config setting (packages can make config overrides within a resolve). That way you can set a global welcome message too.

That makes sense to me.

**Comment by nerdvegas** [comment]
I am not a fan of adding this functionality, because a package is already
able to print to console after the resolve has occurred, and all the
necessary bindings (request and resolve object for eg) are there to get
info from already.

https://github.com/nerdvegas/rez/wiki/Package-Commands#info

I don't think it's appropriate that any given package should be able to
alter the standard message. Packages can override settings, but those
overridden settings are only used in the context of building said package,
so in that case it makes sense. If two or more packages wanted to redefine
"message", correct behavior would be unclear.

Note that "rez-env -q" is already available, and using a combo of -q and
the existing 'info' function should give you the printout you're after.

Thx
A

**Comment by mottosso** [comment]
Agreed, the `-q` flag and `info()` solves this for me.
