### ISSUE TITLE
[Feature] rez build --version

### ISSUE THREAD

**Issue by mottosso** [nerdvegas/rez#633]
### Goal

Alternative to specifying a version from within the `package.py`.

### Motivation

I was looking to generate lots of versions of a given package programmatically, but quickly realised there wasn't any way to specify a version other than by editing the `package.py` prior to calling `rez build --install`.

Beyond that, in porting an existing package management system to Rez, one of the differences was that the version wasn't given within the package definition, but rather during release.

```bash
$ other-system release --version 1.0.0
```

There isn't anything inherently wrong the current way versions are specified with Rez I think, nor with this other-system. However most of the time, changes you make are to the payload like Python module and so rather than having to also update the `package.py` due to technicalities, you could simply pass a version via the command-line.

These are essentially two different mindsets to releasing/installing packages. The current system has the advantage of being very specific, as one would need to remember the current version in order to increment properly, or look it up amongst released packages. The other-system didn't have to worry about that, because packages were published in context with the previous packages; in a GUI that visualised the currently available versions, which carried the additional benefit of visually indicating whether a chosen version was available or misformatted interactively.

### Implementation

Provide an override to the version in `package.py` in the Rez CLI.

```bash
$ rez build --install --version 1.0
```

- If `--version` was not provided, use `package.py:version`
- If `--version` was not provided and there is no `package.py:version`, abort.

### Extras

This could also be helpful for debugging, development and tutorials.

- In my [rez-for-projects](https://github.com/mottosso/rez-for-projects) repository, I'd like to provide example packages but also generate a repository of many versions. With this, I could have a script call `rez build --version` multiple times, with multiple versions to simulate a large repository. Without it, I would need to programatically open and write to each `package.py` prior to calling `rez build`; hacky
- For performance testing, I'd like to generate a large mock-repository of packages with many versions. With this feature, I would hand-craft a few, and install lots of versions programatically
- For debugging, I'd like to publish a copy of a repository as a `*.beta` and would need to edit the package.py for this to happen. Since I wouldn't want to keep or push this change, I would then need to remember to remove this temporary change once installed.

**Comment by JeanChristopheMorinPerso** [comment]
Hey @mottosso, I think overriding the version with `--version` at build or release time goes against the idea and principle of a package manager. In pretty much every packager I know of and used (pip, pipenv, poetry, yum, npm, etc) (it's probably possible with mvn though and others with some fancy args passed in CLI like `-DcustomVersion=1.0.0` where customVersion` is referenced by the package configuration file), the version is controlled from the package config file (package.py, package.json, Pipfile...) and can't be overriden from the command line.

>I was looking to generate lots of versions of a given package programmatically, but quickly realised there wasn't any way to specify a version other than by editing the package.py prior to calling rez build --install.

That seems like a really specific case that doesn't seems like a common problem right? I mean how many times would you need to do that? I do understand that you have a need, but isn't this need too specific to be added to rez?

>However most of the time, changes you make are to the payload like Python module and so rather than having to also update the package.py due to technicalities, you could simply pass a version via the command-line.

Can you elaborate more on this? I'm not entirely sure to understand what you mean.

>For performance testing, I'd like to generate a large mock-repository of packages with many versions. With this feature, I would hand-craft a few, and install lots of versions programatically

That again sounds like a really specific case.

>For debugging, I'd like to publish a copy of a repository as a *.beta and would need to edit the package.py for this to happen.

I'm not sure what you mean by publish... But for debugging a version, you can simply `rez-build -ci` the same version and rez will take your local package first during the resolve. That's what I do all the time. That way I don't have to edit the `package.py`

>Since I wouldn't want to keep or push this change, I would then need to remember to remove this temporary change once installed.

Wouldn't it be the same with `--version`? You would still have to remember to remove it no?

I'd be happy to hear what others think about that and discuss more about it.

**Comment by mottosso** [comment]
One more usecase, touching on #577.

```bash
$ cd maya
$ rez build --install --version 2016
$ rez build --install --version 2017
$ rez build --install --version 2018
```

Where the `maya/package.py` could look like:

```python
name = "maya"

def commands():
  if system.platform == "windows":
    env.PATH.append("c:\program files\autodesk\maya{version}\bin")
```

Potentially written as:

```bash
$ rez build --install --version 2016 2017 2018
```

**Comment by nerdvegas** [comment]
I agree with JC on this one. The rez project was started specifically to avoid ambiguity and under-defined packages. It came from a time in VFX when most in-house packages required a lot of knowledge of a package and its dependencies to even build and install it. An early goal was to be able to `rez-build -i` / `rez-release` a package, specifically without needing any prior knowledge of said package.

I don't think this feature would bring much to the table besides avoid a local package.py update which changes the version. It would also be odd for `--version` to be available in rez-build, but not rez-release - and yet, I would consider it a terrible idea to support this in a release, since it'd result in a tagged copy of the package definition in a git repo which doesn't specify the version at all, meaning that without prior knowledge, it would be impossible to reproduce the same package again at a later date (or in another location).

As well as this - and you'll probably see this become a theme - every change adds complexity and increases the size of the project, and so its relative benefits have to be weighed against that. In this case, I'd put more weight behind the proposal if this was something that had been asked for multiple times in the past, but it hasn't.
