### ISSUE TITLE
[Support] How to add packages to existing environment?

### ISSUE THREAD

**Issue by santosh** [nerdvegas/rez#638]
A new environment can be started with `rez-env package`. But suppose I forgot to pass package2 to rez-env that time. How do I add _package2_ to the current env? 

I tried doing `rez-env --patch package2`, but that starts a new env inside current env _(Double `>` appears at the shell)_. 

Hope you guys are getting me.

**Comment by mottosso** [comment]
Hi @santosh, I think you've got it right, `--patch` does add a package to your current environment. The new environment *inherits* the current environment, and that extra `>` you're seeing is a visual cue to help you understand how many times you've patched.

You should be able to spot the newly added package amongst previous existing packages by calling `rez context`.
