### ISSUE TITLE
[Bug] rez-bind platform appears to fail when $HOME contains `@` symbol

### ISSUE THREAD

**Issue by Ahuge** [nerdvegas/rez#645]
Hey, looking at trying to use rez internally here at VitalityVFX, I have seen demos of it at previous studios but we never managed to transition over to it, I figured that I would try to start us off on rez before we had too much in place.

## Problem
```bash
[ahughes@alex tmp]$  rez-bind platform
searching /software/rez/2.31.0/lib/python2.7/site-packages/rez-2.31.0-py2.7.egg/rez/bind...
creating package 'platform' in /mnt/Profiles/ahughes@netflix.local/packages...
17:52:29 ERROR    RezPluginError: Unrecognised package repository plugin: '/mnt/Profiles/ahughes'
```
I don't totally know what that means, but it seems to be related to the `@` symbol in my home directory.

I tried changing user to be a local user with a normal home directory in "/home" and was just told to create `/home/localuser/packages` and when I did, the rez-bind command completed.

I am pretty new to rez, so there may be something that I can do that I don't know about.

**Comment by instinct-vfx** [comment]
I looked that up in the code quickly (for reference this happens in package_repository.py). The reasons this breaks for you is that repository paths can either be straight paths OR "type@location" to enable enforcing a specific repository type (i assume that is needed if the URI does not allow to detect the repository type automatically).
The implementation splits on first occasion of @ only so setting the path like this works for me:

`filesystem@/mnt/Profiles/ahughes@netflix.local/packages`

Mind you i am on windows, but i don't see anything in the code that should change this behavior on linux.

**Comment by aprayez** [comment]
There was an issue for this already I think :)

https://github.com/nerdvegas/rez/issues/573

**Comment by Ahuge** [comment]
Thanks everyone, I'll go rally over there
