### ISSUE TITLE
[Support] How to save/load environment resolves?

### ISSUE THREAD

**Issue by santosh** [nerdvegas/rez#648]
From README:

> * Environment resolves can be saved to disk and reused at a later date (a bit like VirtualEnv);

I don't see any wiki page where it is documented. If there is, please point me out.

**Comment by lambdaclan** [comment]
Hello santosh,

The feature you are looking for is called resolve baking, the wiki page is located here --> https://github.com/nerdvegas/rez/wiki/Contexts#baking-resolves.

Hope this helps.

**Comment by nerdvegas** [comment]
https://github.com/nerdvegas/rez/wiki/Contexts
and
https://github.com/nerdvegas/rez/wiki/Suites

Hth
A
