### ISSUE TITLE
Rez at SIGGRAPH 2019

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#655]
Hi all,

The ASWF have generously sponsored me to head over from Australia to attend SIGGRAPH and present a rez talk. At present time, the BoF is scheduled for 10am Tuesday 30th July.

The talk will be presented by myself and my work college Stephen aka @maxnbk. It will be in three parts. The first will be an overview of how Method have integrated rez into their production environment; the second will be a roadmap presentation going over project goals and the development needed to get there; the third will be Q&A time. I'll be working on the roadmap and associated tickets in the coming weeks, and welcome feedback prior to the talk.

Thanks all for your ongoing support and development time, and I hope to see some faces there both old and new!

Thanks
Allan

**Comment by bfloch** [comment]
Won't make it, but highly appreciate the ASWF's work and support.
Hope you will be able to share slides afterwards.

**Comment by lambdaclan** [comment]
This is amazing news Allan, congratulations on the sponsorship from ASWF which is very encouraging for the future of rez.

Unfortunately, I will be unable to attend this time but hopefully will make it at a different event, a bit closer from here :)

I hope your presentation goes smoothly and as Blazej mentions I hope you will be able to share the slides or even the video if is being recorded.

Looking forward to seeing the roadmap section to get some ideas on how we can further help improve rez.

Good luck!

Ira

**Comment by KelSolaar** [comment]
Super sweet! :)

**Comment by instinct-vfx** [comment]
Hey Allan,

that's really great to hear as i said before and i am also very happy that the ASWF is showing interest to that level already!

Looking forward to the roadmap a LOT here!

**Comment by jasoncscott** [comment]
Can we record somehow?  And I think we're tentatively trying for a repeat at SIGGRAPH Asia in Brisbane as well?

**Comment by JeanChristopheMorinPerso** [comment]
Great news! Though I'm sad cause I can't make it to the Siggraph this year :( Looking forward for the roadmap and maybe a potential recording of the session?

**Comment by larsbijl** [comment]
This is great! Looking forward to it!

**Comment by swallitsch** [comment]
@nerdvegas this is on the Siggraph schedule as 12-1pm, Tuesday
![image](https://user-images.githubusercontent.com/32879218/61472685-d26b7b00-a939-11e9-908c-9d1af009d042.png)

**Comment by nerdvegas** [comment]
Yeah times are still moving around a bit so stay tuned.

A

**Comment by nerdvegas** [comment]
https://s2019.siggraph.org/presentation/?id=bof_179&sess=sess570

Tuesday 12-1pm. Lunch provided, win!

**Comment by nerdvegas** [comment]
Ps - It would be great if someone could record it so speak up if you mat be able to. Besides that, there will definitely be slides available afterwards.

A

**Comment by bpabel** [comment]
I'll be attending Siggraph.  I have some camera gear and live relatively close by so I should be able to bring it with me.

**Comment by nerdvegas** [comment]
Hey all, I've been informed by the ASWF that they're already recording all presentations and will share them afterwards. Win!

**Comment by smaragden** [comment]
This is amazing!
I will be there and really looking forward to it!

See you on Tuesday!
/Fredrik

**Comment by bfloch** [comment]
I'll just drop the recording for future reference:
https://www.youtube.com/watch?v=y5VSPeeqJbM

**Comment by nerdvegas** [comment]
Actually this reminds me.. I'll add a section to the wiki to keep track of
media like this, cheers.
