### ISSUE TITLE
[Feature] Additional tools to add to PATH

### ISSUE THREAD

**Issue by bfloch** [nerdvegas/rez#660]
## Goal 

In order to provide tools like `dot` to resolved rez environments without having to rely on the system I would like to extend the rezconfig with an additional mechanism to prepend/append to PATH within environments.

## Currently rezconfig provides options to ...

1. `parent_variables`: Inherit variables (PATH) from the current environment
2. `standard_system_paths`: Provide a static list of PATH variables, as opposed to the default system variables
3. `rez_tools_visibility`: Option to append/prepend the Script/rez or bin/rez tools to the path

## Problems with the available options
1. This means all variables are inherited, which may easily conflict as the comments show
2. You would need to duplicate all the PATHs and maintain them
3. This is ideal since we can append / prepend and the tools are closely related, but we need to provide our own paths.

## Proposed solutions

A) Create a rezconfig list `rez_additional_tools` which is expanded and added following the logic of `rez_tools_visibility` (after it for backwards compatibility).

B) Alternatively allow 2. to be prepended / append as opposed to replacing the current PATH discovery from the system. 
I propose a new config variable: `standard_system_path_visibility` that accepts: 

- `replace` (default/backwards compatible)
- `append`
- `prepend`

EDIT: This option affects how the `standard_system_paths` behave.

I would be fine with either option and would be willing to implement it.

**Comment by bfloch** [comment]
I went forward to implement variant B) but I am struggling to do the right thing.

Currently:
`resolved_context` -> `rex.append_system_path()` + `rex.append/prepend_rez_tools()` -> `shell(instance)->get_syspath()`

get_syspath in turn is checking the config to either use the standard_system_path = [] or get it from an clean environment by any means possibly for the the particular shell.

Now I could nicely remove the logic from get_syspath() and move it up one level to rex / resolved_context to fit the api nicely.
This way the shell would ALWAYS return a system PATH and it is up to rex / resolved context to adapt it to the configuration's need.

However the shell also implements the `which` function which in turn only relies on its own get_syspath().
So it will not discover the tools added at all - it might even break existing functionality.

Note: As is, the which kind of acts wrong (by design?) because it has no notion of the added rez_tools. But that might be fine since rez_tools are a construct of a resolved_context (??).

My thought - in order to keep the functionality compatible and the which intact is to move all the new system_path logic down to the shell level. I could easily manage it with a decorator so we don't need to repeat ourselves. It also moves some of the class variable caching into a centralized location, which is nice.

But then the newly introduced options will not affect HOW the system path is being added on the upper level. So replace/append/prepend really means only from the standard_system_path level.

The result will still be just appended in rex - as is, compatible to current behavior.
That is all ok, intended, solves my request and is still backwards compatible.

The only downside will be that the implementation looks different from the rez_tools since it happens on a lower level. But I can live with that and would add a comment for future reference so developers looking into rex are not confused.

If this is all confusing let me drop a PR and hopefully it will clear things up.

**Comment by bfloch** [comment]
Quite happy with the PR as is. Feedback welcome over there.

**Comment by nerdvegas** [comment]
Hey Blazej,

I think I need to see the PR!

I'm fine with your proposal, the functionality makes sense. However one
thing I was thinking, I wonder if it'd be a little simpler to not add the
new 'standard_system_path_visiblity' setting, but instead provide the same
functionality like so:

standard_system_paths = [
  "__PATH__",
  "/some/custom/stuff
]

Ie, "__PATH__" would be replaced with standard systems paths.

Thx
A

**Comment by bfloch** [comment]
Closing in favor of #737
