### ISSUE TITLE
[BUG] Windows cmd-shell fails on commands with whitespaces

### ISSUE THREAD

**Issue by bfloch** [nerdvegas/rez#664]
The test `test_build.TestBuild.test_build_cmake` fails with cmd on Windows if CMake is installed in the default location `C:\Program Files\CMake\cmake.exe`.

The source of the problem is cmd.py - `join()` https://github.com/nerdvegas/rez/blob/master/src/rezplugins/shell/cmd.py#L303

... since it simply returns a single string, and then Popen interprets `C:\Program` as the command.

I don't yet know how to fix this since simply escaping like the Unix shells do means that the passing to the cmd command fails since it already uses quotes.

https://github.com/nerdvegas/rez/blob/master/src/rezplugins/shell/cmd.py#L221

Need to look deeper, suggestions appreciated.

**Comment by rusreh** [comment]
Can you use the env variables %ProgramFiles% and %ProgramFiles(x86)% ?

**Comment by bfloch** [comment]
Would not help. At the end it is expanded.

**Comment by ChinaArvin** [comment]
i have the same problem

**Comment by bfloch** [comment]
I'm closing this in favor of #691 
As mentioned over there it is being handled by #698
