### ISSUE TITLE
build scripts generated with incorrect shebang arg

### ISSUE THREAD

**Issue by joehigham-bss** [nerdvegas/rez#671]
After `rez build -s`, [v2.38.1](https://github.com/nerdvegas/rez/releases/tag/2.38.1) creates this first line in build-env:

`#!/usr/bin/env _rez_fwd`

However, the installed name is now `_rez-fwd`

I've fixed it locally by changing [src/rez/util.py:80](https://github.com/nerdvegas/rez/blob/e6217a09cc13656fbde69c0f057618fecc472aad/src/rez/util.py#L80) to:

`    create_executable_script(filepath, body, "_rez-fwd")`

**Comment by instinct-vfx** [comment]
I created a PR for this. Nice catch.

**Comment by nerdvegas** [comment]
Thanks, I think the bin name change was unintentional but I'll take the PR fix in any case.

**Comment by nerdvegas** [comment]
Should be fixed in https://github.com/nerdvegas/rez/releases/tag/2.38.2.

Fun note: `create_executable_script` needs to be updated to somehow use distlib's `ScriptMaker` instead, so that we can create executables cross platform (currently this doesn't work on Windows).
