### ISSUE TITLE
Add shell plugin for poweshell 6+

### ISSUE THREAD

**Issue by instinct-vfx** [nerdvegas/rez#678]
As a user i would like to be able to use powershell core 6.0/6.1. There is no feature parity between powershell 5.x and powershell core and the executable has been renamed to pwsh.

This issue aims to add support for powershell core. It is not yet clear to me how much of a difference (if any at all) there has to be except for the executable name.

**Comment by instinct-vfx** [comment]
Initial PR created, functionality is there but not tested extensively yet.

**Comment by nerdvegas** [comment]
Closed by #679 (https://github.com/nerdvegas/rez/releases/tag/2.39.0)
