### ISSUE TITLE
Quotation marks issues on Windows.

### ISSUE THREAD

**Issue by KelSolaar** [nerdvegas/rez#691]
Hi,

I'm testing 2.40.1 to upgrade from 2.16.0 and I'm having issues with quotation marks on Windows.

Specifically:

```cmd
C:\Users\thomas>rez-env substance_painter -- "Substance Painter"
'Substance' is not recognized as an internal or external command,
operable program or batch file.
```

It could be related to #664 but I'm not sure yet, I will try to take a look.

Cheers,

Thomas

**Comment by nerdvegas** [comment]
Hi Thomas,

I wonder also if it's related to
https://github.com/nerdvegas/rez/releases/tag/2.35.0. Can you test that and
the version before it? (https://github.com/nerdvegas/rez/releases/tag/2.34.0
).

The changes in 2.35.0 do potentially affect how the command is escaped in
cmd. If that is the case, it's certainly worth looking at the merged PR
thread. Please let me know how you go!

Thanks,
A

**Comment by KelSolaar** [comment]
Hi @nerdvegas,

Confirming that 2.35.0 introduced the issue, 2.34.0 is working as expected! I will look at what the PR changed.

Cheers,

**Comment by KelSolaar** [comment]
So quickly comparing the generated *rez-shell.bat* and the command call:

### Rez 2.34.0

*rez-shell.bat*

```shell
set REZ_ENV_PROMPT=%REZ_ENV_PROMPT%$G
call c:\users\thomas\appdata\local\temp\rez_context_azh6ou\context.bat
set REZ_STORED_PROMPT=$P$G
set PROMPT=%REZ_ENV_PROMPT% $P$G
"Substance Painter"
exit %errorlevel%
```

*Command Call*

```shell
['c:\\windows\\system32\\cmd.exe', '/Q', '/C', 'call c:\\users\\thomas\\appdata\\local\\temp\\rez_context_azh6ou\\rez-shell.bat']
```

### Rez 2.35.0

*rez-shell.bat*

```shell
set REZ_ENV_PROMPT=%REZ_ENV_PROMPT%$G
call c:\users\thomas\appdata\local\temp\rez_context_mjdt6d\context.bat
set REZ_STORED_PROMPT=$P$G
set PROMPT=%REZ_ENV_PROMPT% $P$G
```

*Command Call*

```shell
['c:\\windows\\system32\\cmd.exe', '/Q', '/C', 'call c:\\users\\thomas\\appdata\\local\\temp\\rez_context_mjdt6d\\rez-shell.bat', '& Substance Painter']
```

The double-quotes are effectively gone but to make matter worse, tweaking the code so that the command call is as follows:

```shell
['c:\\windows\\system32\\cmd.exe', '/Q', '/C', 'call c:\\users\\thomas\\appdata\\local\\temp\\rez_context_beyump\\rez-shell.bat', '& "Substance Painter"']
```

still errors out:

```shell
'\"Substance Painter\"' is not recognized as an internal or external command,
operable program or batch file.
```

Haven't followed exactly the PR discussions, I'm wondering what was the rationale for this separation compared to having everything in the .bat file?

**Comment by KelSolaar** [comment]
@mottosso : I suppose this discussed issue was introduced with #627, any idea of how to circumvent that?

**Comment by nerdvegas** [comment]
Best person to speak to would be @mottosso. If that release has caused
problems that don't appear to be solvable, then it can be reverted.

Here is the first PR that you may have missed (it wasn't merged):
https://github.com/nerdvegas/rez/pull/626
And there is the replacement PR that was merged into that release:
https://github.com/nerdvegas/rez/pull/627

Would be great to get your input as I don't do the Windows stuff.

Thanks Thomas,
A

**Comment by KelSolaar** [comment]
Ah! We just cross-posted @nerdvegas :]

**Comment by nerdvegas** [comment]
Hey Thomas, have you had a chance to look further into this?

Cheers
A

**Comment by KelSolaar** [comment]
Hey @nerdvegas,

I spent a few hours but I, unfortunately, could not get it to work at all. I would probably suggest to revert the PR unless @mottosso has an idea.

Cheers,

Thomas

**Comment by nerdvegas** [comment]
Ok no worries. I'm off on vacation for a week, but I'll make it a priority
to get this reverted when I get back, unless other options present
themselves in the meantime.

Thanks for looking into it.
A

**Comment by instinct-vfx** [comment]
Thanks are a bit busy here currently but i will try to look into it or have someone here look into it in the meantime.

**Comment by Jordibastide** [comment]
Hi all,

I'm encountering a linked issue with [CMakeBuildSystem.build_systems values](/src/rezplugins/build_system/cmake.py#L42) that results to non quoted generators names in cmake commands

Thanks

**Comment by nerdvegas** [comment]
Cheers Blazej, I'll get to this one soon.
A

**Comment by nerdvegas** [comment]
Closed by https://github.com/nerdvegas/rez/pull/698
