### ISSUE TITLE
Shell plugin Support API

### ISSUE THREAD

**Issue by bfloch** [nerdvegas/rez#696]
(Not sure if this qualifies as REP since it is quite small in scope, feel free to rename/tag)

Currently shell plugins are expected to available on specific platforms:

```
Windows -> cmd
Windows -> PowerShell
Windows -> Pwsh
Non-Windows -> bash
Non-Windows -> zsh
...
```

The logic for the platform is defined in the windows specific shells via `if windows ...`

We recently got more shell plugins which could be considered _optional_, but also we live in complex times with WSL, MacOS switching from bash to zsh etc. where it is hard to predict which shells will work on which platform.

I suggest we add two new pure abstract read-only classmethods to the Shell base class:

```
is_required
    States if Shell is required on current platform.
    This way we can still generate sensible exceptions in cases an expected shell is 
    not available.
    This might also help implementing more details logic like for example if a 
    platform deprecates and removes a shell we generate platform version specific
    results.

is_available
   States if Shell is available on current platform. In most cases this is just going through
   the implementation of the executable discovery, but it will not throw and states the 
   intend better for availability checks.
```

A platform-dependent required Shell can be now implemented like this

```python
class Cmd(Shell):

@classmethod
def is_required(cls):
    # ...
    return platform_.name == "windows"

@classmethod
def is_available(cls):
    try:
        return cls.executable is not None
    except RuntimeError:
        return False
```

An optional platform can be implemented via:
```python
class Zsh(SH):

@classmethod
def is_required(cls):
    # Pseudo code with sample versions
    return platform_.name = "macos" and platform_.os > "12.2"

@classmethod
def is_available(cls):
    try:
        return cls.executable is not None
    except RuntimeError:
        return False
```

The plugin registration now becomes uniformly:

```python
def register_plugin():
    return _verify_shell(Zsh)

def _verify_shell(shell):
    if shell.is_available():
        return shell
    elif shell.is_required():
        raise RequiredShellNotAvailable(shell.name)
    return None
```

EDIT 1: Python version agnostic class properties are somewhat complicated. Sticking to class methods.

**Comment by nerdvegas** [comment]
Sure I don't have a problem with this, although I don't think it's a REP.

One thing I'd say is that is_required is a little confusing, perhaps
is_supported would be more intuitive.

Thx
A

**Comment by bfloch** [comment]
Thanks for the feedback.
I'll add it as separate commit to my shell improvement branch.

**Comment by nerdvegas** [comment]
Revisiting this. So I'm going to implement part of this just now, because currently, rez-selftest will fail if you don't have one of the supported shells installed. This isn't really intuitive - if I don't have zsh installed for eg, I would expect those tests to be skipped.

To that end, I'll put in a PR which:
* adds an 'is_available' method to shells, as described above;
* update the 'shell_dependent' test decorator to only iterate over available shells.

A note on plugin registration: I think plugin registration shouldn't contain any logic beyond a simple platform check, where we know that the shell is only an option for that platform(s). Anything else (eg whether it's required, whether it's installed on the system) are runtime considerations.

**Comment by nerdvegas** [comment]
I'm going to close this as #747 largely addresses it. However if anyone feels that further aspects of this ticket need to be addressed, please feel free to open a new ticket, cheers!
