### ISSUE TITLE
rez-pip should assume python provided pip

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#706]
Newer python versions ship with pip, however rez-pip first searches for a rezified pip package, falling back to its own pip installation if one isn't found.

Instead, rez-pip should (in this order):
* Search for rezified python matching python version request;
* If found, test if pip is present;
* If pip is present, use it;
* If not present, search for rezified pip (this is for backwards compatibility);
* If rezified pip is found, use it;
* If not, fall back to rez's python installation.

The rez-pip `--pip-version` arg should also be marked as deprecated (though not removed just yet).

**Comment by maxnbk** [comment]
Could it be made possible to influence the request for pip made in step 4? I have had times where I needed to test against one rezified pip over another.

**Comment by JeanChristopheMorinPerso** [comment]
>Search for rezified python matching python version request;

What happens if the python version is not requested? We take the latest? Or we simply make the `--python-version` mandatory? I think I'd go with `--python-version` being mandatory so that it is more explicit which version is taken and avoids mistakes and better fits with the general philosophy of `/path/to/python -m pip`.

What do you think?

**Comment by nerdvegas** [comment]
I think it's more "rezish"(?) to just default to latest python package
found - not specifying python version should be equivalent to a 'rez-env
python' if you see what I mean.

Wrt specific rezified pip - I wouldn't put too much effort into this, since
we know we're headed to a place (py3) where we expect pip to be provided by
python itself. In the meantime, it's not so hard to alter REZ_PACKAGES_PATH
to get the correct pip chosen anyway. Having said that, I think better
logging verbosity and addition of a `--dry-run` mode would further justify
leaving things as they are.

A
