### ISSUE TITLE
#712 merged in 2.43.0 caused external environ not to pass through to resolve

### ISSUE THREAD

**Issue by maxnbk** [nerdvegas/rez#744]
testable between `2.42.2` and `2.43.0` by `rez-env`-ing a package with:
```
def commands():
    print(env.keys())
```
result in `2.42.2` is a list of variable names, 2.43.0 is `[]`

solved in incoming PR.

**Comment by maxnbk** [comment]
addressed in #745

**Comment by nerdvegas** [comment]
Closed by https://github.com/nerdvegas/rez/pull/745
