### ISSUE TITLE
Rez environment not evaluated in time for command on Windows

### ISSUE THREAD

**Issue by bsilvaLS** [nerdvegas/rez#746]
Hello! We're using Rez with the Shotgun Toolkit, and I've just updated to the latest Rez version. In the latest, the rez_app_launch.py script is failing here:

https://github.com/nerdvegas/rez/blob/9aaf75c16a2705d50b44e3ef08e6737b2066357d/src/support/shotgun_toolkit/rez_app_launch.py#L134

If I run that command myself at the command prompt, now I just get back the environment variable string instead of the path:

```
> rez-env rez -- echo %REZ_REZ_ROOT%
%REZ_REZ_ROOT%
```

I've narrowed this down to [v2.35.0](https://github.com/nerdvegas/rez/releases/tag/2.35.0) -- it works fine in v2.34.0, so I suspect this is an unintended consequence of the Windows changes made in that version.

Any ideas? Thanks!

**Comment by nerdvegas** [comment]
Hello,

This is almost certainly a regression introduced in v2.35.0. Others
have reported similar issues.

The good news is that there's a PR in to fix this, and we'll be merging it
really soon! In the meantime, if you're able, could you test with
https://github.com/bfloch/rez/tree/enhancements_for_shell_plugins and
report back?

Said PR: https://github.com/nerdvegas/rez/pull/698

Thx,
A

**Comment by bsilvaLS** [comment]
That's great news!

I cloned/installed the bfloch fork, and it all seems to be working again:
```
rez-install\bfloch\Scripts\rez> rez-env rez -- echo %REZ_REZ_ROOT%
\\...\rez-packages\ext\rez\2.18.0\platform-windows
```

(Clearly I need to update that package, too.)

Thanks a lot!

**Comment by nerdvegas** [comment]
Great, thanks for the test. Merge coming soon,
A

**Comment by bfloch** [comment]
@bsilvaLS This fork has been released as https://github.com/nerdvegas/rez/releases/tag/2.47.0
Give it a try and feel free to close the issue if it still works for you.

**Comment by bsilvaLS** [comment]
@bfloch I've been testing this for a few days and so far it works great! Thanks a lot for your work.

**Comment by bfloch** [comment]
Glad to hear.
Closing this issue. Feel free to open a new one if necessary.
