### ISSUE TITLE
find_pip_from_context failing on Windows platform

### ISSUE THREAD

**Issue by theceebee** [nerdvegas/rez#796]
The recent changes to the rez pip module have broken pip installs on Windows,

https://github.com/nerdvegas/rez/blob/6db191f4aa01903e22955cf38e8342cb8697a499/src/rez/pip.py#L162

When doing a `context.which` call to find the python executable the major version token is being appended to 'python' which on Windows returns None.

This causes an issue with the subsequent `subprocess` call which attempts to find a pip install.

**Comment by JeanChristopheMorinRodeoFX** [comment]
Hi @theceebee , thanks for the report. I'm the one who changed this part of the code. I'm being told by @instinct-vfx that the executable with a version in its name on Windows only exists in Python 3. :neutral_face: Someone (me or @instinct-vfx probably) will create a PR shortly to fix this.

**Comment by theceebee** [comment]
Fantastic. I'll keep an eye out.

**Comment by JeanChristopheMorinPerso** [comment]
@theceebee If you want to test, you can test with #798 . Just checkout and install and see how it goes.
