### ISSUE TITLE
"rez-env pkg -- command" usage is undocumented in rez2.

### ISSUE THREAD

**Issue by ihenckel** [nerdvegas/rez#803]
`rez-env -h` contains no mention of the ability to pass a command following a double-dash.

**Comment by predat** [comment]
https://github.com/nerdvegas/rez/wiki#examples

**Comment by ihenckel** [comment]
It does seem to be used ubiquitously in the wiki docs. If it's actually the preferred usage (as opposed to `-c`), it would be great to have it in the `-h` where most users will look first.

**Comment by ColinKennedy** [comment]
"rez-env -- foo" is shown in both https://github.com/nerdvegas/rez/wiki#examples and at the bottom of https://github.com/nerdvegas/rez/wiki/Getting-Started.

Maybe we can make it more visible to users. But then again this documentation issue was made a while ago so maybe we can just close this one.

**Comment by nerdvegas** [comment]
outdated request, closing
