### ISSUE TITLE
rez-cp fails with argument error if --variants argument is used last

### ISSUE THREAD

**Issue by instinct-vfx** [nerdvegas/rez#812]
Discovered with 2.47.3 on windows.

When running rez-cp with the --variants argument and the --variants argument is the last before the package rez-cp failes with `rez cp: error: argument --variants: invalid int value: '3dsmax-2018'`

**Example:**
![image](https://user-images.githubusercontent.com/243828/69850843-84b83500-1280-11ea-9ff2-b962dc40a5f6.png)

**Switching the --variants and the --dest-path arguments makes it work:**
![image](https://user-images.githubusercontent.com/243828/69850881-a2859a00-1280-11ea-8a34-c5aedeb4508b.png)

**Comment by nerdvegas** [comment]
This is just an argparsing issue - `--variants` accepts an arg list, so `3dsmax-2018` is getting consumed as a variant (which is valid because variant indexes are currently int-based, but not guaranteed to be in future).

Closing this but please let me know if there are further issues.
