### ISSUE TITLE
rez-bind os - centos, inconsistent name

### ISSUE THREAD

**Issue by HansBaldzuhn** [nerdvegas/rez#813]
Hi everyone,

I have an issue with the default os package on centos.
I have computer with mixed centos (mainly 7.6 and 7.7) and we found that rez returns two differents value for the os name.

``` bash
rpm -q centos-release
>> centos-release-7-7.1908.0.el7.centos.x86_64
rez env os
>>  resolved packages: os-CentOS-7.7.1908
```
```bash
rpm -q centos-release
>> centos-release-7-6.1810.2.el7.centos.x86_64
rez env os
>> resolved packages: os-centos-7
```

As you can see, the os string is returned with a different case. 

After some investigation, the difference comes from here [https://github.com/nerdvegas/rez/blob/a9f61980a9cebcf67df09023cccdcbf1b9edea66/src/rez/utils/platform_.py#L230](url)

On the centos 7.6, the lsb_release executable doesn't exists and the value for distributor is found by parsing the file ```/etc/os-release```
Whereas on the centos  7.7, ```lsb_release``` executable is found and the data is taken from the output of the command.

With this information, the issue might have nothing to do with centos version but with the availability or not of the command ```lsb_release``` ( part of ```redhat-lsb``` yum package ).

I will make sure all different computer here have the ```redhat-lsb``` yum package installed so this will hopefully be fixed for us.

But I wanted to report here in case there is something that can be done on the rez side to avoid such difference in os resolution.

Best,
Hans

**Comment by nerdvegas** [comment]
Hi Hans,

You can get around this issue currently by using the 'platform_map' config
option: https://github.com/nerdvegas/rez/wiki/Configuring-Rez#platform_map

Something we're also considering is using https://github.com/nir0s/distro.
Actually it would be useful if you could verify if this gives you
consistent results. Do you mind giving it a go?

Thx
Allan

**Comment by JeanChristopheMorinPerso** [comment]
@nerdvegas We will need the `distro` package quite soon as the `platform.linux_distribution` function is officially gone in Python 3.8. My Arch linux on which I develop is on 3.8 and I had to patch rez locally to fix a bunch of issues (one of which was the platform.linux_distribution).

**Comment by HansBaldzuhn** [comment]
@nerdvegas 
I didn't understand how 'platform_map' is working.
Is is read at each resolution or should I setup it before I do rez-bind ?

As for the distro package here are my results:
``` bash
rpm -q centos-release
>> centos-release-7-7.1908.0.el7.centos.x86_64
distro -j
>>
{
    "codename": "Core", 
    "id": "centos", 
    "like": "rhel fedora", 
    "version": "7", 
    "version_parts": {
        "build_number": "", 
        "major": "7", 
        "minor": ""
    }
}
python
import distro
distro.linux_distribution(full_distribution_name=False)
>> (u'centos', u'7', u'Core')
```
``` bash
rpm -q centos-release
>> centos-release-7-6.1810.2.el7.centos.x86_64
distro -j
>>
{
    "codename": "Core", 
    "id": "centos", 
    "like": "rhel fedora", 
    "version": "7", 
    "version_parts": {
        "build_number": "", 
        "major": "7", 
        "minor": ""
    }
}
python
import distro
distro.linux_distribution(full_distribution_name=False)
>> (u'centos', u'7', u'Core')
```

It removes the difference in the name, but I loose information on minor numbers.
I then won't be able to differentiate both os.
Please note that I tried with python 2.7

@JeanChristopheMorinPerso 
Is the distro package present in python 3.8 the same as the one mentionned by @nerdvegas ? [https://pypi.org/project/distro/](url)

**Comment by JeanChristopheMorinPerso** [comment]
The distro package is not included with python 3.8. So the answer is yes, it's the same as Allan mentioned, except that it's not included in python 3.8.

And the distro package can be used like this:

```python
import disto

name = distro.id()  # returns 'centos'
version = distro.version(best=True)  # returns '7.6.1810'
```
See https://distro.readthedocs.io/en/latest/

**Comment by HansBaldzuhn** [comment]
Oh nice ! 
I just used the first exemple on the main page but with the correct function call it works perfectly !

``` bash
rpm -q centos-release
>> centos-release-7-7.1908.0.el7.centos.x86_64
import distro
distro.id()
>> u'centos'
distro.version(best=True)
>> u'7.7.1908'
```
``` bash
rpm -q centos-release
>> centos-release-7-6.1810.2.el7.centos.x86_64
import distro
distro.id()
>> u'centos'
distro.version(best=True)
>> u'7.6.1810'
```

**Comment by nerdvegas** [comment]
It seems `distro` may be the way to go then. Note that we'll have to be careful with this though, since it'll be a form of backwards incompatibility when the results differ from current code. It may be sufficient to explicitly document this in the release notes, and point out that `platform_map` can be used to retain current platform/arch/os if `distro` causes them to change.

Hans, are you able to resolve the issue by using `platform_map` to get the os version you expect? If so, I vote we close off this ticket and create a new one to port to `distro`.

Thx
A

**Comment by HansBaldzuhn** [comment]
Yes I resolved my issue.
I'm making sure both os have lsb_release available and I use platform_map to force both to have a lowercase centos os package (to match the result of what distro would output).

Thanks !

**Comment by nerdvegas** [comment]
FYI, we already have a ticket: https://github.com/nerdvegas/rez/issues/516
