### ISSUE TITLE
[User Question] How to import a module and use it in package.py?

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#829]
I'd like to have a package.py like this

```python
import foo

name = 'my_package'

version = '1.0.0'

description = foo.some_function()
```

The idea is that this import + function call will always work, even if I am building this package.py for the first time. I know you can import rez into package.py, but adding `some_function` would require me to fork Rez to make that change. Is there a way to get what I'm looking for without forking?

## What I've tried
- Creating a package and adding it to ~/.rezconfig as an implicit package. This does not work (it raises a `rez.exceptions.ResourceError` any time I build)

**Comment by instinct-vfx** [comment]
I would suggest thoroughly reading both the package commands page and the package definition guide page in the wiki. I stumbled over a lot of neat things that sooner or later came in handy :)

That said, i think you are looking specifically for the section on sharing code in the package definition guide: https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#sharing-code-across-package-definition-files

This deals with both sharing code amongst packages during build and across installed packages.

**Comment by instinct-vfx** [comment]
Oh and also take a look at the example package as it deals with some other options too.

For example if you define your attribute as a function you can import in the body of the function and to make packages available you can add them to your build_requires.

From the example package:
```
@early()
def variants():
    from rez.package_py_utils import expand_requires
    requires = ["platform-**", "arch-**", "os-**"]
    return [expand_requires(*requires)]
```

**Comment by ColinKennedy** [comment]
Thanks for the quick response and the links. I won't have time to test this until after the holidays but I will give this a try early next year. Happy holidays!

**Comment by nerdvegas** [comment]
Thorsten's link is what you want!

Basically you can't use rez packages in another packages' package.py,
because that's a catch 22 - packages only work properly within a resolved
runtime, and to construct the resolved runtime, rez needs to read the
package.py's.

Cheers
Allan

**Comment by ColinKennedy** [comment]
Hi everyone, Happy New Year!

I had a look at this problem again and I'm not 100% sure if that I'm seeing is user error or maybe my company's fork of rez may be causing an issue. But using **@early** raises an exception when importing code, even if that code is available in `package_definition_build_python_paths`.

Specifically, this errors for me

```python
@early()
def help():
    import sys
    return  []
```

It errors with ...

```
...
  File "/film/tools/packages/rez/2.30.0.17/CentOS-7_thru_8/lib/python2.7/site-packages/rez-2.30.0.17-py2.7.egg/rez/serialise.py", line 287, in _process
    value[k] = _process(v)
  File "/film/tools/packages/rez/2.30.0.17/CentOS-7_thru_8/lib/python2.7/site-packages/rez-2.30.0.17-py2.7.egg/rez/serialise.py", line 321, in _process
    value_ = fn()
  File "/fast/repositories/Assets/src/AL/AL_owl/package.py", line 11, in help
    import some_module
ImportError: __import__ not found
```

I'll try reproducing the error at home with a fresh Rez install. For now, I'm getting around the problem using the **@late** decorator. e.g.

```python
@late()
@include("rez_documentation")
def help():
    return [
        [rez_documentation.API_DOCUMENTATION_KEY, "API URL"],
        [rez_documentation.DEVELOPER_DOCUMENTATION_KEY, "DEVELOPER URL"],
        [rez_documentation.USER_DOCUMENTATION_KEY, "USER URL"],
    ]
```

**Comment by nerdvegas** [comment]
Hi Colin,

I can't replicate the problem on latest rez unfortunately - I've verified
that your example above works.

Side note, the docs on package help were wrong, I have updated that:
https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#help

Cheers and happy NY also,
A

**Comment by ColinKennedy** [comment]
I can confirm on the latest Rez that it works for me too. I also tried out 2.30.0, which is the version at work we're using. But it works for 2.30.0, too. 

Most likely it's an issue with the fork. Thanks again for teaching me the ropes @nerdvegas and @instinct-vfx !
