### ISSUE TITLE
Resolve timestamps should be in UTC

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [nerdvegas/rez#835]
The `REZ_USED_REQUESTED_TIMESTAMP` and `REZ_USED_TIMESTAMP` environment variables should be in UTC. That would mean stats exported with AMQP would be reliable when a studio is spanning across multiple timezones.

Or if nobody want the env var to be in UTC, I would at least make sure the timestamps sent to an AMQP server are in UTC format.

**Comment by nerdvegas** [comment]
They already are in UTC though? They are linux epoch time, which by definition is UTC (seconds since midnight on Jan 1st 1970, UTC).

**Comment by JeanChristopheMorinPerso** [comment]
Hey @nerdvegas , unfortunately, they are far from in UTC.

`time.time()` returns time since epoch in your current timezone, while `time.mktime(time.gmtime())` returns time since epoch in UTC.

Here is a little snippet to prove it:

```python
import time
import datetime
import subprocess

print 'time.time  : %s' % datetime.datetime.fromtimestamp(time.time()).isoformat()
print 'time.gmtime: %s' % datetime.datetime.fromtimestamp(time.mktime(time.gmtime())).isoformat()
stdout = subprocess.check_output(['date', '-u', '--iso-8601=seconds'])
print 'UTC        : %s' % stdout.strip()
```

The output looks like:
```
time.time  : 2020-01-14T17:03:45.421150
time.gmtime: 2020-01-14T22:03:45
UTC        : 2020-01-14T22:03:45+0000
```
The `time` documentation is extremely not clear and plain confusing (as with anything time-related in Python).

**Comment by nerdvegas** [comment]
I'm confused though: https://stackoverflow.com/questions/11845803/is-pythons-time-time-timezone-specific

I've also just ran `python -c 'import time; print time.time()'` across multiple timezones (easy to do as I'm in Sydney working remotely in LA!) and I get the same result.

**Comment by JeanChristopheMorinPerso** [comment]
I'm confused too. I decided to try with `dateutil` and get the UTC tz class to validate everything:

```python
# The substraction thing is what the "datetime.datetime.timestamp" method in Python 3 does
# to get a timestamp from a dateitme object.
>>> (datetime.datetime.now(tz=dateutil.tz.UTC) - datetime.datetime(1970, 1, 1, 0, 0, 0, 0, tzinfo=dateutil.tz.UTC)).total_seconds(); time.time()
1579046893.250527
1579046893.250568
```
Sorry for the noise. I'll just close this issue.
