### ISSUE TITLE
rez-pip - Add help / authors attributes

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#838]
Would it be possible to make ``rez-pip`` include help information when installing packages?

e.g. `rez-pip --install black` in my mind should generate a package.py file that looks like this

```python
# ...

authors = [
    u"Łukasz Langa (lukasz@langa.pl)",
]

help = [
    ["PyPI", "https://pypi.org/project/black/19.10b0'],  # version-lock the PyPI link
    ["Home Page", "https://github.com/psf/black"],  # use the url written in the setup.py file
]

# ...
```

Would you accept a PR with this addition?

**Comment by nerdvegas** [comment]
Yep.
A

**Comment by nerdvegas** [comment]
Closed by https://github.com/nerdvegas/rez/releases/tag/2.57.0
