### ISSUE TITLE
rez-env: --include flag must precede --no-local flag

### ISSUE THREAD

**Issue by LocksmithAnimation** [nerdvegas/rez#846]
This has a very simple workaround (or perhaps it's intentional?), but just wanted to raise this in case it has further ramifications --

It appears that the `--include` flag MUST precede the `--no-local` flag for Rez to resolve an environment properly.

For example, we have a `package_filter` in our config that excludes `*-beta`.

This command line does the correct thing:
`> rez-env --include "*-beta" --no-local <packages>`

but this resolves to an empty context:
`> rez-env --no-local --include "*-beta" <packages>`

 -- Brian --

**Comment by nerdvegas** [comment]
Hey Brian,
The issue actually isn't related to `--no-local` at all. You've simply used an nargs option (`--include`) at the end, so `<packages>` are being consumed as filters.

Closing as this is an argparse limitation that applies to a great number of cli tools.

**Comment by LocksmithAnimation** [comment]
Ah fair enough, thanks!
