### ISSUE TITLE
"rez-env" without arguments produces errors on Windows.

### ISSUE THREAD

**Issue by KelSolaar** [nerdvegas/rez#847]
Here is the output from running `rez-env` on Windows under Rez 2.53.0:

```
> C:\Users\thomas>rez-env
'echo.' is not recognized as an internal or external command,
operable program or batch file.
You are now in a rez-configured environment.
'echo.' is not recognized as an internal or external command,
operable program or batch file.
resolved by thomas@MORGOTH, on Thu Feb 06 14:42:45 2020, using Rez v2.53.0

requested packages:
~platform==windows           (implicit)
~arch==AMD64                 (implicit)
~os==windows-10.0.18362.SP0  (implicit)

resolved packages:
```

@bfloch : I don't know what was the intent but it feels like a typo: https://github.com/nerdvegas/rez/commit/9dcb40204c0fae14283d1dbd866d0915b390e0aa#diff-b1aa7ab463cecaa539089580fe418dc2R327

Cheers,

Thomas

**Comment by bpabel** [comment]
`echo.` is a valid windows batch command. 

What terminal are you using? Is it possible you're calling some other `cmd.exe` besides the one at `C:\Windows\System32\cmd.exe`?  Maybe check your PATH to make sure you're getting the right one.

**Comment by KelSolaar** [comment]
I am launching the correct one via the Windows Menu shortcut. Does not work:

```
Microsoft Windows [Version 10.0.18363.592]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\thomas>echo.
'echo.' is not recognized as an internal or external command,
operable program or batch file.
```

Launching the .exe directly works, I noticed that the shortcuts starts in `%HOMEDRIVE%%HOMEPATH%` where I add an empty `echo` file :)

All good!
