### ISSUE TITLE
"Resolve" "QToolButton" does not work anymore with "PySide 2".

### ISSUE THREAD

**Issue by KelSolaar** [nerdvegas/rez#852]
I got `rez-gui` working with Python 3 and PySide 2 via some minor patches, i.e #850 and #851 and I noticed that the Resolve button is busted, no menu, no nothing:

![image](https://user-images.githubusercontent.com/99779/73975038-62324e80-498a-11ea-8f68-4bd708b81fda.png)

Cheers,

Thomas

**Comment by JeanChristopheMorinPerso** [comment]
From looking at PR #851 , we can now close this. Thanks @KelSolaar for the fix.
