### ISSUE TITLE
any way to take advantage of 'this.root' inside a build_command ?

### ISSUE THREAD

**Issue by col-one** [nerdvegas/rez#859]
First of all thanks for this great tool! 
I would like to know if is it possible to take advantage of 'this.root' inside a build_command ?

as instance: 
build_command = "python3 {this.root}/build.py"

Thanks !

**Comment by nerdvegas** [comment]
Cheers. {this.root} is not available, however {root} is:
https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#build_command

Thx
A

**Comment by col-one** [comment]
Awesome! I missed this part, Thanks
