### ISSUE TITLE
pip install old version

### ISSUE THREAD

**Issue by ClementHector** [nerdvegas/rez#864]
Hi,

Why the version installed with pip are la 2.0.ALPHA.52?
Is the deployment with pip not maintained?

Thanks a lot

Clement

**Comment by instinct-vfx** [comment]
The canonical way to install Rez is to use the provided installation script. See the wiki for information on the reasons for this: https://github.com/nerdvegas/rez/wiki/Installation

I do agree though that we should either remove the old versions or provide current ones.
I personally would vote for providing releases automatically through pypi too.

**Comment by ClementHector** [comment]
Thanks,

it is true that it would be more practical especially that I install bleeding-rez by pip.

Clement

**Comment by nerdvegas** [comment]
Hey Clement,

Installation of rez via pip may appear to work in many cases, but there are
cases where that can break. This is why rez is installed via its
installation script. We hit this issue years ago and a contributing studio
(Luma) put a lot of effort into the issue, going so far as to get a distlib
patch accepted as part of our solution to the problem. I would be careful
assuming that your pip-based rez installation is going to work in all cases.

Having said that I agree that pip version should be maintained and
automatically released via workflow. However, I think the pip-ed rez should
be API only and not provide cli tools. This requires only a minor change to
setup.py/install.py.

Specifically:
- some nominated env-var should be used to enable/disable installation of
rez cli tools (eg _REZ_INSTALL_PY=1)
- install.py should set this
- setup.py checks it and only installs cli tools if enabled

Cheers
A

**Comment by Gaspounet** [comment]
Hi there,

I totally understand why you don't want to maintain the pip install version, but I am wondering then what would be the best practice to install it in a venv?

Thanks,
Gasp
