### ISSUE TITLE
Question - How do I override a package's attribute on-release?

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#894]
I've added a custom attribute to Rez's schema called `foo`. I want `foo` to be `True` on `rez-release` and by default to be false or un-defined.

How can I do this? With release hooks? Attempting to set the `self.package.foo` directly inside of the `FooReleaseHook` class raises the exception `"can't set attribute"`. I've also tried adding it by adding a line like `self.package.config.override('foo', True)` in the `CheckinReleaseProcess.build` method. But neither are showing up on release. 

Is there another, better way to do this? For context, I'm using a company fork of Rez so either of those methods are correct (but still aren't showing) then it could be a bug. Just wanted to know if my method for doing this is wrong.

**Comment by instinct-vfx** [comment]
Can't you just have it as a regular early bound package attribute and in the method check if you are releasing using
```
build.build_type 
One of 'local', 'central'. The type is central if a package release is occurring, and local otherwise.
```

Just a thought, i have not tried this

**Comment by ColinKennedy** [comment]
That's an idea, though (for context) we're extending the release function to have a flag called "--ignore-foo" and when that flag is added, we want the attribute to be true.

So essentially, though the data is added as part of the released package.py, it's not really expected for users to define it in their own package definition file.

**Comment by instinct-vfx** [comment]
Ah i see. I wonder if it is necessary to tweak the release function. If you add a custom build arg and then check for both custom build arg AND being a release that should do the trick, It does of course have to stay in packages and is easy to get around.

**Comment by ColinKennedy** [comment]
Just wanted to circle back on this issue.

I was able to set the data directly onto the package. I just didn't "see" the data on-serialization because I'd registered the attribute as release-specific data so print_info wasn't showing the information by default.

In short, everything was actually working as expected, I just wasn't seeing it in my simple case. Let's close this issue :+1:
