### ISSUE TITLE
Are "."s allowed in Rez package names?

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#897]
`rez-pip --install backports.tempfile --python-version=2.7` creates a Rez package with "." in its name. I know that rez-pip does some conversions to PyPI package name / version to make it compatible with Rez. According to the docs, only alphanumeric + "_" is supported. https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#name

Is the "." which rez-pip creates allowed by Rez and the docs are out of date? Or does "." need to be converted to "_" or some other allowed character?

**Comment by instinct-vfx** [comment]
Converting characters in pip packages is not really possible (e.g. what if there is a package called backports.tempfile and a package called backports_tempfile). I was not really aware (even though i might have read it) about this part in the Wiki. That said we are using pip packages with dots to quite some extent without issues (e.g. Qt.py, path.py etc.).

It is an interesting questions nevertheless and the docs should be consistent with the code of course. I reckon we might need @nerdvegas to answer this?

**Comment by nerdvegas** [comment]
Hey, yeah dots are supported, the docs are out of sync.

Bw aware that you would have issues if you had two packages like a.b and
a_b though. The env var prefix for each would become REZ_A_B.

Cheers
A

**Comment by ColinKennedy** [comment]
Thanks for the head's up! I'll pass this info along
