### ISSUE TITLE
ResolvedContext.get_environ() does not seem to respect parent_environ as a parameter

### ISSUE THREAD

**Issue by jporath** [nerdvegas/rez#898]
Hi all!

Really new here, but I've been implementing Rez at the studio I work at (CoSA VFX) and ran into what I believe is a bug -- or possibly I'm doing something dumb?

When I call rez.ResolvedContext.get_environ() to get a list of environment variables, it does not seem to respect the parent_environ variable passed to it. The simplest repro steps I can give you, from a fresh python shell:

```
from rez.resolved_context import ResolvedContext
ResolvedContext([]).get_environ() == ResolvedContext([]).get_environ({'TEST_VARIABLE':'VALUE'})
> True
```

The second call, with parent_environ set, doesn't pass through my TEST_VARIABLE variable. Although I make no package requests to ResolvedContext in that example, the same thing happens if I do.

I've tested this on MacOS 10.15 with Rez 2.40.4 and Windows 10 with Rez 2.40.3.

Any help would be much welcome!

**Comment by nerdvegas** [comment]
Heya,

The environ you get here will only contain env vars *that any given package
has interacted with *(and I believe the get_environ docstring should be
made clearer in this regard). So if you pass a parent_environ with a var
that no package touches, it won't be included in the result. If you take
the dict you passed to this func, then update() it with the result, you
should have the actual resulting environ dict.

Imo it would make sense to add a `full=False` or similar keyword arg to
make this more explicit.

Hth
A

**Comment by jporath** [comment]
That makes sense! Thank you for the prompt response. Apologies if this was
answered elsewhere, I didn't find anything in a search. :)

-J
