### ISSUE TITLE
Package caching does not work on windows due to device not being implemented in py2 on Windows

### ISSUE THREAD

**Issue by instinct-vfx** [nerdvegas/rez#912]
Package caching is by default configured to not allow caching on the same device. The check for "same device" does not work on windows though and always results in a false positive.

There are multiple possible ways to fix this:
- Add version and platform checking to said function checking for the device. python < 3.4 and windows being problematic. Not sure how to deal with this though as this would make the setting be ignored completely.
- Add version and platform checking to the default config (similar to coloring). That would be rather transparent?

Oppinions?

**Comment by nerdvegas** [comment]
given this is deprecated py2 only, and that checking py version in config would require more work, I think simply ignoring the device in this case would suffice. Even if pkg caching occurred on the same device, it would hardy be a big issue.
