### ISSUE TITLE
Miss-leaded error message while building with invalid package metadata

### ISSUE THREAD

**Issue by davidlatwe** [nerdvegas/rez#915]
Hi everyone 👋🏼 

While I was trying to `rez-build` my Python project, I got an error message saying that I have no build system to use :
```
01:21:32 ERROR    BuildSystemError: No build system is associated with the path ...
```
But the doc says if `package.py` have `build_command` attribute, custom build system should be used.

Here's what my `package.py` looks like:

```python
name = "foo"

authors = ["davidlatwe"]

description = "Awesome foo"

version = "0.1.0"

requires = [
    "python*",
]

variants = [
    ["default"],
]


build_command = "some fancy command"


def commands():
    env.PYTHONPATH.append("{this.root}")

```

I think my `package.py` was fine, at least should be enough to summon custom build system.

So I start to hunt the cause, and I found it was because my required package "python*" some how failed the schema validation.

And here's the reason why the `PackageMetadataError` and `PackageRequestError` was not raised :

https://github.com/nerdvegas/rez/blob/103270d1b39e139223dec706236cbaffc4e14669/src/rez/build_system.py#L31-L36

Any reason why it's being ignored ? I think there should be at least a warning message. 🤔

**Comment by instinct-vfx** [comment]
I agree that the error is somewhat misleading. `python*` is not a valid request though, so the fail itself is expected. What did you want to request? Any python version? That would be just `python`. The reason for your string not to be a valid request is that Rez uses `-` as a separator between package name and version. If there is no `-`, then Rez considers the whole string to be the package name and `*` is not a valid character for package names, hence the schema validation fails.

**Comment by davidlatwe** [comment]
Thanks for the info ! Yes, I changed the request package name to `python` or `python-*` and it resolved. 👍🏼

**Comment by nerdvegas** [comment]
Agreed this should be a warning, I'll make this change.

Please be aware that by specifying `python-*`, you're specifically using
something called "requirements expansion" (which is fine), see
https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#requirements-expansion


Cheers
A

**Comment by nerdvegas** [comment]
Actually I'll make this an error - this then matches existing behaviour when build system is know (eg, a CMakeLists.txt is present)
