### ISSUE TITLE
[wiki] Generate on tags so we can add version number

### ISSUE THREAD

**Issue by j0yu** [nerdvegas/rez#930]
Following from #831 

Might be good to change the Wiki CI to release on tag/release events so we can also add the version number to the sidebar

That way, it will be easier for people to be aware of the current, latest release the Wiki is generated from. 
- Wiki is probably the most popular rez related page, as well as being the default [help] page
- Not everyone visits the [releases page], so it might help bring attention to people of new releases

[![latest release](https://img.shields.io/static/v1?label=release&message=<TAG>&color=informational)](https://github.com/nerdvegas/rez/releases/tag/<TAG>)

```
[![latest release](https://img.shields.io/static/v1?label=release&message=<TAG>&color=informational)](https://github.com/nerdvegas/rez/releases/tag/<TAG>)
```
[help]: https://github.com/nerdvegas/rez/blob/2.64.0/src/rez/rezconfig.py#L985
[releases page]: https://github.com/nerdvegas/rez/releases

**Comment by nerdvegas** [comment]
I think updating the wiki only on release does make sense actually, as does
including the release version on the docs homepage.
A

**Comment by j0yu** [comment]
Ready to review! Was also doing some maintenance to switch to use this standalone script for Python 3.7
