### ISSUE TITLE
`rez bump` command?

### ISSUE THREAD

**Issue by dbr** [nerdvegas/rez#931]
I was going to write a small helper script to automate the process of releasing a new version, which for me involves:

- Check `git log` to check what commits have been made since last release (mostly to verify I haven't already bumped the version number)
- Edit the version string in `package.py` to, most often, just increase the minor version
- Check there are no uncommitted changes
- `git add package.py && git commit -m "Bump version" && git push`

..before running `rez release`. None of the steps are too hard on their own, but adds up to be a little tedious and accident prone (quite often I've forgotten to bump the version string as per #914)

Before I write this as a standalone script, is this something that could potentially be useful as part of rez itself? I'm unsure as seems like it could be useful, but also might be a little too workflow-specific to be in core rez?

**Comment by instinct-vfx** [comment]
I often use bumpversion to do this. So basically:

- Code
- Commit & Push
- Run bumpversion with the desired level (patch, minor, major)
- release

**Comment by rfletchr** [comment]
you might consider a pre-commit hook.

```bash
master=$(git show master:package.py | grep version | cut -d'"' -f 2)
current=$(git show HEAD:package.py | grep version | cut -d'"' -f 2)

if [ "$master" = "$current" ]; then
	echo "version bump required"
	exit 1
fi
```

it simply compares the 2 versions and errors if master matches your current branch

**Comment by nerdvegas** [comment]
IMO this is outside the scope of rez. Both previous suggestions (separate
bumpversion tool, pre-commit hook) sound like reasonable solutions.

Thx
A

**Comment by dbr** [comment]
Yep agreed - thanks for the suggestions!
