### ISSUE TITLE
Document requires version specification syntax

### ISSUE THREAD

**Issue by bpabel** [nerdvegas/rez#933]
As a developer creating rez packages with dependencies on specific versions of other packages, I want to know what the version dependency syntax is for the `package.py` `requires` attribute, so that I can correctly and intuitively indicate the package dependencies.

The Package Definition Guide gives [a couple examples](https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#requires), but the entire version specification syntax doesn't appear to be documented anywhere.

**Comment by nerdvegas** [comment]
Full spec here: https://github.com/nerdvegas/rez/wiki/Basic-Concepts#package-requests

However, I think it's worth adding a link to this in the requires docs, I will add that.

**Comment by nerdvegas** [comment]
just fixed in master, our new wiki github action should pick it up and update wiki shortly.
