### ISSUE TITLE
How do you record a second package version and read it during rez-build?

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#936]
I need 2 Rez package versions. One is the real "version" which would be used for unleash and Rez resolves. The other is the "base" version which the real version is built from.

e.g. Imagine I have an external Rez package from the internet like "foo PyPI package, version 1.2.3". There's a bug in this version and I've contacted the maintainers to fix it and they plan to fix it for version 1.2.4. But in the meantime I need a patch for production, so I make my own custom version 1.2.3.1, so I can rez-release the patch in advance of the maintainer's 1.2.4 patch.

The trouble is, in rez-build I use the `REZ_BUILD_PROJECT_VERSION` environment variable to query something about the "foo" package. This works for "real" versions of the package. But it doesn't work for 1.2.3.1 because that's my custom patch.

So I checked out Rez's schema and noticed this

```python
    Required("name"):                   basestring,
    Optional("base"):                   basestring,
    Optional("version"):                Or(basestring,
                                           And(Version, Use(str))),
```

So I thought "`base` sounds perfect" and then added it to my package.py

```python
name = "foo"
version = "1.2.3.1"
base = "1.2.3"
```

My plan was to change my code in rez-build to refer to `base` instead of `version`, if base exists. But I don't see any environment variable to refer to base.

## Summary
What is base actually used for? Am I using it correctly? If so, can it please be made accessible during rez-build?

And lastly, is there an easier way to achieve what I'm looking to do?

**Comment by nerdvegas** [comment]
First, stay away from base!! That is not what you think it is. See the
diagram here: https://github.com/nerdvegas/rez/wiki/Variants#disk-structure.
Base is the version directory where the package is located.

You can add any arbitrary attribute to your packages, so you could just add
a "vendor_base_version" or similar. You will be able to access that via the
rez API easily, however it won't be exposed as an environment variable. But
all you need to do to expose it as an env var, is to do that yourself in
your commands:

# in package.py
vendor_base_version = '1.2.3'

def commands():
    env.PATH.append('{root}/bin')
    env.MYPKG_VENDOR_BASE_VERSION = this.vendor_base_version

If you need general support for this then you just need to ensure that you
write the base version into some env var with a standard name derived from
the package name. If you want to get really fancy, you might be able to do
that with
https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#package-preprocessing,
though I don't know if it would be possible (or advisable) to alter the
commands function in the preprocessor.

Hth
A

**Comment by ColinKennedy** [comment]
Thanks Allan, this helps a lot! An extra attribute should work well for my case.
