### ISSUE TITLE
Error building platform variants (Duplicate of https://github.com/nerdvegas/rez/issues/498)

### ISSUE THREAD

**Issue by reformstudios** [nerdvegas/rez#947]
From a linux workstation running centos 7...

When I set variants in package.py as follows : 

```variants = [["platform-linux"], ["platform-darwin"]]```

When I `rez build` I get the following error : 
```

================================================================================
Building rv-7.9.0-dev...
================================================================================

================================================================================
Building variant 0 (1/2)...
================================================================================
Resolving build environment: python platform-linux
resolved by patrick-macdonald@z640-01, on Wed Sep 02 13:03:50 2020, using Rez v2.67.0

requested packages:
python                
platform-linux        
~platform==linux      (implicit)
~arch==x86_64         (implicit)
~os==CentOS-7.8.2003  (implicit)

resolved packages:
arch-x86_64         /rs/apps/rez/packages/int/arch/x86_64                                                 
os-CentOS-7.8.2003  /rs/apps/rez/packages/int/os/CentOS-7.8.2003                                          
platform-linux      /rs/apps/rez/packages/int/platform/linux                                              
python-2.7.5        /rs/apps/rez/packages/int/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.8.2003  

Invoking custom build system...
Running build command: python /rs/studio/_repos/rez/packages/app/rv/7.9.0-dev/build.py
Building...7.9.0-dev : platform-linux

================================================================================
Building variant 1 (2/2)...
================================================================================
Resolving build environment: python platform-darwin
The context failed to resolve:
The following package conflicts occurred: (platform-darwin <--!--> ~platform==linux)
The build environment could not be resolved:
The following package conflicts occurred: (platform-darwin <--!--> ~platform==linux)
```

I've seen reference to setting `implicit_package" to [] in another ticket https://github.com/nerdvegas/rez/issues/291#issuecomment-173732906

```
In rez packages you can override settings. So if you wanted to use
rez-build to install, but you don't actually need to build anything, you
could override the "implicit packages" setting and set it to nothing. That
way the build will happily iterate over every variant, even though you
aren't actually on that platform. I haven't tested this but it should work.
Here's what you'll want to add:

with scope('config') as config:
config.implicit_packages = []
```

but I've not been able to get that to work.

What's the correct approach to building packages for platforms other than the current implicit platform?

**Comment by nerdvegas** [comment]
It may be that the package config isn't getting read for implicit_packages, I'll have to take a look at that.

In the meantime you could:
```
]$ REZ_IMPLICIT_PACKAGES= rez-build -i
```

Implicits are just a way to add a set of packages to every request automatically. Rez uses standard packages to model the current system. In normal circumstances, the behaviour you're getting is correct - of course the build env should fail to resolve if you're attempting to build something that has a system requirement not matching the current system. But your edge case is valid, and for that case, overriding implicit_packages in the package.py needs to work.

**Comment by reformstudios** [comment]
Thanks Allan,
I tried what you suggested but it's still erroring. This is when I run it on linux.

```
> patrick-macdonald@z640-01:/rs/studio/_repos/rez/packages/app/rv/7.9.0-dev $ REZ_IMPLICIT_PACKAGES= rez-build -i

================================================================================
Building rv-7.9.0-dev...
================================================================================

================================================================================
Building variant 0 (1/2)...
================================================================================
Resolving build environment: python platform-linux arch-x86_64
resolved by patrick-macdonald@z640-01, on Thu Sep 03 14:43:54 2020, using Rez v2.67.0

requested packages:
python          
platform-linux  
arch-x86_64     

resolved packages:
arch-x86_64         /rs/apps/rez/packages/int/arch/x86_64                                                 
os-CentOS-7.8.2003  /rs/apps/rez/packages/int/os/CentOS-7.8.2003                                          
platform-linux      /rs/apps/rez/packages/int/platform/linux                                              
python-2.7.5        /rs/apps/rez/packages/int/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.8.2003  

Invoking custom build system...
Running build command: python /rs/studio/_repos/rez/packages/app/rv/7.9.0-dev/build.py
Building...rv : 7.9.0-dev : platform-linux/arch-x86_64
src_path : //rs/apps/rv/7.9.0-dev/platform-linux/arch-x86_64 : True
dest_path : /home/patrick-macdonald/packages/rv/7.9.0-dev/platform-linux/arch-x86_64 : True
Packages already exists. Please delete /home/patrick-macdonald/packages/rv/7.9.0-dev/platform-linux/arch-x86_64 before installing.

================================================================================
Building variant 1 (2/2)...
================================================================================
Resolving build environment: python platform-osx arch-x86_64
14:43:55 ERROR    PackageNotFoundError: Package could not be found: platform-osx

```

I'm wondering if I need to build the implicit platform-osx platform anyway? Can I do that from linux ? Or do I need to do that from an osx box and then rez release to make it available on my linux machine? 

Thanks again.
p.

**Comment by reformstudios** [comment]
I tried the code you have in the docs and it seems to fix the issue.... to some extent. It means I can build only for linux on linux and osx on osx... 

```
@early()
def variants():
    from rez.package_py_utils import expand_requires
    requires = ["platform-**", "arch-**", "os-**"]
    return [expand_requires(*requires)]
```

I can certainly take this workaround... but there are a few things that I'm still unsure of:

- The above fix works when building ON each platform, but for simple packages where I'm not actually doing any building(eg compiling) on each platform, I'd like to be able to build all platform variants from linux, so I'm still looking for a way to achieve this if you can think of anything. 

- I'm still getting a package conflict when I call `rez env rv`. I can prevent the error by using `--ni`, but I wonder if that has any unforeseen implications I might not be aware of?

**Comment by nerdvegas** [comment]
There's no such thing as an "implicit platform". Implicit packages are just
a list of configured requests that are automatically added to every request.

If you have a variant that requires platform-osx, then you need that
package to exist. You don't even need to build it, you could just create it
manually in the correct format and it will work. It is simply a matter of
having the correct package.py in the correct location, rez will then ingest
it.

Hth
A

**Comment by reformstudios** [comment]
Thanks, sorry yes I meant to say `platform implicit package`.

Ok I've made some progress, I can now build the platform variants without error using  `REZ_IMPLICIT_PACKAGES= rez-build -i`. 

I was also able to release using `REZ_IMPLICIT_PACKAGES= rez release --ba force` (without this I get the package conflict).

I'm passing a "force" argument to my build script so I can remove any existing package definition that I've released and re-copy the payload over. Without this I'd be forced to version up the package. 

Ignoring the danger of going off topic here, with vendor packages, I assume the standard approach is to append a local version to the vendor version; eg `vendor_version = "1.2.3"; version=vendor_version+"-local_1.0.0"` If I want to pass the vendor version to to build.py I need to via the build command (eg `build_command = "python {root}/build.py version=" + vendor_version`) or is there a better way ? I appreciate this is probably another case of something that's up to the developer rather than any rez convention.... but thought it would be worth asking in case there's any best practice. 

Thanks again.

**Comment by nerdvegas** [comment]
That's how you'd do it at the moment yeah. However this reminds me, I think
it'd be useful to have some rez tool that can inspect the current
"developer" package (that's the package in cwd that is getting built). So
for example, in your build script you could invoke 'rez-build --attrib
vendor_version' which would just print 1.2.3 to stdout.

Thx
A

**Comment by JeanChristopheMorinRodeoFX** [comment]
@nerdvegas That's in PR, see https://github.com/nerdvegas/rez/pull/539.

The other way would be to have a common build utilities package that you could import in your build script that would know your naming convention and extract the right part of the version for you, like a regex for example.

**Comment by reformstudios** [comment]
Thanks all.

`It may be that the package config isn't getting read for implicit_packages, I'll have to take a look at that.` - nerdvegas

@nerdvegas Shall I take a look at what's causing the "with scope" approach to excluding implicit packages not being respected in the current build? Happy to get my hands dirty to help out... but might need a little pointer as to where to begin looking. 

Ah, and I just found this ticket (https://github.com/nerdvegas/rez/issues/498) which is my exact problem. It sounds from what you wrote that it's quite a major change to the build logic that's required for the config to get updated on the fly.

```
 The code isn't structured
such that package config overrides become globally visible during a package
build
```

Happy to take a look but if it's a structural change, then that'll be well outside my area of expertise! 
Cheers
p.

**Comment by reformstudios** [comment]
Duplicate of [issue 498.](https://github.com/nerdvegas/rez/issues/498)

**Comment by nerdvegas** [comment]
I think it'd be reasonable to put a fix in specifically to support
implicit_packages override.

Thx
A
