### ISSUE TITLE
package_maker.make_package does not write out build_command

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#967]
If you make a Rez package which contains a build command, it doesn't write to-disk.

## Reproduction Steps

Run this:
```python
from rez import package_maker

name = "something"

with package_maker.make_package(name, "/tmp/somewhere") as package:
    package.version = "1.0.0"
    package.build_command = "blah"
    print('command', package.build_command)

print('command', package.build_command)
```

The print statements both show that `build_commands` is set to `"blah"`. But the `package.py` which is written to disk doesn't include it.

```python
# -*- coding: utf-8 -*-

name = 'something'

version = '1.0.0'

timestamp = 1603681483

format_version = 2
```

## System Details
CentOS 7.8
Rez version: 2.68.4
Rez API Python version: 3.6.8 (it happens even if Rez is built from Python 2.7, too)

**Comment by nerdvegas** [comment]
So this is actually correct behaviour.

'build_command' is only a valid attribute in _developer_ packages, ie unbuilt packages. The build_command attribute is stripped from installed packages (it isn't of use at this point). A 'package' in rez describes what an installed package looks like, hence build_command not being retained.

Is there a specific use case you have in mind?

**Comment by ColinKennedy** [comment]
My intent is to make a (developer, non-installed) Rez package which I could use to build a package. If package_maker.make_package isn't meant for that, could you please point to how developer packages are meant to be built? Sorry if I missed how to do this in the documentation.

**Comment by nerdvegas** [comment]
Ah right. There has never been API support for creating a developer package. Package_maker can be used, but as you've discovered, you can only create a subset of what can exist in a developer package. It's not as simple as allowing all attributes either - early/late binding would have to be supported too. This use case has never come up, developer packages are always created by a person.

I'm closing this ticket since this would actually be a feature request.

**Comment by davidlatwe** [comment]
Hey @ColinKennedy , you may have a look at [this](https://github.com/davidlatwe/rez-ghostwriter) if you are still interested. And welcome to submit issue/PR there.

**Comment by ColinKennedy** [comment]
@davidlatwe Thanks for that link, this looks to be exactly what I needed!
