### ISSUE TITLE
See which resolve caused package conflicts

### ISSUE THREAD

**Issue by j0yu** [nerdvegas/rez#972]
Inspired by #971 

It will be nice to have something similar for when there is package conflict.

e.g. when a resolve errors with:

```
The context failed to resolve:
The following package conflicts occurred: (python-2 <--!--> python-3)
```

and you want to find out:
- which packages/dependency chain requested `python-2`, and 
- which packages/dependency chain requested `python-3`

Rather than digging through a re-resolve with `rez env --verbose`, include the resolve/request information in the initial error message like:

```
The context failed to resolve:
The following package conflicts occurred: (python-2 <--!--> python-3)
python-2: pymel <-- maya-2020.2 <-- proj_env_foobar-0.2
python-3: houdini-18.5
```

**Comment by j0yu** [comment]
Considered closed by #1083

**Comment by nerdvegas** [comment]
Yeah I agree this would be useful actually. It's really just displaying the
graph in cli format, where each line is a chain in the resolve DAG
terminating at one of the package requests involved in the conflict.

**Comment by davidlatwe** [comment]
Adding context from the time I was doing #1083 ：）

Yes, understanding the conflict/cycle by reading the path from the failure point toward init requests like the format above could be easier.

But the path growing from failure point may split if it's related to multiple requests, which may not easy to represent in CLI ? 

This was the main reason of #1083 describing the failure starting from init requests.

**Comment by nerdvegas** [comment]
Yeah sorry David I've been a bit distracted this morning, and yes your PR
addresses this already. What I was actually thinking about is a similar CLI
representation of the graph, for any nominated package. Ie, the CLi
equivalent of `rez-context -g --pp {pkg}` - so you can see how a given
package version was selected, even in a successful resolve.
