### ISSUE TITLE
Installation With Python >=3.9 Fails ('HTMLParser' object has no attribute 'unescape')

### ISSUE THREAD

**Issue by b0ssi** [nerdvegas/rez#980]
## Rez version

2.69.6

## Platform and Operating System

* Python-3.9
* Arch Linux

## Contextual Information

I'm attempting to install rez.

## Simplest possible steps to reproduce.

Using an environment with `Python >=3.9` installed, attempt a manual install:

 $ tar -xazvf 2.69.6.tar.gz
 $ cd rez-2.69.6
 $ python ./install.py

### Expected Result

Successful installation

### Actual Result

Installation fails with the following:

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/opt/rez/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
            from setuptools.dist import Distribution, Feature
        File "/opt/rez/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
            from setuptools.depends import Require
        File "/opt/rez/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
            from .py33compat import Bytecode
        File "/opt/rez/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
            unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
    ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-w0ivy6a5/
    WARNING: You are using pip version 19.1.1, however version 20.3.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    [...]

The reason seems to be rez being bundled with `setuptools-41.0.1-py2.py3-none-any` (and `pip-19.1.1`), which is now incompatible with Python-3.9 (and above), as `HTMLParser.unescape` got removed in `Python-3.9`.

**Comment by nerdvegas** [comment]
I highly suspect that the best fix for this will be https://github.com/nerdvegas/rez/issues/982

**Comment by b0ssi** [comment]
That sounds like it should fix the issue, if it's instead using the local venv environment that corresponds with the Python installation that gets picked up.

**Comment by b0ssi** [comment]
This has been working for a while now since, thanks :+1:
